### ISSUE TITLE
Proxy issue

### ISSUE THREAD

**Issue by xlinxlin** [nf-core/ampliseq#100]
Hi, I had a proxy issue when I ran `nf-core/ampliseq`
```
(base) sysgen@supermicro02:~$ nextflow run nf-core/ampliseq -profile test,docker
N E X T F L O W  ~  version 19.07.0
Pulling nf-core/ampliseq ...
WARN: Cannot read project manifest -- Cause: Unable to tunnel through proxy. Proxy returns "HTTP/1.1 407 Proxy Authentication Required"
Cannot find `nf-core/ampliseq` -- Make sure exists a GitHub repository at this address `https://github.com/nf-core/ampliseq`
```
How can I set proxy in nextflow? Thanks!

**Comment by d4straub** [comment]
Not that I know of. 
I leave it open a little longer in case somebody comes by soon who has a more optimistic answer.

**Comment by apeltzer** [comment]
You can download the pipeline and all required files using the `nf-core download` feature. If your installation doesn't allow a simple HTTP proxy, which you can configure like [this](https://www.nextflow.io/docs/latest/config.html#environment-variables) there is not much we can do about it unfortunately.
