### ISSUE TITLE
Updating dependencies in nfcore/ampliseq:1.0.0 container?

### ISSUE THREAD

**Issue by DiegoBrambilla** [nf-core/ampliseq#101]
Hello everybody,
So far I have prepared a [nf script](https://github.com/DiegoBrambilla/rrna-ampliseq/blob/dev/until_cutadapt.nf) that relies on R-DADA2 instead of the R-DADA2 plugin for QIIME2. Some R scripts are stored in [/bin](https://github.com/DiegoBrambilla/rrna-ampliseq/tree/dev/bin) for the moment and later on I plan on uploading them into a conda channel, as we discussed [before](https://github.com/nf-core/ampliseq/issues/94).

I have updated [my environment.yml](https://github.com/DiegoBrambilla/rrna-ampliseq/blob/dev/environment.yml) basing on the [nfcore/ampliseq:1.0.0](https://hub.docker.com/r/nfcore/ampliseq/dockerfile) container and added the dependencies required to run the R scripts.
I would like to update the environment.yml stored in the Docker image so that it will be possible to run my pipeline on UPPMAX, how can we achieve that?

Best
Diego

**Comment by d4straub** [comment]
build your own container based on your environmental.yml, e.g. in your piepline folder with (docker and singularity required):
```
docker build .
docker images #shows image tag
docker run -d -p 5000:5000 --name registry registry:2
docker image tag <your image tag>  localhost:5000/ampliseq-dev
docker push localhost:5000/ampliseq-dev
SINGULARITY_NOHTTPS=true singularity build ampliseq-dev.img docker://localhost:5000/ampliseq-dev
```
and use this container in the pipeline by adding 
`-with-singularity ampliseq-dev.img`

I would advice you to use the [environmental.yml of 1.1.0](https://github.com/nf-core/ampliseq/blob/master/environment.yml) because 1.0.0 has some channel issues (these were modified after the release). Also be aware that the environment might be updated in the dev branch soon.

**Comment by DiegoBrambilla** [comment]
Thank you, really appreciate the detailed information.
I will test it tomorrow and see how it goes.

**Comment by apeltzer** [comment]
And, to be frank: Once a pipeline is released, there won't be any changes to existing/released containers for reproducibility reasons. You could work on making 1.2.0 for example if you want to, or keep your local copy/version as Daniel suggested it above, but changing released versions/containers is a bad idea as we can't guarantee reproducibility then anymore.

**Comment by DiegoBrambilla** [comment]
@apeltzer it makes perfect sense.
@d4straub I have my test dataset on a HPC cluster (UPPMAX) and I have no root privilege there.
How can I build my own container with the method you suggested with singularity alone?
Thank you!

**Comment by d4straub** [comment]
As far as I know, you cant do it with singularity alone. I make test containers usually locally and transfer them.

**Comment by DiegoBrambilla** [comment]
Hi,
I have managed to upload to DockerHub a [container](https://hub.docker.com/r/diebra/rrna-ampliseq) updated to 1.1.0 ampliseq version that contains all of the necessary dependencies for such scripts in environment.yml.
I was curious to know how come you do not need to specify the location of `main.nf` on GitHub in the command line. I know that you can link a GitHub repository to a DockerHub repository, maybe this is how `main.nf` is used a default, without calling it.

example:
```
nextflow run nf-core/ampliseq \
    -profile singularity \
    --reads "data" \
    --FW_primer GTGYCAGCMGCCGCGGTAA \
    --RV_primer GGACTACNVGGGTWTCTAAT \
    --metadata "data/Metadata.tsv"
```
> nfcore/ampliseq
 is the path to the container in DockerHub. At first I thought you just specifiy the remote location of the docker image in some config file and then run, but I saw no mention of it in any document of this Git repository.

I would be grateful if you could tell me more on how to set the pipeline to work with content from from DockerHub and GitHub, so that I don't have to pull the image from Docker.
Any additional information on the profiles you use, e.g. uppmax, are greatly appreciated.

Thank you

**Comment by apeltzer** [comment]
Hi Diego!

the ideal solution would be to have all dependencies in the `environment.yml` and then have everything in the environment / PATH upon execution - might be that I misunderstood but you might have that already in place now? 

Nextflow can read any repository given that there is a `nextflow.config` in the root of that repository - therefore if you specify e.g. the `nextflow run nf-core/ampliseq` it finds the `nextflow.config`, which lists the `main.nf` to be executed [by default](https://github.com/nf-core/ampliseq/blob/57e1ee2f9028d0a8c5838ee8aa8cf4b383f61174/nextflow.config#L109) 

With respect how to run the profile(s), please refer to the documentation about [Profiles](https://www.nextflow.io/docs/latest/config.html#config-profiles). In nf-core we simply define the URL to the docker image with the software dependencies to be `nf-core/<pipelinename>` on DockerHub and upon release there is an image automatically built with the exact same version number than the pipeline code release on GitHub automatically, too. 

You can setup automatic builds on your own DockerHub account (create one, they are free) and use the URL to that image for testing - we typically set these in the `nextflow.config` under `container = ....`.

**Comment by DiegoBrambilla** [comment]
Hi Alexander!

I am aware of the ideal solution, it has been discussed in this [issue](https://github.com/nf-core/ampliseq/issues/94#issuecomment-514192158). Until I set a dedicated conda channel, the strategy is, during the building of the Docker image, to `git clone` the [repository](https://github.com/erikrikarddaniel/eemisdada2) and symlink the R scripts `to $PATH` .

I am now applying the [pipeline settings](https://www.nextflow.io/docs/latest/sharing.html#publishing-your-pipeline) and the [automated build](https://docs.docker.com/docker-hub/builds/). 

Thank you for the detailed reply, let's keep in touch.

**Comment by DiegoBrambilla** [comment]
Hello all,
After applying the aforementioned changes to have Nextflow call the remote repository, I still fail to and receive this error message:

`Unknown project `DiegoBrambilla/rrna-ampliseq` -- NOTE: automatic download from remote repositories is disabled`

the command line I use is:

`nextflow run DiegoBrambilla/rrna-ampliseq -profile test --trunclenF 150 --trunclenR 150 --maxconsist 30 --minoverlap 10 --overab 4 --nsamples 4`

I have triggered an [automated build for the Docker container](https://cloud.docker.com/repository/docker/diebra/rrna-ampliseq) through my local GitHub dev branch of this pipeline and modified the [manifest](https://github.com/DiegoBrambilla/rrna-ampliseq/blob/dev/nextflow.config#L119) and the [container](https://github.com/nf-core/ampliseq/blob/57e1ee2f9028d0a8c5838ee8aa8cf4b383f61174/nextflow.config#L49) of `nextfow.config` accordingly.

Do you see any kind of error I'm missing?
Also, tell me if you need further information to make it reproducible.

**Comment by apeltzer** [comment]
Hi @DiegoBrambilla !

in general that should be fine though I have to say that the entire discussion here is a bit off topic. (or the title misleading now ;-)) - can you open separate issues for separate problems? 

The container dependencies in 1.0.0 will stay fixed as this is a basic requirement for reproducibility. I'll release 1.1.1 today with the latest stable QIIME2 release included, so if you want to use that that should be good 👍
