### ISSUE TITLE
rnaseq/smrnaseq ERROR  : No valid /bin/sh in container 

### ISSUE THREAD

**Issue by AMChalkie** [nf-core/ampliseq#105]
I've tried testing two of your workflows and get the following error in both:

nextflow run nf-core/rnaseq -r 1.4.2 -profile test,singularity
nextflow run nf-core/smrnaseq -r 1.0.0 -profile test,singularity

Error: No valid /bin/sh in container
Process `get_software_versions` terminated with an error exit status (255)

nextflow -version

      N E X T F L O W
      version 19.10.0 build 5170
      created 21-10-2019 15:07 UTC (22-10-2019 02:07 AEDT)
      cite doi:10.1038/nbt.3820
      http://nextflow.io

singularity -v
Increasing verbosity level (2)
Singularity version: 2.4.2-dist

Reads             : data/*{1,2}.fastq.gz
Data Type         : Single-End
Strandedness      : None
Trimming          : 5'R1: 0 / 5'R2: 0 / 3'R1: 0 / 3'R2: 0 / NextSeq Trim: 0
Aligner           : STAR
Fasta Ref         : https://github.com/nf-core/test-datasets/raw/rnaseq/reference/genome.fa
GTF Annotation    : https://github.com/nf-core/test-datasets/raw/rnaseq/reference/genes.gtf
GFF3 Annotation   : https://github.com/nf-core/test-datasets/raw/rnaseq/reference/genes.gff
Remove Ribosomal RNA: false
Biotype GTF field : gene_biotype
Save prefs        : Ref Genome: No / Trimmed FastQ: No / Alignment intermediates: No
Max Resources     : 6 GB memory, 2 cpus, 2d time per job
Container         : singularity - nfcore/rnaseq:1.4.2
Output dir        : ./results
Launch dir        : /mnts/bioinfo/RAW_DATA/2017_08_07_SRSF2_HsclCreYFP_Novogene_/FASTQ
Working dir       : /mnts/bioinfo/RAW_DATA/2017_08_07_SRSF2_HsclCreYFP_Novogene_/FASTQ/work
Script dir        : /home/AD.SVI.EDU.AU/achalk/.nextflow/assets/nf-core/rnaseq
User              : achalk
Config Profile    : test,singularity
Config Description: Minimal test dataset to check pipeline function
----------------------------------------------------
executor >  local (2)
[93/8cd581] process > get_software_versions [100%] 1 of 1, failed: 1 ✘
[-        ] process > makeBED12             -
[-        ] process > makeSTARindex         -
[-        ] process > fastqc                -
[-        ] process > trim_galore           -
[-        ] process > star                  -
[-        ] process > rseqc                 -
[-        ] process > preseq                -
[-        ] process > markDuplicates        -
[-        ] process > qualimap              -
[-        ] process > dupradar              -
[-        ] process > featureCounts         -
[-        ] process > merge_featureCounts   -
[-        ] process > stringtieFPKM         -
[-        ] process > sample_correlation    -
[-        ] process > multiqc               -
[42/779ab4] process > output_documentation  [100%] 1 of 1, failed: 1 ✘
[0;35m[nf-core/rnaseq] Pipeline completed with errors
WARN: To render the execution DAG in the required format it is required to install Graphviz -- See http://www.graphviz.org for more info.
Error executing process > 'get_software_versions'

Caused by:
  Process `get_software_versions` terminated with an error exit status (255)

Command executed:

  echo 1.4.2 &> v_ngi_rnaseq.txt
  echo 19.10.0 &> v_nextflow.txt
  fastqc --version &> v_fastqc.txt
  cutadapt --version &> v_cutadapt.txt
  trim_galore --version &> v_trim_galore.txt
  sortmerna --version &> v_sortmerna.txt
  STAR --version &> v_star.txt
  hisat2 --version &> v_hisat2.txt
  stringtie --version &> v_stringtie.txt
  preseq &> v_preseq.txt
  read_duplication.py --version &> v_rseqc.txt
  echo $(bamCoverage --version 2>&1) > v_deeptools.txt
  featureCounts -v &> v_featurecounts.txt
  salmon --version &> v_salmon.txt
  picard MarkDuplicates --version &> v_markduplicates.txt  || true
  samtools --version &> v_samtools.txt
  multiqc --version &> v_multiqc.txt
  Rscript -e "library(edgeR); write(x=as.character(packageVersion('edgeR')), file='v_edgeR.txt')"
  Rscript -e "library(dupRadar); write(x=as.character(packageVersion('dupRadar')), file='v_dupRadar.txt')"
  unset DISPLAY && qualimap rnaseq  > v_qualimap.txt 2>&1 || true
  scrape_software_versions.py &> software_versions_mqc.yaml

Command exit status:
  255

Command output:
  (empty)

Command error:
  ERROR  : No valid /bin/sh in container
  ABORT  : Retval = 255
  

nf-core/smrnaseq v1.0.0
----------------------------------------------------
Pipeline Release  : 1.0.0
Run Name          : voluminous_stallman
Reads             : data/*.fastq.gz
Genome            : false
Min Trimmed Length: 17
Trim 5' R1        : 0
Trim 3' R1        : 0
miRBase mature    : https://github.com/nf-core/test-datasets/raw/smrnaseq/reference/mature.fa
miRBase hairpin   : https://github.com/nf-core/test-datasets/raw/smrnaseq/reference/hairpin.fa
Save Reference    : Yes
Protocol          : illumina
miRTrace species  : hsa
3' adapter        : TGGAATTCTCGGGTGCCAAGG
Output dir        : ./results
Launch dir        : /mnts/bioinfo/RAW_DATA/2017_08_07_SRSF2_HsclCreYFP_Novogene_/FASTQ
Working dir       : /mnts/bioinfo/RAW_DATA/2017_08_07_SRSF2_HsclCreYFP_Novogene_/FASTQ/work
Current home      : /home/AD.SVI.EDU.AU/achalk
Current user      : achalk
Current path      : /mnts/bioinfo/RAW_DATA/2017_08_07_SRSF2_HsclCreYFP_Novogene_/FASTQ
Script dir        : /home/AD.SVI.EDU.AU/achalk/.nextflow/assets/nf-core/smrnaseq
Config Profile    : test,singularity
Max Resources     : 6 GB memory, 2 cpus, 2d time per job
Container         : singularity - nfcore/smrnaseq:1.0.0
User              : achalk
Config Description: Minimal test dataset to check pipeline function
[2m----------------------------------------------------
executor >  local (10)
[90/2bd0df] process > get_software_versions                                            [100%] 1 of 1, failed: 1 ✘
[5a/3659dd] process > make_bowtie_index                                                [100%] 1 of 1, failed: 1 ✘
[eb/3e74d8] process > fastqc (sample_2.fastq.gz)                                       [100%] 3 of 3, failed: 3 ✘
[2b/2758fa] process > trim_galore (sample_1.fastq.gz)                                  [100%] 3 of 3, failed: 3 ✘
[-        ] process > insertsize                                                       -
[-        ] process > collapse                                                         -
[-        ] process > bowtie_miRBase_mature                                            -
[-        ] process > bowtie_miRBase_hairpin                                           -
[-        ] process > bowtie_miRBase_hairpin_collapsed                                 -
[-        ] process > mirna_post_alignment                                             -
[-        ] process > edgeR_mirna                                                      -
[-        ] process > mirtop_bam_hairpin                                               -
[f6/381b60] process > mirtrace (sample_1.fastq.gz sample_2.fastq.gz sample_3.fastq.gz) [100%] 1 of 1, failed: 1 ✘
[-        ] process > multiqc                                                          -
[f4/c49228] process > output_documentation (1)                                         [100%] 1 of 1, failed: 1 ✘
Execution cancelled -- Finishing pending tasks before exit
[0;35m[nf-core/smrnaseq] Pipeline completed with errors
WARN: To render the execution DAG in the required format it is required to install Graphviz -- See http://www.graphviz.org for more info.
Error executing process > 'get_software_versions'

Caused by:
  Process `get_software_versions` terminated with an error exit status (255)

Command executed:

  echo 1.0.0 > v_pipeline.txt
  echo 19.10.0 > v_nextflow.txt
  echo $(R --version 2>&1) > v_R.txt
  fastqc --version > v_fastqc.txt
  trim_galore --version > v_trim_galore.txt
  bowtie --version > v_bowtie.txt
  samtools --version > v_samtools.txt
  htseq-count -h > v_htseq.txt
  fasta_formatter -h > v_fastx.txt
  mirtrace --version > v_mirtrace.txt
  multiqc --version > v_multiqc.txt
  scrape_software_versions.py > software_versions_mqc.yaml

Command exit status:
  255

Command output:
  (empty)

Command error:
  ERROR  : No valid /bin/sh in container
  ABORT  : Retval = 255
  

Work dir:
  /mnts/bioinfo/RAW_DATA/2017_08_07_SRSF2_HsclCreYFP_Novogene_/FASTQ/work/90/2bd0df455740dcc5ad559b94124df7

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

**Comment by d4straub** [comment]
Hi there,

as far as I can tell this appears to be a problem with the software container. The container should be in work/singularity/

I am a little surprised that you post that issue in nf-core/ampliseq and not in [nf-core/rnaseq](https://github.com/nf-core/rnaseq) or nf-core/smrnaseq. Even if this seems to be a general issue and not related to the pipeline I would recommend you to post an issue in the pipeline you have problems with instead of this one where you have not reported any problems.

I would recommend going to [nf-core/rnaseq](https://github.com/nf-core/rnaseq) with this issue.
