### ISSUE TITLE
User input manifest file?

### ISSUE THREAD

**Issue by erikrikarddaniel** [nf-core/ampliseq#110]
I can't find a way of specifying a manifest file for qiime import and the inbuilt procedure fails, probably because Scilife uses underscores in sample names. (Qiime has this problem when called without manifest file.)

/D

**Comment by erikrikarddaniel** [comment]
Clarification: With "specifying" I mean a command line option that lets me use my own, handwritten, manifest file.

**Comment by d4straub** [comment]
There is no option to start from a hand-written manifest file currently.
Reads are currently captured from folders (single sequencing run) or folders in a folder (multiple sequencing runs) and manifests are created automatically after cutadapt and before qiime data import.

Here:

https://github.com/nf-core/ampliseq/blob/57e1ee2f9028d0a8c5838ee8aa8cf4b383f61174/main.nf#L512-L537

**Comment by erikrikarddaniel** [comment]
OK. I saw that code. I think this would be a good feature, but it's something we could implement and contribute, so I'm closing this now.
