### ISSUE TITLE
Add parameter for user specified manifest file

### ISSUE THREAD

**Issue by erikrikarddaniel** [nf-core/ampliseq#111]
Besides handling the file, this needs to skip the automatic generation of a manifest file in the workflow.

**Comment by d4straub** [comment]
Hm why would it need to skip the automatic manifest?

currently: files in folder -> cutadapt -> auto manifest -> qiime
future: manual manifest -> cutadapt -> auto manifest -> qiime

and for PacBio data:
files in folder/manifest -> r dada2 -> sequences in fasta -> qiime

**Comment by erikrikarddaniel** [comment]
Would that handle sample names with underscores? By replacing them with sample names from the manifest file? What if the user specifies sample names with underscores?

**Comment by d4straub** [comment]
I think so, you would just need a manifest file that specifies sample name. E.g.
```
N_a_m_e1 <tab> N_a_m_e1_etc.fq.gz
N_a_m_e2 <tab> N_a_m_e2_etc.fq.gz
```

**Comment by erikrikarddaniel** [comment]
As long as the manifest file used when constructing the qiime artifact has e.g. "N_a_m_e1" specified it should be fine, and if you think that's what the wf would generate, fine. The way I interpreted the code was that it was splitting on underscore, but maybe that's just the default in the absence of manifest? I won't have time to look into this for a little while, but if you don't need this, wait and I'll try to do it.

**Comment by d4straub** [comment]
Yes, you are right it seems like the qiime artifact would have than only "N" as name, due to this line
`.map { name, forward, reverse -> [ name.toString().take(name.toString().indexOf("_")), forward, reverse ] } //extract sample name`
Sorry for causing confusion.

However, I still think an automatic manifest file should be produced to circumvent qiime2 input file name restrictions, but instead of the above function (and the line before) to extract the sample name, the sample name should be directly taken from the manual input manifest.

**Comment by erikrikarddaniel** [comment]
I'm happy with any solution that makes sample names with underscores work, and I must confess I'm a bit uncertain as to why cutadapt needs or could use a manifest file. Moreover, I'm not sure which would be easiest for me to implement myself...

**Comment by DiegoBrambilla** [comment]
> the sample name should be directly taken from the manual input manifest.

@d4straub , Is there a way (e.g. specific flag) in the current release of ampliseq to provide ampliseq with a manual input manifest?

**Comment by d4straub** [comment]
> @d4straub , Is there a way (e.g. specific flag) in the current release of ampliseq to provide a manual input manifest?

No.

**Comment by DiegoBrambilla** [comment]
> > @d4straub , Is there a way (e.g. specific flag) in the current release of ampliseq to provide a manual input manifest?
> 
> No.

If so, do you think that manually providing a manifest file as an option is the best solution to address this issue, or do you recommend other strategies? I would like to contribute on that.

**Comment by d4straub** [comment]
The probably only way to make sure that sample names can be as freely chosen as possible is by a manual manifest. You would just need to make sure that the name specified in the manifest is also forwarded to all processes.
I would maybe take existing code from another nf-core pipeline to read the manifest file, make a specified manifest take priority over the --reads parameter, make a manifest with test-files and just run the pipeline and see where the problems appear. One is already discussed a few posts earlier.

**Comment by d4straub** [comment]
So I think this is done, closing.
