### ISSUE TITLE
Expand default times for jobs

### ISSUE THREAD

**Issue by erikrikarddaniel** [nf-core/ampliseq#115]
I have trouble getting the training step through with just 6 hours, and haven't found a way to configure myself out of this yet. Can you expand this and maybe other steps too, to double the time? I'm tentatively setting this for 1.1.1 -- would be great if you could manage that.

**Comment by d4straub** [comment]
The training sets (test/test_multi) need only ~20 minutes each.
In my experience, all resource settings are fine right now, for test or real samples.

What processes and samples are you referring to?

**Comment by d4straub** [comment]
There is a known issue with 1.1.1 that needs to be resolved, but it raises an error, see #114

**Comment by erikrikarddaniel** [comment]
There's no problem with testing the pipeline, it's when I try to run it on real samples it times out because the SILVA training step takes more than 6 h on my cluster. I saw Alex' pointer to nf-core/config, but am a bit uncertain if that will help since I have been using the uppmax profile the whole time... (And I'm too detached to follow the slack conversation unfortunately.)

**Comment by apeltzer** [comment]
Any idea how long it might take so we can adjust this in 1.1.1?

**Comment by erikrikarddaniel** [comment]
I would double it to 12 h. At Uppmax, queue time for jobs is usually not affected by how long you ask for, so I always ask for the maximum 10 days. I can understand this might be different at other sites, so can understand if you want to be a bit conservative.

**Comment by d4straub** [comment]
Done in commit 9ba4a2f50c51ed249d4bc4d7ec5ef6ca0c198218: process make_SILVA_132_16S_classifier has now a default time of 12h instead of 6h.

**Comment by apeltzer** [comment]
Ok, we'll release 1.1.1 soon (after preprint is out, to have that in the README already).
