### ISSUE TITLE
Bonus tasks (later make individual issues out of this ticket...)

### ISSUE THREAD

**Issue by apeltzer** [nf-core/ampliseq#13]
* Bonus: multiple sequencing runs _(DOESNT WORK!)_
* Analysis of multiple sequencing runs:
    * input are multiple folders, one per sequencing run (`data` folder with multiple subfolders (a,b,c) each containing sequencing read files and a metadatafile with comlumn `new_name`)
    * `params.metadata` still required, contains merged metadata for all samples with `ID` column containing `new_name` values of all metadata files in subfolders
    * trimming on each folder
    * `qiime_import` on each trimming folder
    * `dada_multi` on each `qiime_import` folder
    * `mergeDADA` to combine all sequencing runs, than continue as usual.
* Dream: final report
  * make some sort of final report like extended multiqc report?
  * interesting output (all in `params.outdir` and multiqc/cutadapt report (`%pairs retained`) could get a link/representation in final report?
  * `.html` reports (e.g. from alpha_diversity, beta_diversity, beta_diversity_ordination, ancom) could get a link/representation in final report?

**Comment by d4straub** [comment]
Exept that the multiqc report doesnt contain all interesting data but only some quality control, all points above are integrated. A final report that contains or links all data remains ineresting but probably unreasonable.

Closed for now.
