### ISSUE TITLE
Input Manifest format validation

### ISSUE THREAD

**Issue by DiegoBrambilla** [nf-core/ampliseq#133]
Hi,
As of commit 7c589af , nf-core/dev can accept manifest files as input instead of read files. Such manifest has very strict requirements: must be tab-separated, have exactly the following 3 labels in the same ordes: sampleID, forwardReads, reverseReads. 

@drpatelh 's idea is to add a single process that checks the design file and (possibly) reformats it to suit the requirements of the pipeline.
Something like [this example](https://github.com/nf-core/atacseq/blob/fa1e3f8993cd20e249b9df09d29c5498eff311d2/main.nf#L308-L322).
By executing a [single script written in Python](https://github.com/nf-core/atacseq/blob/master/bin/check_design.py), the example simply avoids confusion in the manifest file format, for example with name variables, merging across lanes etc if you use both `--manifest`  and `--reads`.
The validation script decides what the names look like and avoids typo errors.

**Comment by d4straub** [comment]
The manifest file is validated in the draft version of #223

**Comment by DiegoBrambilla** [comment]
Awesome, good job!
