### ISSUE TITLE
Pipeline fails with remote working directory

### ISSUE THREAD

**Issue by PhilPalmer** [nf-core/ampliseq#136]
Hi,

I am trying to run the pipeline with a remote working directory (i.e. a directory on an AWS S3 bucket) but am having some issues, see [here](https://cloudos.lifebit.ai/public/jobs/5e55029005451c00f443c6d4).

Specifically, the pipeline fails during the `qiime_import` process because files in the `manifest.txt` file are from the (remote) working directory and so not staged in the working directory for the `qiime_import` process.

Any ideas how this can be resolved?

Many thanks in advance

### Launch instance
Create the following `cloud_ampliseq.cfg` file:
```
aws {
  accessKey = 'my_access_key'
  secretKey = 'my_secret_key'
  region = 'eu-west-1'
}
cloud {
  imageId = 'ami-001085c9389955bb6'
  instanceType = 'm1.xlarge'
  userName = 'ec2-user'
  keyName = 'phil-pem'
  bootStorageSize = '75 GB'
}
```

Then run:
```
nextflow -c cloud_ampliseq.cfg cloud create ampliseq  -c 1
```

### Install dependencies
SSH into the instance & install stuff:
```bash
# Install the goodies
sudo mv nextflow /usr/local/bin/
sudo yum install vim tmux python34-pip git htop wget java-1.8.0 -y && \
pip-3.4 install awscli --upgrade --user
git clone https://github.com/nf-core/ampliseq.git && cd ampliseq
```

### Run the pipeline
Run the pipeline using the testdata from the `test` profile and a remote working directory. (If the same command is run without a remote working directory it succeeds)
```bash
nextflow run main.nf --reads 's3://lifebit-featured-datasets/pipelines/ampliseq-data' --FW_primer GTGYCAGCMGCCGCGGTAA --RV_primer GGACTACNVGGGTWTCTAAT --classifier 'https://github.com/nf-core/test-datasets/raw/ampliseq/testdata/GTGYCAGCMGCCGCGGTAA-GGACTACNVGGGTWTCTAAT-gg_13_8-85-qiime2_2019.7-classifier.qza' --metadata 'https://github.com/nf-core/test-datasets/raw/ampliseq/testdata/Metadata.tsv' --max_memory 12.GB --max_cpus 4 -w s3://phil-workdir-jobs/ampliseq -resume -profile docker
```

### Error
However, I was getting the following error (see [nextflow.log](https://github.com/nf-core/ampliseq/files/4255316/nextflow.log)):

```
Caused by:
  Process `qiime_import (1)` terminated with an error exit status (1)

Command executed:

  qiime tools import --type 'SampleData[PairedEndSequencesWithQuality]' --input-path manifest.txt --output-path demux.qza --input-format PairedEndFastqManifestPhred33

Command exit status:
  1

Command output:
  (empty)

Command error:
  There was a problem importing manifest.txt:

    manifest.txt is not a(n) PairedEndFastqManifestPhred33 file:

    File referenced on line 2 could not be found (/phil-workdir-jobs/ampliseq/04/b60b4d40ebbcaaded0ff4c46418af5/trimmed/2a_S115_L001_R1_001.fastq.gz)
```

**Comment by d4straub** [comment]
Your solution is merged, thanks for that!

**Comment by PhilPalmer** [comment]
Okay great, thanks @d4straub
