### ISSUE TITLE
Allow separate paths for reference taxonomy database and reference FASTA sequences

### ISSUE THREAD

**Issue by DiegoBrambilla** [nf-core/ampliseq#141]
Hello, 
As explained in [issue#23](https://github.com/nf-core/ampliseq/issues/23), The current behaviour of ampliseq is to require a zip file that contains both the taxonomy database and the reference sequences (see [here](https://github.com/nf-core/ampliseq/blob/master/main.nf#L637-L640)).
A [config file](https://github.com/nf-core/ampliseq/blob/master/conf/ref_databases.config) specifies per each kind of database a parameter to call the compressed folder and another two for the FASTA and taxonomy reference file.
Also, the pipeline chooses the version number of the aforementioned references basing on `params.dereplication` .

This behaviour limits the chance to include more reference taxonomy databases that are not packed the same way ([GTDB](https://zenodo.org/record/2541239/), [UNITE](https://plutof.ut.ee/#/doi/10.15156/BIO/786343), ecc.).
It is also noteworthy that R-DADA2 requires separate reference files to work.

The code in `main.nf`should take into account the fact that the reference FASTA and taxonomy are not always compressed in the same archive. This should easen things up and allow for the implementation of those databases that comply to the QIIME2 format.

**Comment by d4straub** [comment]
I agree that the current way is very specialized and any changes towards a more generalized way and more flexibility with databases would be great.

However, SILVA is as far as I know the most common database in use for 16S and should require no extra effort to use. It would be highly desirable to make a very generic input in addition, such as sequence file and taxonomy or whatever is suitable.

NB: `params.dereplication` only allows to choose the dereplication threshold (e.g. 99, 97 and the like), not the version of SILVA, this is fixed at 132 at the moment. Also more flexibility regarding the silva version wouldn't be bad I think.

**Comment by d4straub** [comment]
Just came across https://github.com/bokulich-lab/RESCRIPt that seems to address this issue. Maybe it is of use.

**Comment by d4straub** [comment]
I guess this is postponed to 1.3?
