### ISSUE TITLE
File format for multipleSequencingRuns

### ISSUE THREAD

**Issue by MonicaSteffi** [nf-core/ampliseq#142]
Dear All,
I am trying nf-core amplicon pipeline for my analysis. I have reads from two different sequencing run. my input files looks like as follows:
data
  |-run1
  |  |-01_TM48_F.fastq.gz
  |  |-01_TM48_R.fastq.gz
     |-01_TM65_F.fastq.gz
     |-01_TM65_R.fastq.gz
  
  |-run2
     |-01_TM715_F.fastq.gz
     |-01_TM715_R.fastq.gz
     |-01_TM716_F.fastq.gz
     |-01_TM716_R.fastq.gz

> My metafile looks like:
> sample_id		I1	I2	Patient_ID
> run1-01_TM48	GACATAGT	CTACTATA	1
> run1-01_TM65	CTCGACTT	TACGAGAC	19
> run2-01_TM715	CGAAGTAT	TACGAGAC	19
> run2-01_TM716	TAGCAGCT	TACGAGAC	19

Is this format correct?. I am keep getting the error saying that few files have more than one forward reads

**Comment by d4straub** [comment]
Hi there!
Thanks for showing your folder structure and metafile. However, the command you run and the actual error message (or better complete command line output) are necessary to troubleshoot your problem.

I guess `run1` and `run2` are in a folder called e.g. `data` and you use `--reads 'data'`? Also, I hope its just a typo that in folder run2 is twice `|-01_TM716_F.fastq.gz`.

I suspect that the `01_` before your read files might make trouble. Also, depending on your command to start the pipeline, you might need to add `--reads "data" --extension "/*_{F,R}.fastq.gz"`.

Let me know how it goes.

**Comment by MonicaSteffi** [comment]
Hi @d4straub 

Thank you for the reply.  Yeah It is a typo in the run2 folder.  the folders run1 and run2 are in a folder called am and I executed the following command:
nextflow run nf-core/ampliseq -profile singularity --reads "/nfs/home/users/monica188/Final_data_set/am/" --extension "/*_{F,R}.fastq.gz" --FW_primer CCTACGGGNGGCWGCAG --RV_primer GACTACHVGGGTATCTAATCC --metadata "/nfs/home/users/monica188/Final_data_set/sample_meta_r1_r2.tsv" --multipleSequencingRuns --untilQ2import.
And the error log file as follows:

`ERROR ~ Error executing process > 'qiime_import_multi (run2-manifest.txt)'

Caused by:
  Process `qiime_import_multi (run2-manifest.txt)` terminated with an error exit status (1)

Command executed:

  qiime tools import n(duplicated_ids_forward)) 	--type 'SampleData[PairedEndSequencesWithQuality]' 				--input-path run2-manifest.txt an have only one forward read reco--output-path run2-demux.qza est, but the following sample ids w--input-format PairedEndFastqManifestPhred33

Command exit status:
  1

Command output:
  (empty)

Command error:
  Traceback (most recent call last):
    File "/opt/conda/envs/nf-core-ampliseq-1.1.2/lib/python3.6/site-packages/q2cli/builtin/tools.py", line 158, in import_data
      view_type=input_format)
    File "/opt/conda/envs/nf-core-ampliseq-1.1.2/lib/python3.6/site-packages/qiime2/sdk/result.py", line 241, in import_data
      validate_level='max')
    File "/opt/conda/envs/nf-core-ampliseq-1.1.2/lib/python3.6/site-packages/qiime2/sdk/result.py", line 267, in _from_view
      result = transformation(view, validate_level)
    File "/opt/conda/envs/nf-core-ampliseq-1.1.2/lib/python3.6/site-packages/qiime2/core/transform.py", line 70, in transformation
      new_view = transformer(view)
    File "/opt/conda/envs/nf-core-ampliseq-1.1.2/lib/python3.6/site-packages/q2_types/per_sample_sequences/_transformer.py", line 342, in _8
      single_end=False)
    File "/opt/conda/envs/nf-core-ampliseq-1.1.2/lib/python3.6/site-packages/q2_types/per_sample_sequences/_transformer.py", line 272, in _fastq_manifest_helper
      absolute=True)
    File "/opt/conda/envs/nf-core-ampliseq-1.1.2/lib/python3.6/site-packages/q2_types/per_sample_sequences/_transformer.py", line 162, in _parse_and_validate_manifest
      _validate_paired_end_fastq_manifest_directions(manifest)
    File "/opt/conda/envs/nf-core-ampliseq-1.1.2/lib/python3.6/site-packages/q2_types/per_sample_sequences/_transformer.py", line 223, in _validate_paired_end_fastq_manifest_directions
      '%s' % ', '.join(duplicated_ids_forward))
  ValueError: Each sample id can have only one forward read record in a paired-end read manifest, but the following sample ids were associated with more than one forward read record: run2-27, run2-16, run2-30, run2-35, run2-33, run2-14, run2-13, run2-26, run2-31, run2-22, run2-28, run2-20
  
  An unexpected error has occurred:
  
    Each sample id can have only one forward read record in a paired-end read manifest, but the following sample ids were associated with more than one forward read record: run2-27, run2-16, run2-30, run2-35, run2-33, run2-14, run2-13, run2-26, run2-31, run2-22, run2-28, run2-20
  
  See above for debug info.

Work dir:
  /nfs/home/users/monica188/Final_data_set/merged_analysis/work/11/8326b6329e9c818582efc167f94aef

Tip: when you have fixed the problem you can continue the execution appending to the nextflow command line the option `-resume`

 -- Check '.nextflow.log' file for details`

**Comment by d4straub** [comment]
Alright, the problematic part is:
`Each sample id can have only one forward read record in a paired-end read manifest, but the following sample ids were associated with more than one forward read record: run2-27, run2-16, run2-30, run2-35, run2-33, run2-14, run2-13, run2-26, run2-31, run2-22, run2-28, run2-20` meaning that these samples were most likely duplicates. For example the two samples `run2-20_X_{F,R}.fastq.gz` and `run2-20_Y_{F,R}.fastq.gz` are detected as one sample `run2-20`, because underscore (_) is treated as seperator. This obviously leads to multiple forward reads as reported by the pipeline. A solution would be (1) to rename your read files (or symlink), e.g. `run2-20-X_{F,R}.fastq.gz` and `run2-20-Y_{F,R}.fastq.gz` or (2) use the dev version with `--manifest`.

**Comment by MonicaSteffi** [comment]
@d4straub 
Thank you. Ill try renaming the file and let you know.
