### ISSUE TITLE
How to import Singleend reads: Cannot find any reads matching

### ISSUE THREAD

**Issue by MonicaSteffi** [nf-core/ampliseq#146]
Hi All,
I am trying nf-core for single end reads. 
I tried the following command: 

nextflow run nf-core/ampliseq -profile test,singularity --reads "/nfs/home/users/data" --extension "/*_R1.fastq.gz" --singleEnd

my fastq files are in the data folder as follows:
ERR1638423_R1.fastq.gz  
ERR1638425_R1.fastq.gz  
ERR1638427_R1.fastq.gz
ERR1638429_R1.fastq.gz 
ERR1638424_R1.fastq.gz 
ERR1638426_R1.fastq.gz  
ERR1638428_R1.fastq.gz

My log file is:

Config Profile    : test,singularity
Config Description: Minimal test dataset to check pipeline function
Apr-30 14:19:22.606 [main] INFO  nextflow.Nextflow - ------------------------------------------------------
Apr-30 14:19:22.607 [main] INFO  nextflow.Nextflow - 
######## WARNING: No DADA2 cutoffs were specified, therefore reads will be truncated where median quality drops below 25.
The chosen cutoffs do not account for required overlap for merging, therefore DADA2 might have poor merging efficiency or even fail.

Apr-30 14:19:22.659 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: null
Apr-30 14:19:22.659 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'local'
Apr-30 14:19:22.664 [main] DEBUG nextflow.executor.Executor - [warm up] executor > local
Apr-30 14:19:22.668 [main] DEBUG n.processor.LocalPollingMonitor - Creating local task monitor for executor 'local' > cpus=160; memory=1.5 TB; capacity=160; pollInterval=100ms; dumpInterval=5m
Apr-30 14:19:22.717 [main] DEBUG nextflow.processor.TaskProcessor - Creating operator > get_software_versions -- maxForks: 160; blocking: false
Apr-30 14:19:22.780 [main] DEBUG nextflow.script.ProcessConfig - Config settings `withName:fastqc` matches process fastqc
Apr-30 14:19:22.781 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: null
Apr-30 14:19:22.783 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'local'
Apr-30 14:19:22.782 [Actor Thread 5] ERROR nextflow.Nextflow - Cannot find any reads matching: /nfs/home/users/monica188/achauhan/data/*_{R1}.fastq.gz
NB: Path needs to be enclosed in quotes!
Apr-30 14:19:22.790 [main] DEBUG nextflow.processor.TaskProcessor - Creating operator > fastqc -- maxForks: 160; blocking: false

**Comment by d4straub** [comment]
Sorry, the pipeline accepts currently only paired-end Illumina reads that overlap. Single end analysis would need additional processes. I am not aware that anybody is working on that currently.
