### ISSUE TITLE
Split make_SILVA_132_16S_classifier into sequence extraction and training?

### ISSUE THREAD

**Issue by erikrikarddaniel** [nf-core/ampliseq#147]
Sequence extraction takes forever on the UPPMAX cluster (4-5 days), and uses little memory, whereas the training step requires more memory (20-25 GiB) and takes much shorter (< 3h). To make it possible to set better cpu and memory limits for this, I would therefore suggest that we split this process into two: The first would run the currently first four steps (unzipping, qiime imports and read extraction) and the second would just be the training step.

**Comment by d4straub** [comment]
Is this still the case (`1.1.2`/`dev`)? The whole `process make_SILVA_132_16S_classifier` takes <3h for me.

**Comment by erikrikarddaniel** [comment]
Den ons 28 okt. 2020 17:03Daniel Strau
<notifications@github.com> skrev:

> Is this still the case (1.1.2/dev)? The whole process
> make_SILVA_132_16S_classifier takes <3h for me.
>
I should think so, but I haven't tried since I've been running a ready made
classifier for a long time now.

In any case, I can't see that it would hurt to make two processes. Emelie
could do this.

/D

**Comment by d4straub** [comment]
Sure, I have no reservations against splitting the process.

**Comment by d4straub** [comment]
This was solved in the linked PR.
