### ISSUE TITLE
Zero sequence counts in trimming step

### ISSUE THREAD

**Issue by MonicaSteffi** [nf-core/ampliseq#149]
Dear All,
I have 121 samples from PRJEB25676 project.  I executed the following command. 
nextflow run nf-core/ampliseq -profile cluster -c nextflow.config --reads 'Data_PRJEB25676' --extension '/*_{1,2}.fastq.gz' --FW_primer GTGCCAGCMGCCGCGGTAA --RV_primer GGACTACHVGGGTWTCTAAT --untilQ2import --keepIntermediates --outdir na_results 

my Data_folder has following sequences:
ERR2437434_1.fastq.gz  
ERR2437434_2.fastq.gz  
ERR2437556_1.fastq.gz
ERR2437556_2.fastq.gz 

When i checked the per-sequence-fastq , all files have zero counts. but those files are not corrupted.
My trimming summary of a file for example:

```
This is cutadapt 2.6 with Python 3.6.7
Command line parameters: -g GTGCCAGCMGCCGCGGTAA -G GGACTACHVGGGTWTCTAAT --discard-untrimmed -o trimmed/ERR2437412_1.fastq.gz -p trimmed/ERR2437412_2.fastq.gz ERR2437412_1.fastq.gz ERR2437412_2.fastq.gz
Processing reads on 1 core in paired-end mode ...
Finished in 1.24 s (41 us/read; 1.46 M reads/minute).

=== Summary ===

Total read pairs processed:             30,281
  Read 1 with adapter:                      11 (0.0%)
  Read 2 with adapter:                       2 (0.0%)
Pairs written (passing filters):             0 (0.0%)

Total basepairs processed:    18,168,600 bp
  Read 1:     9,084,300 bp
  Read 2:     9,084,300 bp
Total written (filtered):              0 bp (0.0%)
  Read 1:             0 bp
  Read 2:             0 bp

=== First read: Adapter 1 ===

Sequence: GTGCCAGCMGCCGCGGTAA; Type: regular 5'; Length: 19; Trimmed: 11 times.

No. of allowed errors:
0-9 bp: 0; 10-19 bp: 1

Overview of removed sequences
length	count	expect	max.err	error counts
3	10	473.1	0	10
4	1	118.3	0	1


=== Second read: Adapter 2 ===

Sequence: GGACTACHVGGGTWTCTAAT; Type: regular 5'; Length: 20; Trimmed: 2 times.

No. of allowed errors:
0-9 bp: 0; 10-19 bp: 1; 20 bp: 2

Overview of removed sequences
length	count	expect	max.err	error counts
3	2	473.1	0	2
```

But when I tried with cutadapt with the same primer sequence, I get 99% of reads were retained after trimming. what could be the problem?

**Comment by d4straub** [comment]
The primer sequence is either incorrect or is already removed from those reads.

> But when I tried with cutadapt with the same primer sequence, I get 99% of reads were retained after trimming. what could be the problem?

The problem is most likely that in this case you did not use cutadapt's `--discard-untrimmed` parameter. Default is that cutadapt retains untrimmed reads as well.

Solution would be check that primer sequence is correct and if it is, run ampliseq with [--retain_untrimmed](https://github.com/nf-core/ampliseq/blob/master/docs/usage.md#--retain_untrimmed).
Just make sure to check DADA's chimera removal (might be unreasonable high when you do not remove primers) in [results/abundance-table/unfiltered/dada_stats.tsv](https://github.com/nf-core/ampliseq/blob/master/docs/output.md#dada2).

**Comment by MonicaSteffi** [comment]
Thank you. Ill run as you suggested and post the results

**Comment by MonicaSteffi** [comment]
Solution would be check that primer sequence is correct and if it is, run ampliseq with [--retain_untrimmed](https://github.com/nf-core/ampliseq/blob/master/docs/usage.md#--retain_untrimmed).

I tried with --retain_untrimmed and the read counts seems fine. Now I am doing dada2 step. But Is it advisable to run the pipeline with --retain_untrimmed parameter? 
.

**Comment by d4straub** [comment]
No, `--retain_untrimmed` is not advised, so its not default.
Usually, primer sequences are still in the raw read files and all reads that do not contain these primer are thought to be PCR artifacts, thats why they are removed by default. However, certain sequencing procedures (library prep & sequencing primers) or post-processing of reads (read trimming) leads to reads that do not contain primer sequences any more. Either one could be the case for you. And for these cases `--retain_untrimmed` was added to this pipeline.
