### ISSUE TITLE
Don't fetch taxonomy/create classifier when run with `--onlyDenoising`

### ISSUE THREAD

**Issue by erikrikarddaniel** [nf-core/ampliseq#152]
The large Silva file is fetched when the pipeline is run with `--onlyDenoising` which indicates that it would later build a classifier (I stopped it before it came that far). Waste of (a lot of) time.

**Comment by d4straub** [comment]
I'd classify this as bug. What version? 1.1.2?

**Comment by erikrikarddaniel** [comment]
If you say so... Specifying a `--classifier` fixes the problem, but that's of course a workaround.
I get it in my fork that I merged with master some weeks ago. I chose to remark here because I think it should affect all forks and versions, but I have not looked into any details yet.

**Comment by d4straub** [comment]
This should be solved in dev now, let me know if it isn't.
