### ISSUE TITLE
Sequences with multiple primers?

### ISSUE THREAD

**Issue by erikrikarddaniel** [nf-core/ampliseq#156]
Hi,

A user in Kalmar noticed that some ASV sequences he got from ampliseq had primers. When we looked into this it appears that there are sequences with repeated primers in the fastq files. To at least some extent these sequences seem to derive from the most abundant genomes in the data. We're therefore inclined to just remove them from the ASV table. It would of course be good if ampliseq could deal with this, but I'm a little unsure of the best approach since qiime's tool for dealing with primers is for removing primers, not sequences as a whole. It would still be best to be able to remove the ASVs in the qiime artifact, I suppose, so that all exported files are consistent. (Perhaps adding a flag to ampliseq to control this step.)

Have you observed this in your datasets? Can this be a bimera that doesn't get filtered out?

/D

**Comment by d4straub** [comment]
Hi,

I haven't observed such a problem yet. From your description, it appears to be a PCR artifact.

I think it would be a good idea to remove those sequences. Until now, ampliseq is only able to filter the ASV table for taxonomy/prevalence/rel.abundance but not sequences/specific ASVs.

I am unsure if the issue you are describing is a regular problem, I'd guess not. However, what you describe seems similar to contamination removal: specific sequences are removed from the ASV table based on a list of contaminant/unwanted sequences. I have to admit I did not look into that problem yet.

For the time being, the artifact sequences would need to be removed from the ASV table outside of ampliseq or, if they were classified in defined taxonomies, removed via `--exclude_taxa`.

**Comment by erikrikarddaniel** [comment]
Thanks for the reply @d4straub. I suppose one would have to output a file with ASVs that still contain primers after coming through the pipeline. To make the end result easy to use, I suppose adding output files that do not contain these ASVs would be good too. I'll make an issue out of this and close this one.
