### ISSUE TITLE
Can't find git repository config file -- Repository may be corrupted:

### ISSUE THREAD

**Issue by MonicaSteffi** [nf-core/ampliseq#160]
Dear All,
I installed nf-core/ampliseq pipeline a log ago and was able to run without any error. But I accediently delete some nextflow config file and now I am getting the following error. There was a similar issue posted in https://github.com/nextflow-io/nextflow/issues/1460#issue-550268394
```
nextflow run nf-core/ampliseq -profile test
N E X T F L O W  ~  version 20.01.0
Can't find git repository config file -- Repository may be corrupted
```

I tried to re-install as follows:
```

wget -qO- https://get.nextflow.io | bash

      N E X T F L O W
      version 20.07.1 build 5412
      created 24-07-2020 15:18 UTC (17:18 CEST)
      cite doi:10.1038/nbt.3820
      http://nextflow.io
Nextflow installation completed. Please note:
- the executable file `nextflow` has been created in the folder: /nfs/home/mm188
- you may complete the installation by moving it to a directory in your $PATH
```

I added nextflow to the path variable as follows.

`export PATH=$PATH:/nfs/home/users/mm188/nextflow`

And I tried again and got the same error. How do I rectify this? Kindly help me. 

nextflow run nf-core/ampliseq -profile test
N E X T F L O W  ~  version 20.01.0
Can't find git repository config file -- Repository may be corrupted:

**Comment by drpatelh** [comment]
`nextflow pull nf-core/ampliseq`

Hi @MonicaSteffi can you try running the [pull](https://www.nextflow.io/docs/latest/sharing.html#pulling-or-updating-a-project) command above to update the local version of the pipeline before you run it again. Another method is to manually delete your local cache of the pipeline using `rm -rf ~/.nextflow/assets/nf-core/ampliseq/`
