### ISSUE TITLE
error feature-classifier naive-bayes 

### ISSUE THREAD

**Issue by malfr1Ana** [nf-core/ampliseq#161]
Hi,

I tried to run the its2 classifier naive bayes for a small dataset but encountered an error.

The commands I used:
(qiime2-2020.6) afriana@alfriana-hp-laptop-14-cm0xxx:~/Documents/4$ qiime feature-classifier fit-classifier-naive-bayes \
>   --i-reference-reads unite.qza \
>   --i-reference-taxonomy unite-taxonomy.qza \
>   --o-classifier classifier.qza
Killed
(qiime2-2020.6) afriana@alfriana-hp-laptop-14-cm0xxx:~/Documents/4$

**Comment by erikrikarddaniel** [comment]
Looks like you ran out of memory; the classification can sometimes need more than 128 GiB RAM. Do you run on a cluster or on a local machine?

**Comment by d4straub** [comment]
No reply for 2 month, I close this.
