### ISSUE TITLE
Error executing process > 'make_SILVA_132_16S_classifier (1)'

### ISSUE THREAD

**Issue by Vikash84** [nf-core/ampliseq#162]
Error executing process > 'make_SILVA_132_16S_classifier (1)'

Caused by:
  /work/d6/ca95250dceaee9d1842bb565cdda05/SILVA_132_QIIME_release

**Comment by d4straub** [comment]
Hi there, this is unfortunately too less information to troubleshoot your problem. More of the terminal output is needed and also the command that you used to launch the pipeline is helpful.

**Comment by d4straub** [comment]
Occurred again in #169 , but here no reply, so I close it.
