### ISSUE TITLE
Importing fastq files

### ISSUE THREAD

**Issue by MonicaSteffi** [nf-core/ampliseq#165]
Dear All,
I am trying to import 2991 fastq files to nf-core/ampliseq environment. All the files are in fastq manifest format. I have attached my metadata for your reference. 

[https://drive.google.com/file/d/1hdgbCy6T6q8icKDRsgJCeBTYap1meIFN/view?usp=sharing](url)
Format of the file names is as Follows:

*_L001_R{1,2}_001.fastq.gz.

I used the Following command:

nextflow run -r  1.0.0 nf-core/ampliseq -profile docker --reads fastq_1/ --FW_primer CCTACGGGNGGCWGCAG --RV_primer GACTACHVGGGTATCTAATCC --metadata 30092020_modified.txt --keepIntermediates --trunclenf 280 --trunclenr 220 --classifier classifier_V3_V4.qza  --outdir results-CRC_modified

My file names: 
[https://drive.google.com/file/d/1OyvLP7YhYyOW-2oISyIls7eF5OZp0Rli/view?usp=sharing](url)

But I am getting the Following error.

Error executing process > 'qiime_import (1)'

Caused by:
  Process `qiime_import (1)` terminated with an error exit status (1)

Command executed:

  qiime tools import  eline Comp--type 'SampleData[PairedEndSequencesWithQuality]'              --input-path .                 --source-format CasavaOneEightSingleLanePerSampleDirFmt                  --output-path demux.qza

Error"

```
Command exit status:
  1

Command output:
  (empty)

Command error:
  There was a problem importing .:

    Missing one or more files for CasavaOneEightSingleLanePerSampleDirFmt: '.+_.+_L[0-9][0-9][0-9]_R[12]_001\\.fastq\\.gz'

Work dir:
  /media/nfcore/work/40/13b40d9ab4f58583f0419f8b7030b2

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line
```

I am not sure why qiime2 is automatically considered as Casava Format. Kindly help me here.

**Comment by d4straub** [comment]
First of all, these samples were not all multiplexed in one run, are they? I guess not. So please use [--multipleSequencingRuns](https://github.com/nf-core/ampliseq/blob/master/docs/usage.md#--multiplesequencingruns) with version 1.10 or 1.1.2 (this is not yet available in 1.0.0!).

The pipeline produces automatically manifest files for qiime2 import to allow a wide variety of input names, there seems a problem with these. These are saved in the work directory of the pipeline and if you changed there something, that might be a problem.

I first recommend to use version 1.1.0 or the current release 1.1.2 with `--multipleSequencingRuns` to appropriately use the methods.

**Comment by MonicaSteffi** [comment]
> First of all, these samples were not all multiplexed in one run, are they? I guess not. So please use [--multipleSequencingRuns](https://github.com/nf-core/ampliseq/blob/master/docs/usage.md#--multiplesequencingruns) with version 1.1.0 or 1.1.2 (this is not yet available in 1.0.0!).
> 
> The pipeline produces automatically manifest files for qiime2 import to allow a wide variety of input names, there seems a problem with these. These are saved in the work directory of the pipeline and if you changed there something, that might be a problem.
> 
> I first recommend to use version 1.1.0 or the current release 1.1.2 with `--multipleSequencingRuns` to appropriately use the methods.

Thank you so much. Issues were resolved.
One quick question. I got the another error at the classifier step. 
 `classifier_V3_V4.qza was created by 'QIIME 2019.10.0'. The currently installed framework cannot interpret archive version '5`

Which version of QIIME2 classifier will be supported by nfcore/ampliseq 1.1.0

**Comment by d4straub** [comment]
If you do not have a specific reason to supply a classifier yourself, just do not supply any. By default the pipeline will download SILVA v132 (https://www.arb-silva.de/fileadmin/silva_databases/qiime/Silva_132_release.zip), extract sequences based on your primers, and trains a classifier. All automatically.

ampliseq 1.1.0 uses QIIME2 v2018.6 and ampliseq 1.1.2 uses QIIME2 v2019.10

**Comment by MonicaSteffi** [comment]
> If you do not have a specific reason to supply a classifier yourself, just do not supply any. By default the pipeline will download SILVA v132 (https://www.arb-silva.de/fileadmin/silva_databases/qiime/Silva_132_release.zip), extract sequences based on your primers, and trains a classifier. All automatically.
> 
> ampliseq 1.1.0 uses QIIME2 v2018.6 and ampliseq 1.1.2 uses QIIME2 v2019.10

Thank you. We wanted to try with the latest Silva v138. But thank you for the info
