### ISSUE TITLE
Java version error

### ISSUE THREAD

**Issue by xkcococo** [nf-core/ampliseq#171]
I have an error with running ampliseq.

My sbatch file is
```
# load modules
ml singularity
ml nextflow
ml python
ml fastqc
ml multiqc
ml cutadapt
ml qiime

#Run Nextflow
nextflow run ampliseq 
--reads 'data'/ 
--FW_primer XXXX
--RV_primer XXXX
 --onlyDenoising\

date 
```

And the error message is:
```
Lmod is automatically replacing "python/3.7" with "multiqc/1.7".


Lmod is automatically replacing "multiqc/1.7" with "cutadapt/2.8".


Lmod is automatically replacing "cutadapt/2.8" with "python/2.7.6".

Creating a temporary QIIME directory 'tmp' in the current working directory.

The following have been reloaded with a version change:
  1) java/1.8.0_31 => java/1.7.0_79

[31mERROR: Cannot find Java or it's a wrong version -- please make sure that Java 8 or later is installed(B[m
[33mNOTE: Nextflow is trying to use the Java VM defined by the following environment variables:
 JAVA_CMD: /apps/java/jdk1.7.0_79/bin/java
 JAVA_HOME: /apps/java/jdk1.7.0_79
(B[m
Sun Oct 18 23:58:18 EDT 2020

```

It might be some errors about loading incompatible modules.
How could I solve this problem?

Thank you in advance!

**Comment by d4straub** [comment]
Honestly, I do not have the slighted idea what you are doing there. Is this an attempt to use the pipeline on a system without internet connection? Why do you avoid using the singularity/docker container? If you are trying to use the pipeline without its (maintained) software container, than I think you need to figure out software issues yourself. The error message seems quite straight forward to me.

**Comment by d4straub** [comment]
I close this here as this appears to me as no issue of the pipeline. Please feel free to join the [ampliseq slack channel](https://nfcore.slack.com/channels/ampliseq) for more general guidance how to use ampliseq. 
Main message here: do not use modules but let the pipeline handle its own software (docker/singularity/podman/conda required with `-profile`), do not submit the nexflow run command as a job for the scheduler but run it on the headnode and let it handle the scheduler (some sort of config file required that specifies the scheduler, see e.g. [here](https://nf-co.re/usage/configuration)).
