### ISSUE TITLE
Include cutadapt statistics in output

### ISSUE THREAD

**Issue by erikrikarddaniel** [nf-core/ampliseq#185]
The only statistics output today comes from the DADA2 steps in QIIME2, and doesn't include how many sequences passed through the primer removal by cutadapt. I think we should have one table containing all steps, preferably placed in a more natural directory than the current `results/abundance_table/unfiltered/dada_stats.tsv` -- how about `results/overall_stats.tsv`?

Cutadapt stats can be collected from the `cutadapt_log_*sample*.txt` files by grepping for "Total written". Sample names are in the file names.

A simple R script is one way to join a table from all the cutadapt logs with the `dada_stats.tsv`. Personally, I'd be willing to pay the price of depending on `dplyr` and write the R script using that (and possibly other `tidyverse` packages).

**Comment by d4straub** [comment]
Good idea!

nf-core pipelines usually collect statistics in multiQC, which is a little underused in this pipeline (only software versions, fastQC and cutadapt results are shown in the multiQC report).

So I'd recommend to (1) keep the folder structure as it is now but integrate these numbers into the multiQC report and/or (2) keep `results/abundance_table/unfiltered/dada_stats.tsv` where it is but additionally collect read numbers in a new file, such as `results/overall_stats.tsv` you proposed.
I somewhat guess that you prefer (2), but I think for many users (1) would be the better solution. I think its an improvement either way.

I think `results/overall_stats.tsv` would serve best when it collects all possible read numbers, i.e. number of reads of raw input, after cutadapt primer trimming, complete DADA2 stats, reads after feature table filtering (`results/abundance_table/filtered/count_table_filter_stats.tsv`).

**Comment by erikrikarddaniel** [comment]
I don't mind keeping the `results/abundance_table/unfiltered/dada_stats.tsv` but for me, like you guess, having the full stats only in the multiQC report is less than ideal. (In fact, I have no idea *how* to integrate that there.) So, just adding `results/overall_stats.tsv` without changing anything would be my choice and, as you say, why not include the outcome of filtering too -- is that easily accessible in a file to be fed into a script or does it need to be summarised first like the cutadapt stats?

**Comment by d4straub** [comment]
> why not include the outcome of filtering too -- is that easily accessible in a file to be fed into a script or does it need to be summarised first like the cutadapt stats?

Yes, that is summarized already in `results/abundance_table/filtered/count_table_filter_stats.tsv`, [here an example](https://nf-core-awsmegatests.s3-eu-west-1.amazonaws.com/ampliseq/results-70b23f4710094df9299e5ab2d18a1d412bbd4d04/abundance_table/filtered/count_table_filter_stats.tsv).

**Comment by d4straub** [comment]
This was solved.
