### ISSUE TITLE
Sample ids are in incorrect order in feature-table from PacBio data

### ISSUE THREAD

**Issue by jtangrot** [nf-core/ampliseq#187]
Found a bug in dada2_chimrem.r when running on a new dataset.

**Comment by d4straub** [comment]
When you are working on this and running into trouble with the automated tests, it might be due to #186 . If this happens, I'll fix the tests asap.

**Comment by jtangrot** [comment]
Indeed tests fail, on "Checking if Docker file of Conda environment changed". I would think that's related to that issue.

**Comment by d4straub** [comment]
Sorry, meetings, I'm going to do this today afternoon.

**Comment by d4straub** [comment]
@jtangrot I solved the github actions tests. But there is _again_ a template update incoming... however, this time no conflicts.

**Comment by d4straub** [comment]
This was solved in the linked PR.
