### ISSUE TITLE
How to only run fastqc/multiqc/demux separately?

### ISSUE THREAD

**Issue by xkcococo** [nf-core/ampliseq#192]
Greetings developers,

I have a question about pipeline.
If I only want to get the results of fastqc or multiqz or demux, how could I edit my command line?

For example, the script for test data is: `nextflow run nf-core/ampliseq -r 1.1.3 -profile test`
If I only want to get the results of fastqc or multiqz or demux, how could I edit this command line?

Thanks in advance.

Ke

**Comment by d4straub** [comment]
Hi there,
this is a very rare request, but adding [`--untilQ2import`](https://nf-co.re/ampliseq/1.1.3/parameters#untilq2import) should do the trick. Please let me know if this works for you.
Best

**Comment by xkcococo** [comment]
> Hi there,
> this is a very rare request, but adding [`--untilQ2import`](https://nf-co.re/ampliseq/1.1.3/parameters#untilq2import) should do the trick. Please let me know if this works for you.
> Best

Hi, Thanks for helping. But if I only added --untilQ2import, it will give me multiQC, fastQC, demux, and trimmed.
How could I do if I only want fastqc results?


Thanks.

**Comment by d4straub** [comment]
> How could I do if I only want fastqc results?

The pipeline isn't made for such a task. Please refer to the documentation about [skipping steps](https://nf-co.re/ampliseq/1.1.3/parameters#skipping-specific-steps) and [running the partial workflow](https://nf-co.re/ampliseq/1.1.3/parameters#run-only-partial-workflow). A combination of those parameter will come close to your request.

**Comment by d4straub** [comment]
I close the issue, don't hesitate to open another issue if you have other questions.
