### ISSUE TITLE
dada2 error with pacbio database 

### ISSUE THREAD

**Issue by mac012** [nf-core/ampliseq#196]
When I use pacbio database with `--pacbio`, there will be an error in `learnErrors()` of` dada2_errmodels_pacbio.r`:
`Done filtering, output in dada2_filtered
  The max qual score of 93 was not detected. Using standard error fitting.
  Error in err[c(1, 6, 11, 16), ] <- 1 : 
    incorrect number of subscripts on matrix
  Calls: learnErrors -> dada`
and in dada2_1.14.1, parameter of learnErrors():
`qualityType: (Optional). ‘character(1)’. The quality encoding of the
          fastq file(s). "Auto" (the default) means to attempt to
          auto-detect the encoding. **This may fail for PacBio files with
          uniformly high quality scores, in which case use
          "FastqQuality"**. This parameter is passed on to ‘readFastq’;
          see information there for details.`
Is there a way to solve this problem with changing this parameter or a simple update of dada2?

**Comment by d4straub** [comment]
Just guessing: possibly all you data was removed by filtering? Or did you not use fastq but fasta?
@jtangrot Probably you have a better idea what could have gone wrong?

**Comment by jtangrot** [comment]
Usually, the warning "The max qual score of 93 was not detected. Using standard error fitting" does not result in an error, so I suspect that something else than the quality encoding detection is wrong. It could be as @d4straub suggests, that all your data was removed in the filtering - I would start by checking that.

**Comment by mac012** [comment]
Thanks for your replies. I checkd my data ,is there a possibility that all of the base quality in fastq data are  "30"? Maybe you are right, my data was removed in the filtering.
![image](https://user-images.githubusercontent.com/47921791/101426353-c968b880-3937-11eb-913a-ed989d8749d6.png)
in fastq file: 
![image](https://user-images.githubusercontent.com/47921791/101427149-5102f700-3939-11eb-8bae-52b5b8e28072.png)

**Comment by d4straub** [comment]
This looks unusual. The quality values do not look real, at least some variation is expected.

**Comment by mac012** [comment]
> This looks unusual. The quality values do not look real, at least some variation is expected.

Yes, I think  the unusual base quality is the reason of this error. I just want to ask that in `dada2_1.14.1`, changing `qualityType` parameter of `learnErrors()`  could deal with `PacBio files with uniformly high quality scores` or not. If it could, I supposed that update the version of `dada2`.
Thanks.

**Comment by jtangrot** [comment]
Changing the qualityType parameter would make sure that also files where all quality values are above 58 are identified as having Phred-like base 33 encoding. However, I don't think that's the issue in your case.
Right now we are using dada2 version 1.10 as that's what's required in other parts of the pipeline.

**Comment by mac012** [comment]
> Changing the qualityType parameter would make sure that also files where all quality values are above 58 are identified as having Phred-like base 33 encoding. However, I don't think that's the issue in your case.
> Right now we are using dada2 version 1.10 as that's what's required in other parts of the pipeline.
Thank you! That answers my question perfectly.
