### ISSUE TITLE
Include option to rerun annotation on existing asv's

### ISSUE THREAD

**Issue by emnilsson** [nf-core/ampliseq#202]
There are cases when you want to update an asv-dataset with regards to taxonomic annotation, e.g. if you want to compare different reference databases or if the reference database has been updated and you want to use the update. Having this as an option when running ampliseq, potentially by including fasta-files with the asv's sequences in a qiime artefact, would be a nice enhancement.

**Comment by d4straub** [comment]
If you do have the working directory (i.e. comapring different databases), then using the pipeline twice with `-resume` and different output directory will do what you want, e.g.
- standard test (with the small pre-trained SILVA 132 classifier):
`nextflow run nf-core/ampliseq -r 1.1.2 -profile test,singularity --skip_ancom --outdir test`
- standard test with producing and using the full standard (SILVA 132) classifier:
`nextflow run nf-core/ampliseq -r 1.1.2 -profile test,singularity --skip_ancom --classifier false --outdir test_taxref -resume`

If you do not have the working directory available any more, running the pipeline again (same version, same command) but with different database will lead to the exactly same ASV table but new taxonomy classifications.

I am not so sure we really need additional functionality.

**Comment by erikrikarddaniel** [comment]
We will regularly reannotate a Swedish library of ASV sequences. One option is of course to make something special for this purpose, but adding a flag to ampliseq that makes it possible to just take a fasta file with sequences would be helpful as that means we don't have to duplicate the code for dealing with different databases that @emnilsson is working on now.

**Comment by d4straub** [comment]
Ah, regularly, than of course you do not want to regularly process the data again, I see. Sure, another starting point.

So just like set a parameter, e.g. `--ASV_sequences "seq.fasta"`, add a process to read it in qiime2, feed it into `ch_qiime_repseq_raw_for_classifier` while keeping channels `ch_read_pairs; ch_read_pairs_fastqc` empty. Should work fine.

**Comment by erikrikarddaniel** [comment]
Exactly.

**Comment by d4straub** [comment]
> As for #202, I'd prefer if no particular file extension was required. Personally, I always use `.fna` for nucleotide fasta, others use `.fa` and we might see gzipped files too. Although I understand if the latter is not currently supported, it's probably easy to do.

Currently, the `--input` parameter can take:
- fasta file, ending with `fasta`
- sample sheet / manifest, ending with `tsv`
- folder input, if not any of the files before

If you have a set of file endings that should be recognized as fasta, thats no problem, as long as these are unique to others. If any file ending is supposed to be supported, using `--input` won't work. But I prefer that strongly, because it keeps parameters at a minimum and centralizes input parsing.

**Comment by erikrikarddaniel** [comment]
Good point, @d4straub. Add `.fna` and `.fa`. At a later point, maybe also the gzipped versions.
