### ISSUE TITLE
Add defaults for max_cpus, max_memory and max_time

### ISSUE THREAD

**Issue by erikrikarddaniel** [nf-core/ampliseq#204]
If one runs e.g. `-profile docker` one gets warnings about no defaults for the max_cpus, max_memory and max_time. This is quite ugly, so they should have defaults. Best in `nextflow.config`.

**Comment by d4straub** [comment]
max_cpus, max_memory and max_time are specific for the hardware infrastructure. These values are supposed to be given via --profile cfc/uppmax/whatever or by specifying --max_cpus etc.
I think the warnings are warranted here actually.

**Comment by erikrikarddaniel** [comment]
I think we should have conservative defaults instead (possibly together with an information message and/or more information in the README). Currently, it looks like the workflow is about to fail because one gets a lot of warnings. Values for these settings are listed as "Max Resources" when the workflow starts.

**Comment by d4straub** [comment]
I was wrong, these defaults are supposed to be in nextflow.config, as you said. I added them in #207

**Comment by d4straub** [comment]
Done.
