### ISSUE TITLE
The help message is formated badly and contains errors

### ISSUE THREAD

**Issue by erikrikarddaniel** [nf-core/ampliseq#205]
Indentation: Sometimes tabs have been used, sometimes spaces (maybe a vim thing). I think it would be best with an indentation of two spaces.

`--manifest`: It says "table" where it should say "tab" and the rest should be checked to be grammatically correct.

I think there may be other mistakes, so a read through could be worthwhile.

**Comment by apeltzer** [comment]
Once the pipeline fully supports the JSON Schema, this can be automatically generated and is then always consistent :-)

**Comment by d4straub** [comment]
Yes, the `nextflow_schema.json` is the future and representation: https://nf-co.re/ampliseq/dev/parameters
Still, any improvement to the help message in either `main.nf` or `nextflow_schema.json` would be good I think.

**Comment by d4straub** [comment]
I have improved the formatting in #212. Haven't corrected any text though.

**Comment by d4straub** [comment]
The help message in main.nf will be not used any more in #223  but only the schema.
