### ISSUE TITLE
Add data to test_full.config

### ISSUE THREAD

**Issue by d4straub** [nf-core/ampliseq#215]
`test_full.config` is supposed to present the pipeline in [AWS results](https://nf-co.re/ampliseq/results#ampliseq/results-70b23f4710094df9299e5ab2d18a1d412bbd4d04/) but currently only processes very simple test data (`test.config`). Instead, data from the [nf-core/ampliseq paper](https://www.frontiersin.org/articles/10.3389/fmicb.2020.550420/full) should be used, [PRJNA563986](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA563986), probably only a subset.

**Comment by erikrikarddaniel** [comment]
As I understand it, the task is to add a new config that points to full scale data someplace.

We are uploading data to real data to ENA and could provide that for a full scale test. (Now I see that you propose data from the publication, even better.) 

We should also test building a taxonomy classifier, which we could do with @emnilsson 's new database code (using GTDB species representative rRNAs). I'm adding @emnilsson as we talked about this yesterday.
