### ISSUE TITLE
Keep certain key .qza files

### ISSUE THREAD

**Issue by d4straub** [nf-core/ampliseq#22]
always publish the following files in the result folder:
table.qza
rep-seqs.qza
taxonomy.qza
rooted-tree.qza

**Comment by apeltzer** [comment]
Should they be in separate directories or something like that?

**Comment by d4straub** [comment]
They can all go in the results dir in a sub-directory, probably named like "key_qiime2_files"

**Comment by d4straub** [comment]
solved at least for:
table.qza
rep-seqs.qza
taxonomy.qza

**Comment by apeltzer** [comment]
Anything else we need to have? CI Tests are running fully now!
