### ISSUE TITLE
DADA2 version not reported in `software_versions.csv`

### ISSUE THREAD

**Issue by erikrikarddaniel** [nf-core/ampliseq#222]
The version of QIIME2 implies a version of DADA2 but in many cases people will want to write the version of DADA2 in their M&M sections, so I think it would be good if we could report that. I'm not sure how this is best done though as one probably has to call R, or is there a way of reporting this from QIIME2?

**Comment by d4straub** [comment]
Absolutely true, this is helpful. This will be also addressed in #223. Basically, call it in R and export version.
