### ISSUE TITLE
Transition to nextflow DSL2

### ISSUE THREAD

**Issue by d4straub** [nf-core/ampliseq#223]
### Motivation
Nextflow DSL2 is around since a while and currently ampliseq and most nf-core pipelines are written in DSL1. However, nf-core/rnaseq is already released (and several have development branches) in DSL2 and there are DSL2 nf-core templates and best practices outlined already. I am working on re-writing the pipeline in DSL2 and would like to share my progress and have a discussion platform.

### Planned changes

- DSL2 moves from one large software container (as done in DSL1) to several small ones and is organized in (software) modules, this requires large structural changes.
- The pipeline is historically grown and looks partially like a patchwork, I'd like to streamline it and reduce its code complexity without reducing functionality.
- `--input` should take a .tsv file or folder and allow for all analysis for both, file and folder input.
- QIIME2 narrows down ASV generation too much by limiting DADA2 parameter access, so I'd like to use DADA2 directly (similar as with PacBio data in v1.2.0). QIIME2 downstream analysis is great imho, so I'd like to keep that (but only after ASV generation).

### Progress on milestones

- [x] minimal working pipeline, raw reads to ASVs
- [x] design allows for all envisaged data analysis (SE/PE/Illumina/PacBio) 
- [x] manifest input covers all input types (SE/PE/multipleSequencingRuns)
- [x] folder input covers all input types (SE/PE/multipleSequencingRuns)
- [x] sensible DADA2 option for all data types (SE/PE/Illumina/PacBio)
- [x] selected informative files are published in results folder
- [x] provisionally updated documentation
- [x] restore `--double_primer` & automatic choosing of trunclenf & trunclenr (`--trunc_qmin` & `--trunc_rmin`)
- [x] automatic CI tests use manifest input instead of readPaths (unnessessary complication, because never used outside of tests)
- [x] QIIME2 downstream analysis
- [x] updated docs
- [x] tests all pass

I am happy about comments or suggestions.

**Comment by d4straub** [comment]
Ok, first draft code is out: https://github.com/d4straub/ampliseq/tree/DSL2
Should work with 
```
export NXF_VER=21.02.0-edge
nextflow run d4straub/ampliseq -r DSL2 -profile test_manifest,singularity --outdir results_test_manifest
```
All other tests are not running yet, because they either rely on `readPaths` (now deprecated) or do not follow current sample sheet (=manifest) parsing rules.

**Comment by d4straub** [comment]
I believe all functions of 1.2.0 until ASV generation are restored in DSL2, I've added DADA2 assignTaxonomy as well.
Next step is to organize CI tests.

**Comment by d4straub** [comment]
Tests are all running without error, but haven't verified whether the results are comparable to 1.2.0, yet. Also added a full test config #215 .

**Comment by d4straub** [comment]
All functions are restored, linting is fine.
While reducing linting warnings, #221 was solved.
Also #202 is working, the fasta files is supplied with --input and requires a 'fasta' as file ending, up for discussion.

There are a few issues though, e.g. 
- -resume doesnt work properly when changing parameters. Running the pipeline once with standard setting and then using different setting with -resume will load from cache with ignoring the new parameter. This is because many parameters are given via 'addParams' and those bypass nextflows hash checks. These have to go into channels instead to trigger new calculations.
- processes/modules need to be reorganized into individual files and folders
- some modules do not have the perfect settings for all possibilities, e.g. cutadapt for --illumina_its

**Comment by erikrikarddaniel** [comment]
Great progress!

As for #202, I'd prefer if no particular file extension was required. Personally, I always use `.fna` for nucleotide fasta, others use `.fa` and we might see gzipped files too. Although I understand if the latter is not currently supported, it's probably easy to do.

**Comment by d4straub** [comment]
This is now merged to dev, so it can be seen as solved.
