### ISSUE TITLE
DADA2 assignTaxonomy

### ISSUE THREAD

**Issue by erikrikarddaniel** [nf-core/ampliseq#231]
What I found out about DADA2's `assignTaxonomy` and `assignSpecies` so far:

1. Documentation here: https://benjjneb.github.io/dada2/training.html
1. The functions take just a fasta file with a hierarchy in the header, i.e. no training required
2. The provided GTDB file is r86, so outdated. We should allow download and make a script that converts the GTDB files into one fasta file for both Archaea and Bacteria. This script is probably similar to the one for QIIME2 except it should output just a single fasta file
3. Eukaryotes: Silva 132 and 128, Unite and PR2 present
4. If we want to support cutting out the right part of the sequence, it should be as easy as calling `cutadapt` on the already formatted fasta file with the primers and outputting a new fasta file.

Example fasta file for `assignTaxonomy` and, I think, `assignSpecies` (sequences cut):

```
>Archaea;Crenarchaeota;Korarchaeia;Korarchaeales;Korarchaeaceae;Korarchaeum;Korarchaeum_cryptofilum(RS_GCF_000019605.1)
GGTTGATCCTGCCGGAGGGAACCCCTATCGGGCTCGCACTAAGCCATGCGAGTCTGCTGGGGGCCCCTGCCCCTGGCGGCG
>Archaea;Crenarchaeota;Thermoprotei;Desulfurococcales;Desulfurococcaceae;Staphylothermus;Staphylothermus_hellenicus(RS_GCF_000092465.1)
AGGTGATCCAGCCGCAGGTTCCCCTACGGCTACCTTGTTACGACTTCTCCCCCCTTGGGAGGGGGGAGTTCGACCTGGCCCC
>Archaea;Halobacterota;Methanosarcinia;Methanosarcinales;Methanosarcinaceae;Methanosarcina;Methanosarcina_mazei(RS_GCF_000970205.1)
GAGGTGATCCAGCCGCAGATTCCCCTACGGCTACCTTGTTACGACTTAACCCCCCTTGCAAAGCACAGGTTCGAACACGGCAC
>Archaea;Euryarchaeota;Methanobacteria;Methanobacteriales;Methanobacteriaceae;Methanobacterium;Methanobacterium_formicicum_A(RS_GCF_000302455.1)
CCGTTTGATCCTGGCGGAGGCCACTGCTATTGGGTTTCGATTAAGCCATGCAAGTCGTACGATCCTTTCGGGGTCGTGGCATAC
>Archaea;Crenarchaeota;Thermoprotei;Thermofilales;Thermofilaceae;Thermofilum_A;Thermofilum_A_uzonense(RS_GCF_000993805.1)
TCCGGTTGATCCTGCCGGACCCGACTGCTATCAGGGTGGGGCTAACCCATGGAAGTCTAGGAGCCGGGGCTACGGCCGGCTCA
```

Note that in the above example, taken from a user provided GTDB file, blanks in names are replaced with '_' and the GTDB genome ID is appended in parenthesis. I suspect that only names down to genus will actually be assigned.

**Comment by d4straub** [comment]
Great, that sounds actually even easier than expected (no training required)!

`assignSpecies` is expecting `>ID Genus species`, probably same for `addSpecies`
Currently the pipeline is using `assignTaxonomy` and `addSpecies`, but not `assignSpecies`. That might be another point to add.

**Comment by erikrikarddaniel** [comment]
It's a bit strange that there's an ID required for `addSpecies` and `assignSpecies` but not for `assignTaxonomy`, particularly since the latter (probably) accepts names down to species level. This is, anyway, the way the user provided GTDB files look.

I think we should settle with just the representative genomes. Partly because it's less data, but also because one might bias the kmer distribution by having certain species represented by a very large number of sequences. This is how me and @emnilsson originally thought.
