### ISSUE TITLE
md5 sums as keys for sequences

### ISSUE THREAD

**Issue by erikrikarddaniel** [nf-core/ampliseq#244]
I think the md5 sums generated as keys for sequences by QIIME2 was good, and I think we should have that for the DADA2 prepared data as well. I should also add that in the biodiversity project that funds us, we have come to rely on these.

**Comment by d4straub** [comment]
Yes I also prefer md5sums to the arbitrary `ASV_<number>` naming schema that we use now in the DSL2 version.

**Comment by d4straub** [comment]
This was solved in #250 , great!
