### ISSUE TITLE
Should update the parameter into ${task.cpus}

### ISSUE THREAD

**Issue by likelet** [nf-core/ampliseq#248]
https://github.com/nf-core/ampliseq/blob/1e76f1c0c6d270572573a6ad76aa40bfc185c3da/main.nf#L1187
seems an error here, which should be 
```
  --p-n-threads ${task.cpus}
```

and another line :
https://github.com/nf-core/ampliseq/blob/1e76f1c0c6d270572573a6ad76aa40bfc185c3da/main.nf#L1044

**Comment by d4straub** [comment]
Yes, you are right! Thanks for reporting!
