### ISSUE TITLE
Fix the Uppmax profile

### ISSUE THREAD

**Issue by erikrikarddaniel** [nf-core/ampliseq#262]
The Uppmax profile in `nf-core/profiles` contains a number of params that are not used any more in the DSL2 version of `ampliseq`, remove them when releasing 2.0:

`igenomes_base`, `save_reference`, `modules`, `classifier_extract_seq`, `classifier_train` and `classifier`. Warnings are different for the first three and last, so take care. If the first three are generic and can't be deleted, maybe follow this adivice:

```Ignore this warning: params.schema_ignore_params = "igenomes_base,save_reference,modules"```

**Comment by d4straub** [comment]
Have you removed those parameters?

**Comment by erikrikarddaniel** [comment]
Den tors 29 juli 2021 kl 13:41 skrev Daniel Straub ***@***.***>:
>
> Have you removed those parameters?
>
Not yet, I'll try to get it done soon.

**Comment by erikrikarddaniel** [comment]
Let's close this, I'm unsure if it's still a problem.
