### ISSUE TITLE
The DADA2 taxonomy tables don't have confidence

### ISSUE THREAD

**Issue by erikrikarddaniel** [nf-core/ampliseq#264]
Some value for the assignment confidence should be available, but it's not output now neither in `ASV_tax.tsv` nor in `ASV_tax_species.tsv`. This is probably because we've set `outputBootstraps = FALSE` in the call to `assignTaxonomy()`.

**Comment by d4straub** [comment]
Seems like a dublicate of https://github.com/nf-core/ampliseq/issues/243?

**Comment by erikrikarddaniel** [comment]
> Seems like a dublicate of #243?

Correct. I'll close this and put #243 in this milestone.
