### ISSUE TITLE
The PR2 reformatting script is not present

### ISSUE THREAD

**Issue by erikrikarddaniel** [nf-core/ampliseq#265]
## Description of the bug

In the dev version, the `taxref_reformat_pr2.sh` is not present in the `bin` directory, so one can't run with `--dada_ref_taxonomy pr2`.

**Comment by d4straub** [comment]
@emnilsson would you be able to correct this?

**Comment by d4straub** [comment]
This was done in https://github.com/nf-core/ampliseq/pull/281
