### ISSUE TITLE
Unexpected error [NullPointerException]

### ISSUE THREAD

**Issue by ld9866** [nf-core/ampliseq#266]
hello! l have meet some problems
when l print nextflow run nf-core/ampliseq -profile test or nextflow run nf-core/ampliseq
then it showed that:
N E X T F L O W  ~  version 20.04.1
Pulling nf-core/ampliseq ...
Unexpected error [NullPointerException]
l have successfully install it through conda,so l would like to ask how l can solve it?

**Comment by erikrikarddaniel** [comment]
What did you install through Conda, Nextflow? Please install Nextflow following the instructions here: https://www.nextflow.io/ (scroll down to "Getting started". 

When you've installed Nextflow that way, try:

`nextflow run nf-core/ampliseq --help`

If that succeeds, follow the instructions here: https://github.com/nf-core/ampliseq/blob/master/README.md

**Comment by d4straub** [comment]
This doesnt seem to be a bug at that point. @ld9866 feel free to ask for more advice or give feedback if you succeeded.

**Comment by ld9866** [comment]
> nextflow run nf-core/ampliseq --help

I'm glad to hear from you.  
when l print   nextflow run nf-core/ampliseq --help,then it showed that 
N E X T F L O W  ~  version 20.04.1
Pulling nf-core/ampliseq ...
Unexpected error [NullPointerException]
l do not know how to solve it 
thank you!

**Comment by ld9866** [comment]
l install through Conda, and it showed that l have succeed.

**Comment by ld9866** [comment]
when l print nextflow,then the software showed it ok.
Usage: nextflow [options] COMMAND [arg...]
Options:
  -C
     Use the specified configuration file(s) overriding any defaults
  -D
     Set JVM properties
  -bg
     Execute nextflow in background
  -c, -config
     Add the specified file to configuration set
  -d, -dockerize
     Launch nextflow via Docker (experimental)
  -h
     Print this help
  -log
     Set nextflow log file path
  -q, -quiet
     Do not print information messages
  -syslog
     Send logs to syslog server (eg. localhost:514)
  -v, -version
     Print the program version

**Comment by erikrikarddaniel** [comment]
Try to install Nextflow following the instructions here: https://www.nextflow.io/, and try the `hello` workflow.

**Comment by ld9866** [comment]
hello
l have follow it and try to install form conda or&nbsp;https://www.nextflow.io/&nbsp;,when l try to test it showed that ,do l success or not?
thank you!
li dong







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nf-core/ampliseq"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月6日(星期四) 中午1:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [nf-core/ampliseq] Unexpected error [NullPointerException] (#266)





 
Try to install Nextflow following the instructions here: https://www.nextflow.io/, and try the hello workflow.

**Comment by d4straub** [comment]
Nextflow is not supposed to be installed from conda and that is made clear. https://www.nextflow.io/ under the headline `Getting started` shows three steps. Please follow those 3 steps, otherwise we cannot help.

**Comment by ld9866** [comment]
I think you may have misunderstood my meaning.
I mean I used both Conda and manual installation, neither of which solved the problem.



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nf-core/ampliseq"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月6日(星期四) 下午3:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [nf-core/ampliseq] Unexpected error [NullPointerException] (#266)





 
Nextflow is not supposed to be installed from conda and that is made clear. https://www.nextflow.io/ under the headline Getting started shows three steps. Please follow those 3 steps, otherwise we cannot help.

**Comment by d4straub** [comment]
Alright, could you copy paste the following into your terminal and than copy paste the output (incl. commands you used). It would be important to see all commands and all output in the terminal:
```
java -version 
curl -s https://get.nextflow.io | bash
./nextflow run hello
./nextflow pull nf-core/ampliseq -r 1.2.0
./nextflow run nf-core/ampliseq -r 1.2.0 --help
```

**Comment by ld9866** [comment]
The picture shows the problem I am facing now, and I personally feel very confused.
The second picture is a state I have been in, and the results have not been shown yet.







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nf-core/ampliseq"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月6日(星期四) 下午3:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [nf-core/ampliseq] Unexpected error [NullPointerException] (#266)





 
Alright, could you copy paste the following into your terminal and than copy paste the output (incl. commands you used). It would be important to see all commands and all output in the terminal:
 java -version  curl -s https://get.nextflow.io | bash ./nextflow run hello ./nextflow pull nf-core/ampliseq -r 1.2.0 ./nextflow run nf-core/ampliseq -r 1.2.0 --help

**Comment by d4straub** [comment]
What picture? As I said, could you please copy-paste the terminal commands and output here into the github issue?

**Comment by ld9866** [comment]
I have re-uploaded these two pictures in the attachment. Can you see them now?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nf-core/ampliseq"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月6日(星期四) 下午4:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [nf-core/ampliseq] Unexpected error [NullPointerException] (#266)





 
What picture? As I said, could you please copy-paste the terminal commands and output here into the github issue?

**Comment by d4straub** [comment]
No, I cannot see any pictures. One last time, please copy paste commands & output.

**Comment by ld9866** [comment]
java -version
openjdk version "11.0.1-internal" 2018-10-16
OpenJDK Runtime Environment (build 11.0.1-internal+0-adhoc..src)
OpenJDK 64-Bit Server VM (build 11.0.1-internal+0-adhoc..src, mixed mode)



curl -s https://get.nextflow.io | bash
&nbsp; &nbsp; &nbsp; N E X T F L O W
&nbsp; &nbsp; &nbsp; version 21.04.0 build 5552
&nbsp; &nbsp; &nbsp; created 02-05-2021 16:22 UTC (03-05-2021 00:22 CDT)
&nbsp; &nbsp; &nbsp; cite doi:10.1038/nbt.3820
&nbsp; &nbsp; &nbsp; http://nextflow.io

Nextflow installation completed. Please note:
- the executable file `nextflow` has been created in the folder: /home/lidong
- you may complete the installation by moving it to a directory in your $PATH



./nextflow run hello
N E X T F L O W&nbsp; ~&nbsp; version 21.04.0
Pulling nextflow-io/hello ...
Unexpected error [NullPointerException]



./nextflow pull nf-core/ampliseq -r 1.2.0
Checking nf-core/ampliseq ...
(it still running and show nothing)










------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nf-core/ampliseq"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月6日(星期四) 下午4:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [nf-core/ampliseq] Unexpected error [NullPointerException] (#266)





 
No, I cannot see any pictures. One last time, please copy paste commands &amp; output.

**Comment by apeltzer** [comment]
```
./nextflow run hello
N E X T F L O W&nbsp; ~&nbsp; version 21.04.0
Pulling nextflow-io/hello ...
Unexpected error [NullPointerException]
```

That is an extremely odd case. Can you try a different Java version maybe? Is there a logfile `.nextflow.log` for the "hello" run?

**Comment by ld9866** [comment]
ok l will try it later.
thank you



---Original---
From: "Alexander ***@***.***&gt;
Date: Thu, May 6, 2021 17:23 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [nf-core/ampliseq] Unexpected error [NullPointerException] (#266)




 ./nextflow run hello N E X T F L O W&amp;nbsp; ~&amp;nbsp; version 21.04.0 Pulling nextflow-io/hello ... Unexpected error [NullPointerException]  
That is an extremely odd case. Can you try a different Java version maybe? Is there a logfile .nextflow.log for the "hello" run?

**Comment by ld9866** [comment]
Thank you very much. I changed the version of Java and it worked. @apeltzer

**Comment by ld9866** [comment]
I want to ask a new question when the input is :
./nextflow pull nf-core/ampliseq -r 1.2.0
it showed that:
Checking nf-core/ampliseq ...
https://github.com/nf-core/ampliseq.git: cannot open git-upload-pack

**Comment by erikrikarddaniel** [comment]
Try without the `-r 1.2.0`. That's the stable release anyway, so should download the same.

**Comment by ld9866** [comment]
./nextflow pull nf-core/ampliseq
Checking nf-core/ampliseq ...
Unexpected error [NullPointerException]
l don't know how to solve it.

**Comment by erikrikarddaniel** [comment]
Seems like you're back to your old version of Java...

**Comment by ld9866** [comment]
java -version
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.20.04)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.20.04, mixed mode, sharing)
l think l have the right java.

**Comment by erikrikarddaniel** [comment]
You're getting the same error message as before, which to me indicates you've gone back to a non-working version of Java since that solved your problem then. 

When you get the same error message as before, please check that the `hello` workflow still works.

**Comment by ld9866** [comment]
Thank you very much for your patience when I installed the software.
Now I have the software installed and am testing the next tasks
Thank you very much.

./nextflow pull nf-core/ampliseq
Checking nf-core/ampliseq ...
 done - revision: 1e76f1c0c6 [1.2.0]
