### ISSUE TITLE
Add support for IonTorrent data

### ISSUE THREAD

**Issue by jtangrot** [nf-core/ampliseq#279]
For fungi, it's not been uncommon to sequence with IonTorrent. It should be fairly straight-forward to add support for this, just changing settings in DADA2 according to their recommendations for IonTorrent data.

**Comment by d4straub** [comment]
An additional parameter such as `--iontorrent` that causes appropriate minor changes in DADA2 settings, a test data set, a new test config, and documentation seem needed.
I have never came across IonTorrent data, so I have no clue how it looks like.

**Comment by d4straub** [comment]
This was solved in https://github.com/nf-core/ampliseq/pull/280, wasn't it?
