### ISSUE TITLE
Error executing process > ' AMPLISEQ: RENAME_RAW_DATA_FILES"

### ISSUE THREAD

**Issue by AaronHY** [nf-core/ampliseq#298]
Hello, I met some error when working on the single-ended data as below. Please help with this. Thank you indeed.

## Commands
nextflow run nf-core-ampliseq-2.0.0/workflow/    -profile singularity  --single_end  --input "test/Manifest1.tsv"     --FW_primer CCTACGGGRSGCAGCAG     --RV_primer GGACTACVVGGGTATCTAATC     --metadata "test/Metadata.tsv"   --max_cpus 10 --max_memory 180.GB --retain_untrimmed -- --trunclenf 280    --trunclenr 250

##results

Use DADA2 taxonomy classification
Pulling Singularity image https://depot.galaxyproject.org/singularity/bioconductor-dada2:1.18.0--r40h5f743cb_0 [cache /mnt/g/ampliseq/work/singularity/depot.galaxyproject.org-singularity-bioconductor-dada2-1.18.0--r40h5f743cb_0.img]
Execution cancelled -- Finishing pending tasks before exit
-[nf-core/ampliseq] Pipeline completed with errors-
WARN: Singularity cache directory has not been defined -- Remote image will be stored in the path: /mnt/g/ampliseq/work/singularity -- Use env variable NXF_SINGULARITY_CACHEDIR to specify a different location
Error executing process > 'AMPLISEQ:RENAME_RAW_DATA_FILES (cojq004)'

Caused by:
  Process `AMPLISEQ:RENAME_RAW_DATA_FILES (cojq004)` terminated with an error exit status (1)

Command executed:

  [ ! -f  cojq004.fastq.gz ] && ln -s cojq004.fastq.gz cojq004.fastq.gz

Command exit status:
  1

Command output:
  (empty)

Command error:
  WARNING: Skipping mount /usr/local/var/singularity/mnt/session/etc/resolv.conf [files]: /etc/resolv.conf doesn't exist in container

**Comment by erikrikarddaniel** [comment]
Difficult to say, but I have a guess since I've recently came across a similar weird error. We might have a bug that happens when sample names doesn't contain any underscore characters. Can you do an `ls -l` on the work directory?

If you're running with a sample sheet, try adding e.g. "sample_" before the sample names, that helped for me.

Please let us know if adding "sample_" helped, so I can add a bug issue.

**Comment by AaronHY** [comment]
Thanks for the kindly response. I made some attempt and still failed in the cutadapt process. Your help would be very much appreciated.

When working on the directory, I defined the sample as samplename_R1_001.fastq.gz (e.g. cojq001_R1_001.fastq.gz) and there comes some error in cutadapt processess as PART1 shows.

As suggested, I have also added "sample_"before the sample names in the Manifest.tsv as below and there still come error in the cutadapt process as PART2

# Manifest.tsv
sampleID	forwardReads
sample_cojq001	/mnt/g/ampliseq/data/cojq001.fastq.gz
sample_cojq002	/mnt/g/ampliseq/data/cojq002.fastq.gz
sample_cojq003	/mnt/g/ampliseq/data/cojq003.fastq.gz
sample_cojq004	/mnt/g/ampliseq/data/cojq004.fastq.gz
sample_cojq005	/mnt/g/ampliseq/data/cojq005.fastq.gz
------------------------------------------------------------------
PART I


# Commands
nextflow run ../ampliseq/nf-core-ampliseq-2.0.0/workflow/ -profile singularity --single_end --input test --FW_primer CCTACGGGRSGCAGCAG --RV_primer GGACTACVVGGGTATCTAATC --metadata test/Metadata.tsv --max_cpus 10 --max_memory 180.GB --retain_untrimmed -- --trunclenf 280 --trunclenr 250


# Results
Error executing process > 'AMPLISEQ:CUTADAPT_WORKFLOW:CUTADAPT (cojq004)'

Caused by:
  Process `AMPLISEQ:CUTADAPT_WORKFLOW:CUTADAPT (cojq004)` terminated with an error exit status (2)

Command executed:

  cutadapt \
      --cores 6 \
      --minimum-length 1 -g CCTACGGGRSGCAGCAG \
      -o cojq004.trim.fastq.gz \
      cojq004.fastq.gz \
      > cojq004.cutadapt.log
  echo $(cutadapt --version) > cutadapt.version.txt

Command exit status:
  2

Command output:
  (empty)

Command error:
  WARNING: Skipping mount /usr/local/var/singularity/mnt/session/etc/resolv.conf [files]: /etc/resolv.conf doesn't exist in container
  Run "cutadapt --help" to see command-line options.
  See https://cutadapt.readthedocs.io/ for full documentation.

  cutadapt: error: [Errno 2] No such file or directory


-----------------------------------------------------------------

PART 2

## Commands

nextflow run ../ampliseq/nf-core-ampliseq-2.0.0/workflow/ -profile singularity --single_end --input test/Manifest1.tsv --FW_primer CCTACGGGRSGCAGCAG --RV_primer GGACTACVVGGGTATCTAATC --metadata test/Metadata.tsv --max_cpus 10 --max_memory 180.GB --retain_untrimmed -- --trunclenf 280 --trunclenr 250

# Results

-[nf-core/ampliseq] Pipeline completed with errors-
Error executing process > 'AMPLISEQ:CUTADAPT_WORKFLOW:CUTADAPT (sample_cojq006)'

Caused by:
  Process `AMPLISEQ:CUTADAPT_WORKFLOW:CUTADAPT (sample_cojq006)` terminated with an error exit status (2)

Command executed:

  cutadapt \
      --cores 6 \
      --minimum-length 1 -g CCTACGGGRSGCAGCAG \
      -o sample_cojq006.trim.fastq.gz \
      sample_cojq006.fastq.gz \
      > sample_cojq006.cutadapt.log
  echo $(cutadapt --version) > cutadapt.version.txt

Command exit status:
  2

Command output:
  (empty)

Command error:
  WARNING: Skipping mount /usr/local/var/singularity/mnt/session/etc/resolv.conf [files]: /etc/resolv.conf doesn't exist in container
  Run "cutadapt --help" to see command-line options.
  See https://cutadapt.readthedocs.io/ for full documentation.

  cutadapt: error: [Errno 2] No such file or directory

**Comment by erikrikarddaniel** [comment]
It's a little confusing with your two parts, especially since the first one has a `Manifest.tsv` that has `sample_` prepended to sample names, but the cutadapt step then doesn't have that.

Anyway, it seems like adding `sample_` to sample names made the pipeline pass the renaming step, which was your first issue, right?

The cutadapt step should then get an input file name like `sample_cojq006.fastq.gz` as it does in step 2.

Have you tried to `cd` into the work directory to check which files are there, if there are any broken symlinks and what the `.command.sh` looks like?

Also, try to remove the `work` directory before you start next time to make sure you have a clean directory.

**Comment by AaronHY** [comment]
Thanks. I have rerun the pipeline after removing the work drectory. there still comes the error with cutadapt as below. I have cd into the work directory to  check the files and the sample_cojq008.fastq.gz seems problematic with  0 k.  Should I also need to change the sample name as “sample_name ”in the Metadata.tsv as well?

the .command.sh is :

#!/bin/bash -euo pipefail
cutadapt \
    --cores 6 \
    --minimum-length 1 -g CCTACGGGRSGCAGCAG \
    -o sample_cojq008.trim.fastq.gz \
    sample_cojq008.fastq.gz \
    > sample_cojq008.cutadapt.log
echo $(cutadapt --version) > cutadapt.version.txt


-----------------------------------------------------------

Pulling Singularity image https://depot.galaxyproject.org/singularity/fastqc:0.11.9--0 [cache /mnt/g/ampliseq2/work/singularity/depot.galaxyproject.org-singularity-fastqc-0.11.9--0.img]
Execution cancelled -- Finishing pending tasks before exit
-[nf-core/ampliseq] Pipeline completed with errors-
WARN: Singularity cache directory has not been defined -- Remote image will be stored in the path: /mnt/g/ampliseq2/work/singularity -- Use env variable NXF_SINGULARITY_CACHEDIR to specify a different location
Error executing process > 'AMPLISEQ:CUTADAPT_WORKFLOW:CUTADAPT (sample_cojq008)'

Caused by:
  Process `AMPLISEQ:CUTADAPT_WORKFLOW:CUTADAPT (sample_cojq008)` terminated with an error exit status (2)

Command executed:

  cutadapt \
      --cores 6 \
      --minimum-length 1 -g CCTACGGGRSGCAGCAG \
      -o sample_cojq008.trim.fastq.gz \
      sample_cojq008.fastq.gz \
      > sample_cojq008.cutadapt.log
  echo $(cutadapt --version) > cutadapt.version.txt

Command exit status:
  2

Command output:
  (empty)

Command error:
  WARNING: Skipping mount /usr/local/var/singularity/mnt/session/etc/resolv.conf [files]: /etc/resolv.conf doesn't exist in container
  Run "cutadapt --help" to see command-line options.
  See https://cutadapt.readthedocs.io/ for full documentation.

  cutadapt: error: [Errno 2] No such file or directory

Work dir:
  /mnt/g/ampliseq2/work/8d/831910

**Comment by erikrikarddaniel** [comment]
For cutadapt, you don't need to change the sample name in `Metadata.tsv`, but for the downstream analyses you do.

Does the original file, i.e. the one that was renamed to `sample_cojq008.fastq.gz` have content?

I need to look into the original issue, i.e. if we do have a problem with no underscores in sample names. I'll try to get that done today.

**Comment by AaronHY** [comment]
Thanks again. No, the original file, renamed to sample_cojq**.fastq.gz doesn't have content.

I have rerun the whole pipeline again on the pair-ended data and there still come the error with the cutadapt.

-[nf-core/ampliseq] Pipeline completed with errors-
Error executing process > 'AMPLISEQ:CUTADAPT_WORKFLOW:CUTADAPT (sample_cojq011)'

Caused by:
  Process `AMPLISEQ:CUTADAPT_WORKFLOW:CUTADAPT (sample_cojq011)` terminated with an error exit status (2)

Command executed:

  cutadapt \
      --cores 6 \
      --minimum-length 1 -g ACTCCTACGGGAGGCAGCAG -G GGACTACHVGGGTWTCTAAT --discard-untrimmed \
      -o sample_cojq011_1.trim.fastq.gz -p sample_cojq011_2.trim.fastq.gz \
      sample_cojq011_1.fastq.gz sample_cojq011_2.fastq.gz \
      > sample_cojq011.cutadapt.log
  echo $(cutadapt --version) > cutadapt.version.txt

Command exit status:
  2

Command output:
  (empty)

Command error:
  WARNING: Skipping mount /usr/local/var/singularity/mnt/session/etc/resolv.conf [files]: /etc/resolv.conf doesn't exist in container
  Run "cutadapt --help" to see command-line options.
  See https://cutadapt.readthedocs.io/ for full documentation.

  cutadapt: error: [Errno 2] No such file or directory

Work dir:
  /mnt/g/ampliseqsu/work/a7/e740bfd2b39e2822873fd754603172

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`

The files in a7:

sample_cojq011_1.fastq.gz         0KB
sample_cojq011_1.trim.fastq.gz 1KB
sample_cojq011_2.fastq.gz         0KB
sample_cojq011_2.trim.fastq.gz 1KB

**Comment by erikrikarddaniel** [comment]
If your input files are empty, cutadapt will fail. Check them all, remove the empty ones and try again.

(The bug we have regarding sample names turned out not to be lack of an '_', but that we didn't handle cases where the sample name is the same as the filename minus `.fastq.gz`. I've fixed this, but due to vacations it will take a while to reach the stable version of Ampliseq.)

**Comment by AaronHY** [comment]
The *.fastq.gz I input were not empty. But the ones renamed for cutadapt procedure have no contents.

**Comment by erikrikarddaniel** [comment]
Strange. The renaming process only creates symbolic links to the existing files, so actually no real renaming. Check the work directory where one of the renaming processes ran.

**Comment by d4straub** [comment]
This has been addressed in #306 and is currently in the dev branch. @AaronHY do you want to test with the dev version of the pipeline?

**Comment by AaronHY** [comment]
Fantastic，Please tell me how to set up the dev version.

**Comment by d4straub** [comment]
Like this:
```
nextflow pull nf-core/ampliseq -r dev
nextflow run nf-core/ampliseq -r dev [... your settings ...]
```

The `nextflow pull` command is only needed once whenever you try a new pipeline/version. `-r` specifies the version, for ampliseq that could be a release, e.g. `-r 2.0.0` or dev version `-r dev`.

**Comment by AaronHY** [comment]
Thanks. I did as you suggested and but it comes ‘project ‘nf-core/ampliseq’ contains uncommitted changes — cannot switch to revision: dev’

**Comment by d4straub** [comment]
Than you either did not use the exact two commands that I wrote above (so please supply them!) and/or you messed with the files (that you are not supposed to do).

**Comment by AaronHY** [comment]
Thanks for the response. I use the commands as below:

 nextflow run nf-core/ampliseq -r dev -profile singularity  --input test/Manifest.tsv --FW_primer ACTCCTACGGGAGGCAGCAG --RV_primer  GGACTACHVGGGTWTCTAAT --metadata test/Metadata.tsv --max_cpus 10 --max_memory 180.GB --trunclenf 280 --trunclenr 250

nextflow pull nf-core/ampliseq -r dev

Then it comes the error I mentioned before :  nf-core/ampliseq contains uncommitted changes -- cannot pull from repository

**Comment by d4straub** [comment]
It seems you modified the pipelines files, this is not a good idea. If you do this, I have no way of giving any advice, because I do not know what you might have changed.
While I have never done this myself, you can try [`drop`](https://www.nextflow.io/docs/latest/cli.html#drop) to delete the modified pipeline, `pull` a new copy and `run` it, e.g.
```
nextflow drop nf-core/ampliseq -r dev
nextflow pull nf-core/ampliseq -r dev
nextflow run nf-core/ampliseq -r dev [...]
```

**Comment by d4straub** [comment]
Closing due to no response. Feel free to open another issue if you are having trouble.
