### ISSUE TITLE
--multiple_sequencing_runs option ignored

### ISSUE THREAD

**Issue by lokeshbio** [nf-core/ampliseq#328]
## Check Documentation

I have checked the following places for your error:

- [ x] [nf-core website: troubleshooting](https://nf-co.re/usage/troubleshooting)
- [ x] [nf-core/ampliseq pipeline documentation](https://nf-co.re/ampliseq/usage)

## Description of the bug

`--multiple_sequencing_runs` is being ignored and I get the error message saying that the reads cant be found followed by a message asking to add the option! But the option is already given!

## Steps to reproduce

Steps to reproduce the behaviour:

1. Command line: 
2. See error: 

## Log files

Have you provided the following extra information/files:

- [x] The command used to run the pipeline
- [x] The `.nextflow.log` file 

## System

- Hardware: 
- Executor: 
- OS: 
- Version 

## Nextflow Installation

- Version: 

## Container engine

- Engine: 
- version: 

## Additional context

<!-- Add any other context about the problem here. --
[nextflow.log](https://github.com/nf-core/ampliseq/files/7216734/nextflow.log)
>

**Comment by d4straub** [comment]
There is a space in `--input /crex/proj/snic2020- 16-248/nobackup/insect-biome-atlas/data/Ampliseq_test_data/P19506_test`, therefore it wont work. Without the copy of the error message (and more details, e.g. your folder structure) I cannot help any further.

**Comment by lokeshbio** [comment]
Thanks for a quick reply! There is actually no space, when I pasted the command something happend here :) I tried to attach the log file here, but I couldnt manage it! I will try again now!
[nextflow.log](https://github.com/nf-core/ampliseq/files/7217251/nextflow.log)

**Comment by d4straub** [comment]
I see, indeed, the pipeline cannot find any read files using the parameters you provided. The error message in the log is 

```
Cannot find any reads matching: "/crex/proj/snic2020-16-248/nobackup/insect-biome-atlas/data/Ampliseq_test_data/P19506_test/*_trim_s4_R{1,2}.fastq.gz"
Please revise the input folder ("--input"): "/crex/proj/snic2020-16-248/nobackup/insect-biome-atlas/data/Ampliseq_test_data/P19506_test"
and the input file pattern ("--extension"): "/*_trim_s4_R{1,2}.fastq.gz"
If you have multiple sequencing runs, please add "--multiple_sequencing_runs".
NB: Path needs to be enclosed in quotes!
```

I actually agree, that error message is slightly misleading. You do have already added `--multiple_sequencing_runs` and the path that is actually searched for files is not `/crex/proj/snic2020-16-248/nobackup/insect-biome-atlas/data/Ampliseq_test_data/P19506_test/*_trim_s4_R{1,2}.fastq.gz` but `/crex/proj/snic2020-16-248/nobackup/insect-biome-atlas/data/Ampliseq_test_data/P19506_test/*/*_trim_s4_R{1,2}.fastq.gz`.

**Comment by lokeshbio** [comment]
Ah, I see now what you mean @d4straub! Should I include that in the extension then? would it automatically recognize the different runs?

**Comment by d4straub** [comment]
When you use folder input, the element before the first underscore is used as sample name. `--extension` has no influence on it. Use samplesheet input in the case that sample names cannot retrieved automatically as described.

This is actually documented in the [usage docs](https://nf-co.re/ampliseq/2.1.0/usage#direct-fastq-input):
`Sample identifiers are extracted from file names, i.e. the string before the first underscore _, these must be unique (also across sequencing runs)`

I have opened #329 with a clear description and close this issue here.
