### ISSUE TITLE
option to skip chimeric read removal

### ISSUE THREAD

**Issue by xiaoyunguo** [nf-core/ampliseq#332]
## Is your feature request related to a problem? Please describe

First thanks for the efforts putting out this pipeline. I am running this pipeline to preprocess Amplicon sequencing data, due to the specific nature of the experiment, removing chimeric reads might risk loosing real signals. Is it possible to make an option to skip this step? 

## Describe the solution you'd like

An option to skip chimeric read removal

**Comment by xiaoyunguo** [comment]
Awesome, thanks for the quick reply.

Best,

Xiaoyun

**Comment by d4straub** [comment]
I'll close that issue because it seems resolved. If anyone else also thinks that chimera removal should be skip-able with a parameter, open another issue and let me know!
