### ISSUE TITLE
overall_summary.tsv sample name issue with --illumina_pe_its

### ISSUE THREAD

**Issue by d4straub** [nf-core/ampliseq#334]
## Description of the bug

When using `--illumina_pe_its`, `overall_summary.tsv` contains additional rows for samples that end with `_1`, e.g. `sampleID_1` > `sampleID`

| sample | cutadapt_total_processed | cutadapt_reverse_complemented | cutadapt_passing_filters | cutadapt_passing_filters_percent | DADA2_input | filtered | denoisedF | denoisedR | merged | nonchim |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| sampleID | NA | NA | NA | NA | 1812 | 1446 | 1233 | 1173 | 1072 | 1072 |
| sampleID_1 | 2,500 | NA | 1,812 | 72.5% | NA | NA | NA | NA | NA | NA |

## Steps to reproduce

This is fine:
`nextflow run nf-core/ampliseq -r 2.1.0 -profile test,singularity --skip_qiime`
This contains the additional row:
`nextflow run nf-core/ampliseq -r 2.1.0 -profile test,singularity --skip_qiime --illumina_pe_its`

## Additional context

`sampleID` instead if `sampleID_1` is already present in `dada2/DADA2_stats.tsv`, but all other files seem ok. Therefore it most likely originates in [dada2_stats.nf](https://github.com/nf-core/ampliseq/blob/master/modules/local/dada2_stats.nf).

**Comment by erikrikarddaniel** [comment]
The R code is ugly (and I'm responsible for that). I now have a mulled container with "Tidyverse" and some other more modern R packages -- perhaps we can reimplement with that or ask for another mulled container and tidy up the code?

(From `hash.tsv`: `r-optparse=1.6.6,r-tidyverse=1.3.1,r-data.table=1.14.0,r-dtplyr=1.1.0,bioconductor-biostrings=2.58.0,bioconductor-treeio=1.14.3,r-ape=5.4_1,bioconductor-ggtree=2.4.1`, Docker: `quay.io/biocontainers/mulled-v2-508c9bc5e929a77a9708902b1deca248c0c84689:0bb5bee2557136d28549f41d3faa08485e967aa1-0`, Singularity: `https://depot.galaxyproject.org/singularity/mulled-v2-508c9bc5e929a77a9708902b1deca248c0c84689:0bb5bee2557136d28549f41d3faa08485e967aa1-0`)

**Comment by d4straub** [comment]
Hm, currently `dada2_stats.nf` is using the DADA2 container, if that's not needed, than we could use that mulled container.
But I have to admit I might be not able to write a clean R code for that module. I was hoping a rather small change might fix the bug and I wanted to look for such a fix next week.

**Comment by d4straub** [comment]
Solved!
