### ISSUE TITLE
Input files could be copied into results folder

### ISSUE THREAD

**Issue by d4straub** [nf-core/ampliseq#347]
## Is your feature request related to a problem? Please describe

The pipeline does not store or save input files (_edit: I do not mean here raw data, but samplesheet and metadata sheet as specified below_) and in light of reproducibility, it is nice to have those files preserved in the results folder as well. As of now, I always copy them after a pipeline run into the results folder myself, but that seems something to be rather automatized.

## Describe the solution you'd like

Input files such as samplesheet (via `--input`) and metadata (`--metadata`) (_edit: but not sequencing data files_) should be copied into the results folder, probably in a subfolder named input, to facilitate reproducibility.

**Comment by erikrikarddaniel** [comment]
Are there any principles in the nf-core community for this? I suppose it can apply to virtually any pipeline, but that space considerations of having input files copied by default could be quite problematic for other kinds of sequencing.

**Comment by erikrikarddaniel** [comment]
Correct, I read it as referring to sequence reads. I probably jumped to conclusions again!

**Comment by d4straub** [comment]
Done in dev.
