### ISSUE TITLE
Add PhytoRef to database collection

### ISSUE THREAD

**Issue by erikrikarddaniel** [nf-core/ampliseq#349]
## Is your feature request related to a problem? Please describe

PhytoRef is a 16S database of chloroplast sequences: http://phytoref.sb-roscoff.fr/

## Describe the solution you'd like

Add the database to supported databases for DADA2 (at least).

## Additional context

I'm suspicious about the taxonomy hierarchy since it's eukaryotes -- are there different number of ranks?

**Comment by d4straub** [comment]
Looks good, but I was not able to find (in short time) whether they have some sort of versioning or whether there are several versions or when it was updated last. Nevertheless, more ref tax databases are always a selling point! 

At the moment I would go with adding databases only for DADA2. Eventually I need to benchmark DADA2/QIIME2 and probably a 3rd way to classify ASVs in the pipeline, but that is not very high priority for me right now.

**Comment by erikrikarddaniel** [comment]
I have some colleagues working on other algorithms with the intention of integrating them here. Your 3rd way may hence come without you doing anything.

**Comment by d4straub** [comment]
Great news! Than it might make sense to wait with the benchmarking until that algorithm of your colleagues is here anyway.

**Comment by vaulot** [comment]
Just as a comment, now PhytoRef (plastid sequences) are integrated into PR2 version 5.0.0.  Also some errors have been corrected.  So I think it is better to retire PhytoRef.

**Comment by erikrikarddaniel** [comment]
> Just as a comment, now PhytoRef (plastid sequences) are integrated into PR2 version 5.0.0. Also some errors have been corrected. So I think it is better to retire PhytoRef.

Good to know. We forgot to close this issue when we added this database. I'll close this now, and open a new for removing PhytoRef.
