### ISSUE TITLE
Inconsistencies in PR2

### ISSUE THREAD

**Issue by erikrikarddaniel** [nf-core/ampliseq#351]
It seems there are inconsistencies in how the PR2 database is handled:

1. There might be different number of ranks in the input file, Dinoflagellata has 8 instead of 7.
2. Why does the `assignTaxonomy` file have species? GTDB doesn't.

**Comment by d4straub** [comment]
Do you mean how ampliseq handles PR2 or is that a problem with PR2 itself?

**Comment by erikrikarddaniel** [comment]
> Do you mean how ampliseq handles PR2 or is that a problem with PR2 itself?

It's a bit of both. I'm not sure if PR2 has the same number of ranks for all entries, and my script does not return the correct ranks. I think, needs to be looked into.

**Comment by erikrikarddaniel** [comment]
It turns out PR2 always has 8 ranks: "Kingdom / Supergroup / Division / Class / Order / Family / Genus / Species" (https://pr2-database.org/documentation/pr2-structure/). For us there are a number of issues to think about:

1. We currently enforce 7 ranks for the other databases: domain, kingdom, phylum, class, order, family, genus. Even though it was my suggestion to stick to these seven, I can see that uses of e.g. PR2 would prefer to have all their ranks supported. I'd therefore suggest that we add a field to `conf/ref_databases.config`: `ranks`, where the ranks are enumerated.
2. This has consequences for instance for `modules/local/dada2_taxonomy.nf`. My base R doesn't permit me to fix this but I think I can do it with the tidyverse. This would require a "mulled" container for that module containing DADA2 plus tidyverse. No problem in itself, but before I ask for one, we should maybe think about what else we might want to have in it.
3. To me, "Kingdom" should be "Domain" as it's always "Archaea", "Bacteria" or "Eukaryota" and not at all the classical Linnean kingdoms: animals, plants etc. Again, if the PR2 people calls this "Kingdom" there's a point in adhering to the PR2 standard and a possibility would be to duplicate the field and add the "Domain" rank to the top, similar to what we do with "Kingdom" for e.g. GTDB.

**Comment by d4straub** [comment]
>   We currently enforce 7 ranks for the other databases: domain, kingdom, phylum, class, order, family, genus. Even though it was my suggestion to stick to these seven, I can see that uses of e.g. PR2 would prefer to have all their ranks supported. I'd therefore suggest that we add a field to conf/ref_databases.config: ranks, where the ranks are enumerated.

`conf/ref_databases.config` contains now optional `taxlevels` that serve this purpose, see https://github.com/nf-core/ampliseq/pull/459

> This has consequences for instance for modules/local/dada2_taxonomy.nf. My base R doesn't permit me to fix this but I think I can do it with the tidyverse. This would require a "mulled" container for that module containing DADA2 plus tidyverse. No problem in itself, but before I ask for one, we should maybe think about what else we might want to have in it.

Have fixed that in https://github.com/nf-core/ampliseq/pull/460

> To me, "Kingdom" should be "Domain" as it's always "Archaea", "Bacteria" or "Eukaryota" and not at all the classical Linnean kingdoms: animals, plants etc. Again, if the PR2 people calls this "Kingdom" there's a point in adhering to the PR2 standard and a possibility would be to duplicate the field and add the "Domain" rank to the top, similar to what we do with "Kingdom" for e.g. GTDB.

That could be adjusted now easily by adding appropriate `taxlevels` entry in `conf/ref_databases.config`.

> One of the PR2 people (Daniel Vaulot) says: "You can use all the taxonomic levels down to species when you use assignTaxonomy. This is true for both Euks and Prok (PR2 has a small number of representative Prok sequences). I personally never use assignSpecies which is only useful when you want to make sure that the sequence of your ASV is 100% identical to a reference species sequence." This would be problematic in Ampliseq as addSpecies is automatically run and would overwrite any species assignment from the assignTaxonomy step (usually with an NA or blank). Having different defaults for which steps to run for different taxonomy databases would not feel right. Edit: I now realize that we actually produce two output files, one for assignTaxonomy and one for addSpecies, so both could theoretically have species. Would it be confusing? Should we rename the species column in the addSpecies table to e.g. addSpecies to signify that this field comes from another algorithm?

I see, that is a good point and overlaps with https://github.com/nf-core/ampliseq/issues/387
We can think about how that could be done.

**Comment by d4straub** [comment]
Is that solved with the above PR merged or do we need to address the following part?
> 
> > To me, "Kingdom" should be "Domain" as it's always "Archaea", "Bacteria" or "Eukaryota" and not at all the classical Linnean kingdoms: animals, plants etc. Again, if the PR2 people calls this "Kingdom" there's a point in adhering to the PR2 standard and a possibility would be to duplicate the field and add the "Domain" rank to the top, similar to what we do with "Kingdom" for e.g. GTDB.
> 
> That could be adjusted now easily by adding appropriate taxlevels entry in conf/ref_databases.config.

As far as I see the PR2 file isnt altered.

**Comment by erikrikarddaniel** [comment]
> Is that solved with the above PR merged or do we need to address the following part?
> 
> > > To me, "Kingdom" should be "Domain" as it's always "Archaea", "Bacteria" or "Eukaryota" and not at all the classical Linnean kingdoms: animals, plants etc. Again, if the PR2 people calls this "Kingdom" there's a point in adhering to the PR2 standard and a possibility would be to duplicate the field and add the "Domain" rank to the top, similar to what we do with "Kingdom" for e.g. GTDB.
> > 
> > 
> > That could be adjusted now easily by adding appropriate taxlevels entry in conf/ref_databases.config.
> 
> As far as I see the PR2 file isnt altered.

At least I haven't touched it, or do you mean upstream? In any case, I think this is all good now, except for the SBDI export which is on my plate. I'm closing this.
