### ISSUE TITLE
Usage single ended reads

### ISSUE THREAD

**Issue by colindaven** [nf-core/ampliseq#353]
## Check Documentation

I have checked the following places for your error:

- [x] [nf-core website: troubleshooting](https://nf-co.re/usage/troubleshooting)
- [x] [nf-core/ampliseq pipeline documentation](https://nf-co.re/ampliseq/usage)

## Description of the bug

I don't know if this is a bug or incorrect /unexpected usage

## Steps to reproduce

Steps to reproduce the behaviour:

1. Command line: nextflow run nf-core/ampliseq     -profile singularity     --input "/ngsssd1/rcug/2021_038676/miseq"     --extension "/*_{R1}.fastq.gz"     --FW_primer GTGYCAGCMGCCGCGGTAA     --RV_primer GGACTACNVGGGTWTCTAAT  --dada_ref_taxonomy "silva=138"    --singularity_pull_docker_container true --single_end

2. See error: 

```
Error executing process > 'NFCORE_AMPLISEQ:AMPLISEQ:RENAME_RAW_DATA_FILES (*)'

Caused by:
  Process `NFCORE_AMPLISEQ:AMPLISEQ:RENAME_RAW_DATA_FILES (*)` terminated with an error exit status (1)

Command executed:

  if [ ! -f  *.fastq.gz ]; then
      ln -s *_{R1}.fastq.gz *.fastq.gz
  else
      touch *.fastq.gz
  fi

Command exit status:
  1

Command output:
  (empty)

Command error:
  ln: failed to create symbolic link '*_{R1}.fastq.gz': File exists

```

## Expected behaviour

I am not sure what the softlinking is trying to achieve. The pipeline runs find in PE mode, but had few merged reads (data problem) so I wanted to try the SE version.

## Log files

Have you provided the following extra information/files:

- [ ] The command used to run the pipeline
- [ ] The `.nextflow.log` file 

## System

- Hardware: hpc server
- Executor: local
- OS: ubuntu 2004
- Version nf 21.03

## Nextflow Installation

- Version: 21.03

## Container engine

- Engine: singularity
- version: 3.5.3

**Comment by d4straub** [comment]
First, I would strongly advice to use `-r`, i.e. `-r 2.1.1` for the most recent release! Right now, I cannot tell from your info (command is ambiguous, no .nextflow.log attached) what version of the pipeline you are actually using, thats a real problem for troubleshooting.

But yes, that looks like unintended behavior.
That code was introduced in https://github.com/nf-core/ampliseq/pull/306, that needs further investigation. Could you provide also the names of the files in your input folder?

I guess for now you could switch to the [samplesheet input](https://nf-co.re/ampliseq/2.1.1/usage#samplesheet-input) using `--input`, that might solve the issue!

**Comment by colindaven** [comment]
Ok, thanks for the tips. Getting the error so far with these file names (tried both with and without the _001). I moved the R2 reads out to avoid clashes, didn't help.

Sorry, I am using the most recent release (Singularity download today).

So the (two column) samplesheet tip worked - thanks. It must have been a bug or untested approach using the extension -`extension "/*_{R1}.fastq.gz" `

```

P10_S10_R1_001.fastq.gz
P11_S11_R1_001.fastq.gz
P12_S12_R1_001.fastq.gz
P1_S1_R1_001.fastq.gz
P2_S2_R1_001.fastq.gz
P3_S3_R1_001.fastq.gz
P4_S4_R1_001.fastq.gz
P5_S5_R1_001.fastq.gz
P6_S6_R1_001.fastq.gz
P7_S7_R1_001.fastq.gz
P8_S8_R1_001.fastq.gz
P9_S9_R1_001.fastq.gz

```

**Comment by d4straub** [comment]
Glad to hear that it worked with the samplesheet, but actually, `--extension "/*_R1_001.fastq.gz"` should work for the files listed above. 

Found the problem: 
`nextflow run nf-core/ampliseq -r 2.1.1 -profile test,singularity --metadata false --input data/testdata1 --extension "/*_L001_{R1}_001.fastq.gz" --single_end`
succeeds while
`nextflow run nf-core/ampliseq -r 2.1.1 -profile test,singularity --metadata false --input data/testdata1 --extension "/*_L001_R1_001.fastq.gz" --single_end`
fails with the error message you experience as well.

So the curly brackets were actually the problem. Thats actually a surprise!

**Comment by d4straub** [comment]
Docs are updated in the dev branch now, I'll close that issue.
