### ISSUE TITLE
sample IDs must not start with a number when using metadata

### ISSUE THREAD

**Issue by d4straub** [nf-core/ampliseq#357]
## Is your feature request related to a problem? Please describe

from nf-core slack #ampliseq:

> sample IDs must not start with a number. If they do an X gets added by R, and later QIIME2_BARPLOT can't find them in the metadata. Maybe this could be added to the sample sheet input requirements in the usage docs.

## Describe the solution you'd like

I could imagine 3 ways to resolve this problem:
- Add to documentation. Additionally, perform a test in [parse_input.nf](https://github.com/nf-core/ampliseq/blob/master/subworkflows/local/parse_input.nf) that either produces a warning about downstream analysis problems or even an error.
- Make sure that no X is added by R
- add automatically an X to sample IDs when they start with a number and --metadata is given.

_Edit: that last solution doesnt work, because the metadata is than still without "X" and will not match! SampleIDs also from the metadata needs to be preprended by an X!_

**Comment by erikrikarddaniel** [comment]
> ## Is your feature request related to a problem? Please describe
> 
> from nf-core slack #ampliseq:
> 
> > sample IDs must not start with a number. If they do an X gets added by R, and later QIIME2_BARPLOT can't find them in the metadata. Maybe this could be added to the sample sheet input requirements in the usage docs.
> 
> ## Describe the solution you'd like
> 
> I could imagine 3 ways to resolve this problem:
> 
>     * Add to documentation. Additionally, perform a test in [parse_input.nf](https://github.com/nf-core/ampliseq/blob/master/subworkflows/local/parse_input.nf) that either produces a warning about downstream analysis problems or even an error.
> 
Easy to overlook.

>     * Make sure that no X is added by R
> 
Will require postprocessing of the output file probably and/or ugly if clauses.

>     * add automatically an X to sample IDs when they start with a number and --metadata is given.

I vote for that. Maybe easiest to do even when `--metadata` is not given as it will be added by R anyway?
> 
> ## Describe alternatives you've considered
> ## Additional context

**Comment by d4straub** [comment]
Done in 2.2.0dev
