### ISSUE TITLE
Make addSpecies optional for cut_its too

### ISSUE THREAD

**Issue by jtangrot** [nf-core/ampliseq#370]
## Description of the bug
Maybe not a bug, but shouldn't addSpecies be optional also if you use the cut_its option? In the current dev release, the two opitions "skip_dada_addspecies" and "cut_its" are incompatible.

## Expected behaviour
Accept/implement --skip_dada_addspecies for cut_its too

**Comment by d4straub** [comment]
Agreed, those parameters should work.
The respective code seems to be in [workflows/ampliseq.nf](https://github.com/nf-core/ampliseq/blob/f1abc2010e849903f429a60e130da92b4ad2f8f8/workflows/ampliseq.nf#L319-L334) and adding the code in https://github.com/nf-core/ampliseq/blob/f1abc2010e849903f429a60e130da92b4ad2f8f8/workflows/ampliseq.nf#L321-L324 also to the closure in https://github.com/nf-core/ampliseq/blob/f1abc2010e849903f429a60e130da92b4ad2f8f8/workflows/ampliseq.nf#L327-L333 and adapting `FORMAT_TAXRESULTS` might do the trick.

**Comment by jtangrot** [comment]
Thanks, I'll have a look at it.

**Comment by d4straub** [comment]
Thanks for adding this, I'll close the issue!
