### ISSUE TITLE
Change parameters for ITSx in cut_its argument

### ISSUE THREAD

**Issue by jtangrot** [nf-core/ampliseq#371]
## Is your feature request related to a problem? Please describe
Sometimes the complete ITS sub-regions can not be reported by ITSx, e.g. ITS1 (and therefore the full ITS sequence) can not be reported by ITSx when too much of SSU is missing, which might very well happen depending on primers used. Also, sometimes it's more reasonable to select only the ITS2 region instead of the complete ITS sequence, as is implemented now in ampliseq.

## Describe the solution you'd like
I would like to 
(i) change the parameters for ITSx to add "--partial 15" in order to allow ITSx to report also partial ITS regions if they are longer than the cutoff. 
(ii) add "--save_regions ITS2" to the ITSx call and change the options to "--cut_its" to make it possible to select whether you want to use the full ITS region or only ITS2.

I can implement this, but need to know if there are any reasons why I should not...

**Comment by jtangrot** [comment]
>> (i) change the parameters for ITSx to add "--partial 15" 

>If I understand that right, it will make ITSx report more (above the length threshold) and not less ITS regions? 

That's correct, and the reason why I want to do the change. This will make the number of ITS regions go from none to present in almost all sequences in a dataset where the first amplicon primer is located at the end of the SSU region.

>Is this something that should be often adjusted? If yes, than this could be a parameter, if no, it could be default. If this parameter increases artifacts (because being less strict) strongly, than it might be better to not add that by default (by either as parameter or even let the user use -c with a file that modifies the process args; only advanced user will do that though).

There is a risk that ITSx will report ITS sequences that are not really ITS. However, in this case I find that acceptable as we have already selected for the ITS region with the choice of primers for amplicons, and as the resulting ITS sequences are intended to be used for taxonomy assignment only. I would like to add it as default, but you are right that it should be possible to turn it off and/or adjust the threshold (I realize now that the value I gave as example might be a bit low)

>Are you thinking about allowing --cut_its to accept values, e.g. --cut_its "full_ITS", --cut_its "ITS2" or such? 

Yes, exactly. In the future someone might want to add ITS1, LSU, or something else, but at the moment I don't see a need for that. 

>However, it would make previous commands (using only --cut_its) invalid. That isn't nice but acceptable, if the change brings reasonable improvement.

Correct, that's not nice. Do you know some other way to do this that is nicer? We could add another parameter for changing region, but then there will be lots of parameters to keep track of...

**Comment by d4straub** [comment]
> There is a risk that ITSx will report ITS sequences that are not really ITS. However, in this case I find that acceptable as we have already selected for the ITS region with the choice of primers for amplicons, and as the resulting ITS sequences are intended to be used for taxonomy assignment only.

Agreed.

> I would like to add it as default, but you are right that it should be possible to turn it off and/or adjust the threshold (I realize now that the value I gave as example might be a bit low)

If you can define a reasonable well working default and it is only to be expected to be changed in very special/rare occasions, than its totally fine to me to not make a pipeline parameter and refer to solve that by `-c` and a config. You can judge that better than me!

> Correct, that's not nice. Do you know some other way to do this that is nicer? We could add another parameter for changing region, but then there will be lots of parameters to keep track of...

I would prefer changing the behavior of `--cut_its` instead of adding another parameter. Theoretically, it should be possible to check whether the parameter holds a specific string (ITS1, ITS2, LSU, whatever) and if its not, but it is true, than it uses a default setting. However, that might be not possible with the current way of parameter checking, because it might be that either `boolean` or `string` are allowed, but no mixture of these. Never tried it though. If it doesnt work, just change `--cut_its`'s behavior to require a string and use controlled vocabulary in `nextflow_schema.json`.

**Comment by jtangrot** [comment]
This is solved in PR #390
