### ISSUE TITLE
Allow skipping primer trimming

### ISSUE THREAD

**Issue by d4straub** [nf-core/ampliseq#382]
### Description of feature

Currently, the pipeline forces trimming primer sequences. But there are some cases where it is not appropriate to do so. For example when receiving sequences without primer sequences or when there are specific problems that require trimming primers before using ampliseq. Those cases are seldom, but probably more frequent than I thought.
Therefore, it might be good to add a --skip_cutadapt or --skip_primertrimming or similar, but with a big warning (!?). That would also mean making primer sequence input optional. 
That does make also sense when using a fasta (OTU/ASV) file as input, since than primer sequences have limited use (well, still required for QIIME2 taxonomic classification). So a few parameter sanity checks should be put in place.

**Comment by schifferl** [comment]
Hi @d4straub, just wanted to say that I do have a need for this parameter and that `--skip_cutadapt` seems like the right name. Would it take long to implement? Can I help?

**Comment by d4straub** [comment]
Hi there, it would not take very long to implement it into the `dev` branch (but longer until it appears in a release), the issue is to raise some appropriate warnings and add parameter checks. So if its ok for you to use the dev branch instead of a proper release, I'd be able to add it next week I guess. If you want to do it earlier, I am happy to review a pull request.

**Comment by schifferl** [comment]
Hello again, I'd be ok to use the `dev` branch and test the new parameter – just @ message me when you're ready for me to give it a try. I'll standby on a pull request if you have something in the works already. Thanks for the response!

**Comment by d4straub** [comment]
@schifferl thats not in the dev branch!
