### ISSUE TITLE
Add the possibility to specify a seed 

### ISSUE THREAD

**Issue by erikrikarddaniel** [nf-core/ampliseq#386]
### Description of feature

To make the pipeline (even) more reproducible, add a parameter for seed that is then used in all relevant places (denosing, assigning taxonomy, QIIME modules (if possible)).

**Comment by d4straub** [comment]
I have added --seed in https://github.com/nf-core/ampliseq/pull/395, however, this is
- currently only used in `assignTaxonomy` and `addSpecies`, what else uses seeds? I could certainly just add it everywhere...
- I count not find QIIME2 using seeds
- resuming the pipeline doesnt take a new seed (let me know if thats acceptable)
