### ISSUE TITLE
qimme2 classifier error 

### ISSUE THREAD

**Issue by DooYal** [nf-core/ampliseq#388]
### Description of the bug

I installed scikit-learn 0.23.1, but the output is still interupted with reporting that "The scikit-learn version (0.21.2) used to generate this artifact does not match the current version of scikit-learn installed (0.23.1). Please retrain your classifier for your current deployment to prevent data-corruption errors."

### Command used and terminal output

```console
command
$sudo nextflow run nf-core/ampliseq -r 2.1.1 -profile docker --input "./Samplesheet_double.tsv" --FW_primer "AGTCAACCTAYGGGRBGCASCAG" --RV_primer "GGACTACNNGGGTATCTAATACTGAT" --classifier './gg-13-8-99-nb-classifier.qza' --outdir "./results_clas"


output
Error executing process > 'NFCORE_AMPLISEQ:AMPLISEQ:QIIME2_TAXONOMY:QIIME2_CLASSIFY (rep-seqs.qza,gg-13-8-99-nb-classifier.qza)'

Caused by:
  Process `NFCORE_AMPLISEQ:AMPLISEQ:QIIME2_TAXONOMY:QIIME2_CLASSIFY (rep-seqs.qza,gg-13-8-99-nb-classifier.qza)` terminated with an error exit status (1)

Command executed:

  export XDG_CONFIG_HOME="${PWD}/HOME"
  
  qiime feature-classifier classify-sklearn          --i-classifier gg-13-8-99-nb-classifier.qza          --p-n-jobs 16          --i-reads rep-seqs.qza          --o-classification taxonomy.qza          --verbose
  qiime metadata tabulate          --m-input-file taxonomy.qza          --o-visualization taxonomy.qzv          --verbose
  #produce "taxonomy/taxonomy.tsv"
  qiime tools export --input-path taxonomy.qza          --output-path taxonomy
  qiime tools export --input-path taxonomy.qzv          --output-path taxonomy
  cp taxonomy/taxonomy.tsv .
  
  echo $(qiime --version | sed -e "s/q2cli version //g" | tr -d '`' | sed -e "s/Run qiime info for more version details.//g") > qiime2.version.txt

Command exit status:
  1

Command output:
  (empty)

Command error:
  QIIME is caching your current deployment for improved performance. This may take a few moments and should only happen once per deployment.
  Traceback (most recent call last):
    File "/opt/conda/envs/qiime2-2021.2/lib/python3.6/site-packages/q2cli/commands.py", line 329, in __call__
      results = action(**arguments)
    File "<decorator-gen-359>", line 2, in classify_sklearn
    File "/opt/conda/envs/qiime2-2021.2/lib/python3.6/site-packages/qiime2/sdk/action.py", line 234, in bound_callable
      spec.view_type, recorder)
    File "/opt/conda/envs/qiime2-2021.2/lib/python3.6/site-packages/qiime2/sdk/result.py", line 289, in _view
      result = transformation(self._archiver.data_dir)
    File "/opt/conda/envs/qiime2-2021.2/lib/python3.6/site-packages/qiime2/core/transform.py", line 70, in transformation
      new_view = transformer(view)
    File "/opt/conda/envs/qiime2-2021.2/lib/python3.6/site-packages/q2_feature_classifier/_taxonomic_classifier.py", line 64, in _1
      % (sklearn_version, sklearn.__version__))
  ValueError: The scikit-learn version (0.21.2) used to generate this artifact does not match the current version of scikit-learn installed (0.23.1). Please retrain your classifier for your current deployment to prevent data-corruption errors.
  
  Plugin error from feature-classifier:
  
    The scikit-learn version (0.21.2) used to generate this artifact does not match the current version of scikit-learn installed (0.23.1). Please retrain your classifier for your current deployment to prevent data-corruption errors.
  
  See above for debug info.
```

**Comment by d4straub** [comment]
Hi there!

The database you specified via `--classifier './gg-13-8-99-nb-classifier.qza'` was made for (and most likely with) an older version of QIIME2 (and an older version of scikit-learn) than this pipeline uses. 

Ampliseq version 2.1.1 uses QIIME2 2021.2, classifiers can be found at https://docs.qiime2.org/2021.2/data-resources/#silva-16s-18s-rrna (click the red button "Show me the content on this page"!). Probably you are looking for `https://data.qiime2.org/2021.2/common/gg-13-8-99-nb-classifier.qza`?

Alternatively, the greengenes database is really small and you should be able to use the build-in database with `--qiime_ref_taxonomy "greengenes85"` (which means it will train the classifier, which you probably wanted to prevent).

Let me know if that solves your problem!

**Comment by DooYal** [comment]
> Hi there!
> 
> The database you specified via `--classifier './gg-13-8-99-nb-classifier.qza'` was made for (and most likely with) an older version of QIIME2 (and an older version of scikit-learn) than this pipeline uses.
> 
> Ampliseq version 2.1.1 uses QIIME2 2021.2, classifiers can be found at https://docs.qiime2.org/2021.2/data-resources/#silva-16s-18s-rrna (click the red button "Show me the content on this page"!). Probably you are looking for `https://data.qiime2.org/2021.2/common/gg-13-8-99-nb-classifier.qza`?
> 
> Alternatively, the greengenes database is really small and you should be able to use the build-in database with `--qiime_ref_taxonomy "greengenes85"` (which means it will train the classifier, which you probably wanted to prevent).
> 
> Let me know if that solves your problem!

Thanks for the advice. I found it worked when setting `--classifier "./gg-13-8-99-515-806-nb-classifier.qza"` and the build-in database with `--qiime_ref_taxonomy "silva=138" ` .

**Comment by d4straub** [comment]
> Thanks for the advice. I found it worked when setting --classifier "./gg-13-8-99-515-806-nb-classifier.qza" and the build-in database with --qiime_ref_taxonomy "silva=138" .

Uh that seems not a good idea. What you did is to specify a trained classifier of the `Greengenes` database with `--classifier` and a file to train a `SILVA` classifier with `--qiime_ref_taxonomy`, which are both intended for QIIME2. I actually never tried that and curious what happened. I guess the `--classifier` was taken over `--qiime_ref_taxonomy`, or the other way around? I think I should prevent such parameter combinations.

**Comment by DooYal** [comment]
> > Thanks for the advice. I found it worked when setting --classifier "./gg-13-8-99-515-806-nb-classifier.qza" and the build-in database with --qiime_ref_taxonomy "silva=138" .
> 
> Uh that seems not a good idea. What you did is to specify a trained classifier of the `Greengenes` database with `--classifier` _and_ a file to train a `SILVA` classifier with `--qiime_ref_taxonomy`, which are _both_ intended for QIIME2. I actually never tried that and curious what happened. I guess the `--classifier` was taken over `--qiime_ref_taxonomy`, or the other way around? I think I should prevent such parameter combinations by adding a parameter sanity check for those two.

I also think `--qiime_ref_taxonomy "silva=138" --classifier "./gg-13-8-99-515-806-nb-classifier.qza"` is not a good group, however, when I set `--qiime_ref_taxonomy "silva=138" --classifier "./silva-138-99-515-806-nb-classifier.qza"` , it did not work and the bug report also listed that `The scikit-learn version (0.21.2) used to generate this artifact does not match the current version of scikit-learn installed (0.23.1). Please retrain your classifier for your current deployment to prevent data-corruption errors.
See above for debug info.` 
So I was very confused.

**Comment by d4straub** [comment]
In that case, `silva-138-99-515-806-nb-classifier.qza` was obviously again the wrong choice, i.e. it was trained with a different version of scikit-learn & QIIME2 than the pipeline uses, as explained above.

Only one of the parameters `--qiime_ref_taxonomy`,`--classifier` should be used, _not_ both. Please try with `--qiime_ref_taxonomy "silva=138"` but omit `--classifier "./gg-13-8-99-515-806-nb-classifier.qza"` (i.e. no `--classifier`!). If you have run the pipeline before, add a `-resume` so that only parts of the pipeline that differ based on the changed input will be run again. This was you can make sure to actually have results based on the SILVA database with `--qiime_ref_taxonomy "silva=138"`. If you prefer Greengeenes (which I would _not_ recommend because it is outdated), omit `--qiime_ref_taxonomy`. 

However, by default, also  `--dada_ref_taxonomy` is set to `"silva=138"` and DADA2 classification are taken over QIIME2 classification results (`--qiime_ref_taxonomy` is by default `false`). So if you want to have in the end 
(1) QIIME2 classified amplicon sequences based on the pre-trained classifier, use `--classifier "./gg-13-8-99-515-806-nb-classifier.qza" --dada_ref_taxonomy false -resume`, 
(2) QIIME2 classified amplicon sequences based on the database (i.e. the classifier will be trained) use `--qiime_ref_taxonomy "silva=138" --dada_ref_taxonomy false -resume`, or 
(3) DADA2 classified amplicon sequences use `--dada_ref_taxonomy "silva=138" -resume` (or just `-resume`, because `--dada_ref_taxonomy "silva=138"`  is default!).
The last option is default, because it is easier on computation (less RAM, faster), but the outcomes are not properly benchmarked, so I am not sure which one (QIIME2 or DADA2 classification) performs better.
I hope I made clear how this works.

**Comment by DooYal** [comment]
> In that case, `silva-138-99-515-806-nb-classifier.qza` was obviously again the wrong choice, i.e. it was trained with a different version of scikit-learn & QIIME2 than the pipeline uses, as explained above.
> 
> Only one of the parameters `--qiime_ref_taxonomy`,`--classifier` should be used, _not_ both. Please try with `--qiime_ref_taxonomy "silva=138"` but omit `--classifier "./gg-13-8-99-515-806-nb-classifier.qza"` (i.e. no `--classifier`!). If you have run the pipeline before, add a `-resume` so that only parts of the pipeline that differ based on the changed input will be run again. This was you can make sure to actually have results based on the SILVA database with `--qiime_ref_taxonomy "silva=138"`. If you prefer Greengeenes (which I would _not_ recommend because it is outdated), omit `--qiime_ref_taxonomy`.
> 
> However, by default, also `--dada_ref_taxonomy` is set to `"silva=138"` and DADA2 classification are taken over QIIME2 classification results (`--qiime_ref_taxonomy` is by default `false`). So if you want to have in the end (1) QIIME2 classified amplicon sequences based on the pre-trained classifier, use `--classifier "./gg-13-8-99-515-806-nb-classifier.qza" --dada_ref_taxonomy false -resume`, (2) QIIME2 classified amplicon sequences based on the database (i.e. the classifier will be trained) use `--qiime_ref_taxonomy "silva=138" --dada_ref_taxonomy false -resume`, or (3) DADA2 classified amplicon sequences use `--dada_ref_taxonomy "silva=138" -resume` (or just `-resume`, because `--dada_ref_taxonomy "silva=138"` is default!). The last option is default, because it is easier on computation (less RAM, faster), but the outcomes are not properly benchmarked, so I am not sure which one (QIIME2 or DADA2 classification) performs better. I hope I made clear how this works.

Thanks for the opinion. I think the parameter (choice 1) `--classifier "./gg-13-8-99-515-806-nb-classifier.qza" --dada_ref_taxonomy false -resume` is suitable for my analysis.

**Comment by d4straub** [comment]
Let me know if that worked for you so that I (or you) can close this issue.

**Comment by DooYal** [comment]
OK, I will close the issue.
