### ISSUE TITLE
Taxonomy classification raises an ValueError for some datasets. This is a known but unsolved bug in QIIME2.

### ISSUE THREAD

**Issue by d4straub** [nf-core/ampliseq#39]
There is an value error when specific sequences are in a sample related to specific taxonomies of the classifier:
`ValueError: CategoricalMetadataColumn does not support strings with leading or trailing whitespace characters:`

As long as [this issue](https://github.com/qiime2/q2-types/issues/179) isnt solved in QIIME2, a way to analyze these data sets anyway will be implemented.

The idea is to modify the file with taxonomy strings, most likely hash tags in this file are causing this issue.

**Comment by apeltzer** [comment]
Should we have this in 1.0.1 or are you aiming for 1.1.0 ?

**Comment by d4straub** [comment]
should be solved
