### ISSUE TITLE
-test profile,singularity fails

### ISSUE THREAD

**Issue by agrier-wcm** [nf-core/ampliseq#391]
### Description of the bug

Running the test,singularity profile combination gives an error about failing to pull the singularity image for the very first process.  I tried with the `--singularity_pull_docker_container` parameter as well and got the same error.  Any feedback would be appreciated.

Cheers.

### Command used and terminal output

```console
nextflow run nf-core/ampliseq -profile test,singularity

Error executing process > 'NFCORE_AMPLISEQ:AMPLISEQ:METADATA_PAIRWISE (Metadata.tsv)'

Caused by:
  Failed to pull singularity image
  command: singularity pull  --name depot.galaxyproject.org-singularity-bioconductor-dada2-1.22.0--r41h399db7b_0.img.pulling.1646692250761 https://depot.galaxyproject.org/singularity/bioconductor-dada2:1.22.0--r41h399db7b_0 > /dev/null
  status : 255
  message:
    ERROR: pull is only supported for shub URIs
```

### System information

This is the first time I'm trying to run this pipeline on this machine, so it is pulling the latest version (2.2.0).  I'm using Nextflow 21.10.0 and Singularity version 2.4.2.

**Comment by agrier-wcm** [comment]
I tried it with some real data and different parameters and it fails in the same way, just with a different container:

```
nextflow run nf-core/ampliseq -profile singularity --input SampleSheet.tsv --FW_primer GTGYCAGCMGCCGCGGTAA --RV_primer GGACTACNVGGGTWTCTAAT --outdir ./test_results --dada_ref_taxonomy silva --cut_dada_ref_taxonomy --ignore_empty_input_files --ignore_failed_trimming --min_frequency 10

Error executing process > 'NFCORE_AMPLISEQ:AMPLISEQ:RENAME_RAW_DATA_FILES (C4_16S_01102022)'

Caused by:
  Failed to pull singularity image
  command: singularity pull  --name containers.biocontainers.pro-s3-SingImgsRepo-biocontainers-v1.2.0_cv1-biocontainers_v1.2.0_cv1.img.img.pulling.1646693790437 https://containers.biocontainers.pro/s3/SingImgsRepo/biocontainers/v1.2.0_cv1/biocontainers_v1.2.0_cv1.img > /dev/null
  status : 255
  message:
    ERROR: pull is only supported for shub URIs
```

Could it be that I'm using an older version of Singularity?  I've requested the sys admins update it.

**Comment by d4straub** [comment]
Hi there,
yes, that issue is not related to data (whether test or real) but seem related to singularity. Please report back here whether version 3.x singularity works for you.

**Comment by agrier-wcm** [comment]
Hi Daniel,

I updated to Singularity 3.7.0 and now it works like a charm.  I'll close the issue.  Thanks for your quick reply.
