### ISSUE TITLE
Add SH assignment for ITS sequences

### ISSUE THREAD

**Issue by jtangrot** [nf-core/ampliseq#392]
### Description of feature

We have been working on how to assign a UNITE Species Hypothesis (SH) to our fungal ITS sequences and come up with a procedure to, in short, match sequences to the database with vsearch and, in case of a good enough match, use the SH of the matching sequence, and replace the taxonomy with that of the SH. Now, we would like to add this to ampliseq, e.g. by adding an option --addsh, as a complement to assignSpecies.

**Comment by d4straub** [comment]
Apologies, I am not familiar with the term _species hypothesis_. A quick google search was not very enlightening. Is that related to https://github.com/nf-core/ampliseq/issues/387? Is it a different kind of database? In any case, it does seem interesting to have it in ampliseq.
However, I would advice to not replace any previous taxonomic classification results but rather add additional files or columns to existing classifications.

**Comment by jtangrot** [comment]
> Apologies, I am not familiar with the term species hypothesis. A quick google search was not very enlightening. Is that related to https://github.com/nf-core/ampliseq/issues/387? Is it a different kind of database?

Some more info on SHs can be found here: https://unite.ut.ee/faq.php
It's not directly related to #387, however it might be possible to extract information on SHs from that too if using the Unite databases. All sequences in the Unite databases are assigned to a SH, but it takes some effort to find which SH at a given sequence identity level, and to extract the taxonomy assignment for that SH.

>  In any case, it does seem interesting to have it in ampliseq.

Great, then I'll go ahead and prepare a PR

> However, I would advice to not replace any previous taxonomic classification results but rather add additional files or columns to existing classifications.

I was planning to create a new file, and replace the taxonomic classification in that file (for entries where the SH can be assigned).

**Comment by d4straub** [comment]
Sounds good!
I hope to have https://github.com/nf-core/ampliseq/pull/385 soon merged that fixes all current linting problems, that would aid further development & review ;)

**Comment by jtangrot** [comment]
Solved in #434
