### ISSUE TITLE
Consider rename

### ISSUE THREAD

**Issue by apeltzer** [nf-core/ampliseq#42]
We should probably get rid of the `rrna-` prefix and just do `ampliseq`. 

https://nf-co.re/guidelines#workflow-name

**Comment by d4straub** [comment]
`ampliseq` is fine, because when using an appropriate database any amplicon could be investigated.

**Comment by apeltzer** [comment]
Ok renamed to `ampliseq`, Docker cloud builds now and I will rename every occurence of "rrna-ampliseq" to `ampliseq` then too
