### ISSUE TITLE
DADA2_QUALITY get an error and termimated

### ISSUE THREAD

**Issue by Karma0alpha** [nf-core/ampliseq#422]
### Description of the bug

I found that DADA2 QUALITY in the latest version calls the step of the ampliseq/tree/master/modules/local)/dada2_quality.nf script, reporting an error and terminating the entire pipeline.
Error in if (NROW(x) == 0L) stop("no rows to aggregate") :
  missing value where TRUE/FALSE needed
In addition: Warning message:
In attributes(.Data) <- c(attributes(.Data), attrib) :
  NAs introduced by coercion to integer range
But in the ever version of DADA2 QUALITY,  use dada_quality.r "FW_qual_stats" 5e+06 could finish this step and no error reported.

**Comment by d4straub** [comment]
Hi there, I am not completely sure what you are saying, could you please answer these questions:
- what nf-core/ampliseq version works for you (please write the release number)?
- what nf-core/ampliseq version does not work for you (please write the release number)?
- what is the complete command that you used to start the pipeline?
- number of samples? 
- sample type (illumina SE/PE, pacbio, ...)? 
- approximate total reads of input data?

**Comment by Karma0alpha** [comment]
Sorry for unclear description.

**Comment by Karma0alpha** [comment]
I'm checking the DADA2 quality step, the error occurred in this part:
df <- data.frame(
+         Count = aggregate(data$Count, list(data$Cycle), sum),
+         Median = aggregate(rep(data$Score, data$Count), list(rep(data$Cycle, data$Count)), median)[2]
+     )
I tried running a fraction of the total 398 samples, say 100, and it did, so I'm guessing how many samples fail this step due to low data quality or low number of reads?
Any suggestion to trace this issue?

**Comment by d4straub** [comment]
> Version 21.04.3 worked;
Version 22.04.0 report an error in DADA2 quality step and terminated the pipeline;

uh, ok, that are nextflow versions, not nf-core/ampliseq versions?! Could you please confirm that running
1. `NXF_VER=21.04.3 nextflow run nf-core/ampliseq  -r 2.3.1 [... your parameters] -resume` works while
2. `NXF_VER=22.04.0 nextflow run nf-core/ampliseq  -r 2.3.1 [... your parameters] -resume` fails?

**Comment by Karma0alpha** [comment]
Yes, I found I ever successfully run the pipeline in version 2.1.0, now the failed running version is 2.3.1, I'll test the version 2.1.0 again.

**Comment by d4straub** [comment]
Could you test
`nextflow run nf-core/ampliseq -r 2.3.1 [... your parameters] -resume -c dada_quality.config`

where `dada_quality.config` contains:

```
process {
    withName: DADA2_QUALITY {
        ext.args = ", n = 5e+04, aggregate = TRUE"
    }
}
```
This decreases the reads sampled per file and thereby might make the pipeline run appropriately.
That did help already other people.

Note to myself:
- add parameter `--skip_dada_quality` to be able to skip that step, link with whether `--trunclenf` and `--trunclenr` are set.
- change default settings of `DADA2_QUALITY` to `n = 5e+04` to accommodate deep sequenced samples.

**Comment by d4straub** [comment]
In the dev branch (i.e. new release sometime soon-ish) I have added a new parameter `--skip_dada_quality` and changed plotQualityProfile settings so that `DADA2_QUALITY` will be hopefully robuster.

Let me know if you continue to have that issue (preferentially with more details).

**Comment by d4straub** [comment]
I hope version 2.3.2 fixes that error, please test it in case you are interested.
