### ISSUE TITLE
DADA2_MERGE changes sample ID

### ISSUE THREAD

**Issue by phuongdoand** [nf-core/ampliseq#423]
### Description of the bug

Hi, thank you very much for a complete pipeline for running 16S data.

I found a problem with the DADA2_MERGE process that affect the downstream analysis of QIIME2 while running the `nf-core/ampliseq=2.2.0` version.

I have several samples with names containing the dash `-` character (e.g. MS22001-MOCK-1_R1.fastq.gz). Therefore, my metadata file looks like this.

![image](https://user-images.githubusercontent.com/43783123/166631831-21eb69df-7103-4d08-a764-727d4396b396.png)

The problem happens in the dada2_merge.nf file, line [50](https://github.com/nf-core/ampliseq/blob/306ad5df8f0a3b7cd033d040ddd440c09eb9a361/modules/local/dada2_merge.nf#L50), when transforming the data matrix to a data frame, the `check.names=FALSE` parameter was not used; results in changing the column name from `MS22001-MOCK-1` to `MS22001.MOCK.1`.  This causes problems for the QIIME2 visualization process when it requires the sample ID to be the same as the one provided in the metadata.

Fyi, I used the `nf-core/ampliseq=1.2.0` previously and everything goes smoothly; thus, reconfirm my theory that the error is caused by changing DADA2 to R.

I believe that QIIME2 metadata only allows dash `-` and dot `.` but your pipeline does not allow dot `.`; thus, it is difficult for me to change the samples' names. Could this be changed in the future?

### Command used and terminal output

```console
# COMMAND USED:

NXF_VER=21.10.3 nextflow run nf-core/ampliseq -r 2.2.0 -profile singularity --input "data" --metadata "metadata.tsv" --FW_primer CCTACGGGNGGCWGCAG --RV_primer GACTACHVGGGTATCTAATCC --extension '/*R{1,2}.fastq.gz' --picrust --outdir results --skip_ancom --dada_ref_taxonomy false --classifier /mnt/NFS/pisces/phuong/16S_Illu/classifiers/SILVA_132/classifier_silva_132_99_16S_V3.V4.qza --qiime_tax_agglom_max 7 -resume --rm -with-trace -w work

# ERROR OUTPUT:

Caused by:
  Process `NFCORE_AMPLISEQ:AMPLISEQ:QIIME2_BARPLOT (1)` terminated with an error exit status (1)

Command executed:

  export XDG_CONFIG_HOME="${PWD}/HOME"

  qiime taxa barplot          --i-table filtered-table.qza          --i-taxonomy taxonomy.qza          --m-metadata-file metadata.tsv          --o-visualization taxa-bar-plots.qzv          --verbose
  qiime tools export --input-path taxa-bar-plots.qzv          --output-path barplot

  cat <<-END_VERSIONS > versions.yml
  "NFCORE_AMPLISEQ:AMPLISEQ:QIIME2_BARPLOT":
      qiime2: $( qiime --version | sed -e "s/q2cli version //g" | tr -d '`' | sed -e "s/Run qiime info for more version details.//g" )
  END_VERSIONS

Command exit status:
  1

Command output:
  (empty)

Command error:
  QIIME is caching your current deployment for improved performance. This may take a few moments and should only happen once per deployment.
  Traceback (most recent call last):
    File "/opt/conda/envs/qiime2-2021.8/lib/python3.8/site-packages/q2cli/commands.py", line 329, in __call__
      results = action(**arguments)
    File "<decorator-gen-140>", line 2, in barplot
    File "/opt/conda/envs/qiime2-2021.8/lib/python3.8/site-packages/qiime2/sdk/action.py", line 245, in bound_callable
      outputs = self._callable_executor_(scope, callable_args,
    File "/opt/conda/envs/qiime2-2021.8/lib/python3.8/site-packages/qiime2/sdk/action.py", line 453, in _callable_executor_
      ret_val = self._callable(output_dir=temp_dir, **view_args)
    File "/opt/conda/envs/qiime2-2021.8/lib/python3.8/site-packages/q2_taxa/_visualizer.py", line 35, in barplot
      raise ValueError('Sample IDs found in the table are missing in the '
  ValueError: Sample IDs found in the table are missing in the metadata: {'MST21001.MOCK.original', 'MS20189.MOCK', 'MS20079.MOCK', 'MS20196.re.test.MOCK', 'Mock202105.MOCK', 'MS20284.MOCK.Nov', 'MS20215.MOCK', 'MS20313.MOCK', 'MST21001.MOCK.frameshift'}.

Plugin error from taxa:

    Sample IDs found in the table are missing in the metadata: {'MST21001.MOCK.original', 'MS20189.MOCK', 'MS20079.MOCK', 'MS20196.re.test.MOCK', 'Mock202105.MOCK', 'MS20284.MOCK.Nov', 'MS20215.MOCK', 'MS20313.MOCK', 'MST21001.MOCK.frameshift'}
```

### Relevant files

```
Nextflow log file
```

[nextflow.log.zip](https://github.com/nf-core/ampliseq/files/8617873/nextflow.log.zip)

### System information

- Nextflow version: **21.10.3**
- Hardware: **HPC**
- Executor: **local**
- Container engine: **Singularity**
- OS: **CentOS**
- Version of nf-core/ampliseq: **2.2.0**
- Sample type: **Illumina**

**Comment by d4straub** [comment]
Thanks for this comprehensive and clear report!
Yes, indeed, the change to R seems the problem here.
And you are right, sample IDs should either be more flexible or at least checked for validity. I'll test your suggestion when I find the time.

**Comment by phuongdoand** [comment]
Thank you for the prompt reply. Looking forward to the new version. 
In the meantime, I will change the code to make it works.

**Comment by d4straub** [comment]
You could actually also omit the dash in your sample names in the metadata file and use the samplesheet input to define matching sample IDs, see https://nf-co.re/ampliseq/2.3.1/usage#samplesheet-input
Than you would not need to modify the code (but create a samplesheet...).

**Comment by phuongdoand** [comment]
That sounds like a good idea, I will definitely give it a try.

**Comment by d4straub** [comment]
Ok, I added your suggestion to the code in the `dev` branch. This will be in the next release.
Thanks a lot!

**Comment by phuongdoand** [comment]
Thanks for the quick fix, looking forward to the next release.
