### ISSUE TITLE
Ampliseq Error

### ISSUE THREAD

**Issue by avinash-ngc** [nf-core/ampliseq#424]
### Description of the bug

I encountered an error while running the pipeline at the Denoising and Remove Chimera step. The error message isn't clear enough. My fastq files seem to be ok as well. I would be really obliged if you could have a look into this issue. I am also attaching the error log and quality profile of my data.

Thanks
[ampliseq_error.txt](https://github.com/nf-core/ampliseq/files/8618965/ampliseq_error.txt)
![Capture](https://user-images.githubusercontent.com/85724635/166651211-507acc09-7800-485c-a64e-d335a87886b2.PNG)

### Command used and terminal output

```console
Error executing process > 'NFCORE_AMPLISEQ:AMPLISEQ:DADA2_RMCHIMERA (1)'

Caused by:
  Process `NFCORE_AMPLISEQ:AMPLISEQ:DADA2_RMCHIMERA (1)` terminated with an error exit status (1)

Command executed:

  #!/usr/bin/env Rscript
  suppressPackageStartupMessages(library(dada2))

  seqtab = readRDS("1.seqtab.rds")

  #remove chimera
  seqtab.nochim <- removeBimeraDenovo(seqtab, method="consensus", minSampleFraction = 0.9, ignoreNNegatives = 1, minFoldParentOverAbundance = 2, minParentAbundance = 8, allowOneOff = FALSE, minOneOffParentDistance = 4, maxShift = 16, multithread=6, verbose=TRUE)
  if ( 1 == 1 ) { rownames(seqtab.nochim) <- "AIG93" }
  saveRDS(seqtab.nochim,"1.ASVtable.rds")

  write.table('removeBimeraDenovo       method="consensus", minSampleFraction = 0.9, ignoreNNegatives = 1, minFoldParentOverAbundance = 2, minParentAbundance = 8, allowOneOff = FALSE, minOneOffParentDistance = 4, maxShift = 16', file = "removeBimeraDenovo.args.txt", row.names = FALSE, col.names = FALSE, quote = FALSE, na = '')
  writeLines(c("\"NFCORE_AMPLISEQ:AMPLISEQ:DADA2_RMCHIMERA\":", paste0("    R: ", paste0(R.Version()[c("major","minor")], collapse = ".")),paste0("    dada2: ", packageVersion("dada2")) ), "versions.yml")

Command exit status:
  1

Command output:
  (empty)

Command error:
  Error in isBimeraDenovoTable(unqs[[i]], ..., verbose = verbose) :
    Input must be a valid sequence table.
  Calls: removeBimeraDenovo -> isBimeraDenovoTable
  Execution halted

Work dir:
  /data/NGC_Data/Analysis/External_Projects/2022/AIG-93-94/93/93/work/84/824a1fd58e467ddfe13c0d6a34f070

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`
```

### Relevant files

[ampliseq_error.txt](https://github.com/nf-core/ampliseq/files/8618970/ampliseq_error.txt)
![Capture](https://user-images.githubusercontent.com/85724635/166651313-0cdbbcc7-35f1-44b9-8ce4-11a059ea22cf.PNG)

**Comment by phuongdoand** [comment]
Hi Avinash, I think this problem is not caused by the pipeline itself but rather because of the data. Have you checked the `1.seqtab.rds` returned by the `DADA2_DENOISE` process? 
There could be a possibility that all the reads have been filtered out so the input to `DADA2_RMCHIMERA` is an empty file.

**Comment by d4straub** [comment]
I totally agree.

> Command error:
  Error in isBimeraDenovoTable(unqs[[i]], ..., verbose = verbose) :
    Input must be a valid sequence table.
  Calls: removeBimeraDenovo -> isBimeraDenovoTable
  Execution halted

hints that the table is not valid, i.e. most likely empty.
That stems probably from loosing sequences on the way. Check all steps, i.e. fastqc, cutadapt and then also intermediate files like [phuongdoand](https://github.com/phuongdoand) suggested.
I'll close that for now, but please open another issue if you encounter more problems.
