### ISSUE TITLE
dada2 code optimization for binned quality scores from NovaSeq Data

### ISSUE THREAD

**Issue by lokeshbio** [nf-core/ampliseq#425]
### Description of feature

Hi,

As discussed in slack, it would be great to have the option of having `--illumina_novaseq` that does the error model calculations optimized for the binned qulaity score ouputs that come from NovaSeq data! The solution for this problem in dada2 analysis is described in the lin below:
https://github.com/benjjneb/dada2/issues/791#issuecomment-941366623

Cheers
Lokesh

**Comment by d4straub** [comment]
Thats in dev and will be in the next release.
