### ISSUE TITLE
Adapt ampliseq SBDI output format to changes in ASV portal

### ISSUE THREAD

**Issue by pragermh** [nf-core/ampliseq#436]
@erikrikarddaniel,

I have made a few changes in the ASV database that may require adaptation of ampliseq output:

1) _materialSampleID_ should, if supplied, be a _link to_ an archived sample, typically to an ENA biosample, e.g.: https://www.ebi.ac.uk/ena/browser/view/SAMEA3724536
2) _associatedSequences_ should be a link to the corresponding ENA run page, where you can access the raw read files, e.g.:  https://www.ebi.ac.uk/ena/browser/view/ERR1202039. This field has also been moved from the _asv-table_ tab/file to the _event_ tab/file.
3) I have also implemented flagging/filtering of ASVs based on whether these are actually predicted to be sequences of the targeted gene, e.g. 16S/18S rRNA. At the moment, my R script for data processing takes a tsv file that lists the md5 checksums of ASVs to be flagged as 'non-target', e.g:

f087e887fd14b5152210b35aa3cdc4e9
f0c7831a757569bab9665bb61b6bf4fd
...
...and adds the following fields to tab/file annotation, based on this list (and some description of the criteria):

| annotation_target | target_criteria                                             | target_prediction |
|-------------------|-----------------------------------------|-------------------|
| 16S rRNA               | Assigned kingdom OR barrnap-positive  | TRUE                      |
| 16S rRNA               | Assigned kingdom OR barrnap-positive  | TRUE                      |
| 16S rRNA               | Assigned kingdom OR barrnap-positive  | FALSE                    |

These fields are then used for dynamic filtering of ASVs from search options and results etc. I guess some of the above could be performed by ampliseq, but we can discuss this when you have time.

Thanks

**Comment by erikrikarddaniel** [comment]
A few other things to do:
* Make sure we have at least one test case for the export for all taxonomy databases
* SH to `scientific_name`, rank: "Unranked"
* Make sure `specificEpithet` is only that for PR2
* Set `annotation_confidence` to 0 when missing
* Add url to `reference_db` (might require new config file field)
* `sop` link to Ampliseq
* Use `taxon_remarks` for domain, e.g. "Domain = 'Eukaryota'"

**Comment by pragermh** [comment]
It possible, also add any 'random-number seed' values used, to ensure reproducibility.

**Comment by pragermh** [comment]
Given that positive Barrnap predictions for different domains (e.g. rrna.arc, rrna.bac, rrna.euk) are non-mutually exclusive, it would be good if SBDI output could reflect some evaluation of e-values for competing predictions, e.g. 'rrna.euk.gff' should only include an ASV for which 'euk' is the best prediction.

**Comment by d4straub** [comment]
> Given that positive Barrnap predictions for different domains (e.g. rrna.arc, rrna.bac, rrna.euk) are non-mutually exclusive, it would be good if SBDI output could reflect some evaluation of e-values for competing predictions, e.g. 'rrna.euk.gff' should only include an ASV for which 'euk' is the best prediction.

I agree that a file that lists best e-values or such for barrnap outcomes would be great! However, I disagree to change barrnap output (e.g. rrna.euk.gff) directly, but rather produce another file.
