### ISSUE TITLE
Considering the parameter metadata_category when setting ch_metadata_pairwise

### ISSUE THREAD

**Issue by asafpr** [nf-core/ampliseq#447]
### Description of the bug

I think that `ch_metacolumn_pairwise` should be a subset of `ch_metacolumn_all`. If the parameter `metadata_category` is specified then it might not always be the case since the module `metadata_pairwise` doesn't take it into consideration.

**Comment by d4straub** [comment]
That was much harder than expected, I had to touch code from the ancient beginning of ampliseq.

**Comment by d4straub** [comment]
Ok, thats in dev branch and will be part of the next release!
