### ISSUE TITLE
Implement post-dada2 amplicon length filtering

### ISSUE THREAD

**Issue by tjcreedy** [nf-core/ampliseq#449]
### Description of feature

Currently ampliseq only allows filtering of input read lengths, but there is no way (that I've found) to specify a target range of lengths for the amplicons post merging. Working with COX1, we can have a strict length expectation, and know that an amplicon with even one base variation from this is more likely to contain errors, and anything substantially shorter or longer is definitely not of interest. 

It seems like this would be straightforward to implement in the R code in `dada2_denoising.nf`, by including the line 
`seqtab <- seqtab[,nchar(colnames(seqtab)) %in% <minampliconlen>:<maxampliconlen>])` after the current lines 47 and 70, however of course I'm not familiar enough with nextflow to know how complex it might be to implement and pass through the `<*ampliconlen>` parameters. 

ETA: we imagine this would likely be useful for non-COX1 amplicons as well, of course with less strict length ranges. 

Thanks!

**Comment by tjcreedy** [comment]
That makes a lot of sense, I was just thinking about ease of implementation but I completely agree having this between denoising/barrnap and before classification is the most appropriate location. I see length filtering (and translation filtering*) as doing for protein coding genes what ITSx and barrnap are doing for ITS and SSU - it just gets to be much more simple because the a priori assumptions about PCGs are so much more strict.

(*filtering out stops in translation; low-impact, filters <1% after denoising and length filtering, and not applicable to most markers but could write (yet another) feature request and contribute python code if you'd be interested in implementing this at all.)

**Comment by d4straub** [comment]
Yes, I think adding yet another filter for translation is a good idea, especially since COI will be added in any case, as learned in https://github.com/nf-core/ampliseq/issues/427, and it would be good to discuss with these persons as well.

**Comment by d4straub** [comment]
Hi @tjcreedy, could you have a look at the above linked PR? Let me know if you have any comments/suggestions.

**Comment by tjcreedy** [comment]
Hi @d4straub I've run that branch on my test data and it comes out as expected, thank you! I assume the file `asv_length_filter/ASV_seqs.len.fasta` would be the input to the taxonomic classification steps? The MIDORI database (understandably) isn't implemented in that branch so couldn't check that with my data.

**Comment by d4straub** [comment]
> I assume the file asv_length_filter/ASV_seqs.len.fasta would be the input to the taxonomic classification steps?

correct!

**Comment by d4straub** [comment]
Alright, the addition is merged to dev and will be in the next release.
