### ISSUE TITLE
cutadapt with "null" for primers

### ISSUE THREAD

**Issue by nick-youngblut** [nf-core/ampliseq#462]
### Description of the bug

Error:

```
Command error:
  WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
  Run "cutadapt --help" to see command-line options.
  See https://cutadapt.readthedocs.io/ for full documentation.
  
  cutadapt: error: Character 'L' in adapter sequence 'NTLL' is not a valid IUPAC code. Use only characters ABCDGHKMNRSTUVWXY.
```

This is because the command is:

```
#!/bin/bash -euo pipefail
cutadapt \
    --cores 6 \
    --minimum-length 1 -O 3 -e 0.1 -g null -G null --discard-untrimmed \
    -o D10-1.trimmed_1.trim.fastq.gz -p D10-1.trimmed_2.trim.fastq.gz \
    D10-1_1.fastq.gz D10-1_2.fastq.gz \
    > D10-1.trimmed.cutadapt.log
cat <<-END_VERSIONS > versions.yml
"CUTADAPT_WORKFLOW:CUTADAPT_BASIC":
    cutadapt: $(cutadapt --version)
END_VERSIONS
```

It appears that the pipeline will use `null` for the primer sequences, which results in the misleading error message.

I'm providing a config file `-config` that includes the primers. Example:

```
params {
    FW_primer = "GTGYCAGCMGCCGCGGTAA"
    RV_primer = "GGACTACNVGGGTWTCTAAT"
}
```

...but it appears that the pipeline is converting the primer sequences to `null`

### System information

Nextflow version: 22.04.0.5697
ampliseq version: 2.3.2
profile: docker

**Comment by erikrikarddaniel** [comment]
I think this might be because you specified primers in a `nextflow.config` file. Put them in a yaml file looking like below, that you supply with `-params-file` to nextflow.
```
FW_primer: GTGYCAGCMGCCGCGGTAA
RV_primer: GGACTACNVGGGTWTCTAAT
```
The documentation is maybe not up to date...

**Comment by nick-youngblut** [comment]
Can I just keep them in my secondary config file, as described above (using `-config /path/to/run-specific/config/`)? The other params that I set in my secondary config file seem to work fine (e.g., `outdir = "/path/to/output/dir/"`).

**Comment by erikrikarddaniel** [comment]
I've gotten all kinds of weird errors and error messages after putting parameters in config files, so I strongly advice you to place all in a yaml file instead and use the config file(s) for other purposes like adjusting resources for modules.

**Comment by d4straub** [comment]
I agree with the assessment. Its the config file. nf-core pipelines work with many configs and those get resolved in a sequenctial manner, leading to problems when one config that sets params is loaded after the config that requires them. It is documented in the nextflow docs though, albeit a little hidden: https://www.nextflow.io/docs/latest/config.html#configuration-file
I'd always recommend using the command line parameters if possible, or alternatively `-params-file`.

> The documentation is maybe not up to date...

Really? Do we specify that somewhere? If yes, I'll change it asap.

**Comment by erikrikarddaniel** [comment]
As I mentioned on Slack, @d4straub, I'm not sure the docs are up to date...

**Comment by nick-youngblut** [comment]
>I've gotten all kinds of weird errors and error messages after putting parameters in config files, so I strongly advice you to place all in a yaml file instead and use the config file(s) for other purposes like adjusting resources for modules.

OK, I'll switch to a yaml. It would help to have more docs on using a yaml with `-params-file`. I couldn't find an example in any nf-core repos (or any that I checked at https://github.com/nextflow-io/awesome-nextflow).

**Comment by erikrikarddaniel** [comment]
We're discussing the documentation issue right now, so stay tuned...

**Comment by d4straub** [comment]
That issue with configs/yaml is already quite old, and nicely explained in https://github.com/nf-core/viralrecon/issues/283#issuecomment-1046237471
I'm going to add a paragraph to https://nf-co.re/ampliseq/2.3.2/usage#running-the-pipeline and mention the issue again to people maintaining the nf-core website.

**Comment by nick-youngblut** [comment]
>I'm going to add a paragraph to https://nf-co.re/ampliseq/2.3.2/usage#running-the-pipeline and mention the issue again to people maintaining the nf-core website.

Is this a general issue with Nextflow (DSL2)? If so, then should https://www.nextflow.io/docs/latest/index.html be updated?

**Comment by erikrikarddaniel** [comment]
> > I'm going to add a paragraph to https://nf-co.re/ampliseq/2.3.2/usage#running-the-pipeline and mention the issue again to people maintaining the nf-core website.
> 
> Is this a general issue with Nextflow (DSL2)? If so, then should https://www.nextflow.io/docs/latest/index.html be updated?

No, I think it happens because of how config files in nf-core are parsed.

**Comment by d4straub** [comment]
> Is this a general issue with Nextflow (DSL2)? If so, then should https://www.nextflow.io/docs/latest/index.html be updated?

Yes, it is a general "feature" of nextflow, but I do not see where the docs are misleading (using a config with -c and specifiying params), but I might just not have come across it. I agree though that the nextflow docs aren't flawless and this was brought up a few times already... Also, not sure its DSL2 only, its nextflow in general.

> No, I think it happens because of how config files in nf-core are parsed.

Imho that isnt completely correct. Configs are not parsed by nf-core, but nextflow. When pipelines use no or simple config file(s), using another config file with params _can_ be fine (but afaik was never the correct way), but when params are called in configs (as in nf-core pipelines, but not specific to nf-core), than using -c with params will break stuff.

This here is the problematic part: https://github.com/nf-core/ampliseq/blob/aed35e5b4bad907ed2bdf6587efb82ad2578e6b1/conf/modules.config#L51-L60, which is loaded after https://github.com/nf-core/ampliseq/blob/aed35e5b4bad907ed2bdf6587efb82ad2578e6b1/nextflow.config#L17-L18 and _afterwards_ the config provided by -c and therefore primers will be "null".

**Comment by d4straub** [comment]
Hi @nick-youngblut ,

thanks again for bringing this up. I added a paragraph to the pipelines usage documentation, explaining -params-file and its yaml format: https://github.com/nf-core/ampliseq/blob/3f89f4981dd122a06889e9c9a4820f30e9bceec5/docs/usage.md?plain=1#L68-L87 currently in the dev branch and will be in the next release.

I realize that this doesn't improve the general nextflow documentation, but seems at least a starting point.

**Comment by nick-youngblut** [comment]
Thanks @d4straub for updating the usage docs! 🎉

**Comment by d4straub** [comment]
Since this is resolved for the ampliseq repo, I close this issue now.
