### ISSUE TITLE
Enhancement: more quality control options

### ISSUE THREAD

**Issue by yanxianl** [nf-core/ampliseq#48]
Hi Alex,

Thank you for developing the next flow pipeline to do fully reproducible analysis of 16S rRNA amplicon data.

I have some new feature requests:

1. Enable filtering singletons and low prevalent features (only present in one sample) from the feature table. If samples were denoised on a per sample basis, filtering singletons is probably a good option as explained by the DADA2 developers [here](https://forum.qiime2.org/t/singletons-and-diversity-richness-indices/2971/9). Filtering low-prevalent features can also further reduce false sequence variants as suggested in the [QIIME2 forum](https://forum.qiime2.org/t/i-am-in-a-filter-features-dellima/6651/13).

2. Add quality control options. As part of the quality control, negative (blank extraction/library) and positive (mock) controls are often processed together with the samples. Therefore, allowing input of the mock composition will help to evaluate the reliability of the whole pipeline, which can be implemented by the [q2-quality-control](https://docs.qiime2.org/2018.11/plugins/available/quality-control/) plugin. For the negative control, the feature table with taxonomy can be generated and exported. Users will then need to supply a tsv file containing the featureIDs of contaminant sequences for the filtering in the next flow pipeline. Alternatively, users can provide a "Sample_DNA_concentraion.tsv" file, which can be used to identify the contaminant sequences by tools like the [decontam](https://github.com/benjjneb/decontam) package.

Regards,
Yanxian

**Comment by apeltzer** [comment]
Hi Yanxian!

Could you open two separate issues for this to discuss this further? 

I'm happy about contributors and @d4straub who is the main person behind this project might as well be :-)

**Comment by yanxianl** [comment]
Hi Alex,

Sorry about that. I'll close this issue and open two separate new issues.

Cheers,
Yanxian

**Comment by apeltzer** [comment]
No need to be sorry, thanks for contributing :-)
