### ISSUE TITLE
No reads passed the filter. Please revisit your filtering parameters.

### ISSUE THREAD

**Issue by xkcococo** [nf-core/ampliseq#496]
Greetings,

I have paired 16s sequencing files, and I want to apply ampliseq to them. But I always have an error message 'No reads passed the filter. Please revisit your filtering parameters.'

First I tried to reduce my 'trunclenf' and 'trunclenr' to find appropriate values, but even I reduced them to 0, I still got this error message. 

Attached is my quality score and my error message.
[RV_qual_stats.pdf](https://github.com/nf-core/ampliseq/files/9861743/RV_qual_stats.pdf)
[FW_qual_stats.pdf](https://github.com/nf-core/ampliseq/files/9861745/FW_qual_stats.pdf)

`Command error:
  The filter removed all reads: 62-Plate-1-F02-C13M2-N702-S508_1.filt.fastq.gz and 62-Plate-1-F02-C13M2-N702-S508_2.filt.fastq.gz not written.
  Warning message:
  In filterAndTrim("62-Plate-1-F02-C13M2-N702-S508.trimmed_1.trim.fastq.gz",  :
    No reads passed the filter. Please revisit your filtering parameters.`

Could you help me to figure it out? Thank you very much!

**Comment by xkcococo** [comment]
Hi,

Thank you for your suggestions. I checked the quality score for the samples and I think it is no problem. I was wondering how can I find the folder 'filterAndTrim'?

I also have another question, is it possible to skip the samples if an error happens and then continue run the pipeline?

Thank you very much.

**Comment by d4straub** [comment]
>  I was wondering how can I find the folder 'filterAndTrim'?

in the directory `work`, see the full error message. If you do not know what I mean, you can copy paste the complete error message as shown on your terminal here and I might be able to point you in the right direction.

> I also have another question, is it possible to skip the samples if an error happens and then continue run the pipeline?

Certainly, but without knowing _why_ the sample fails, I wouldn't do it. Anyway, you can do this by ignoring the failing process, therefore any failed sample should simply be lost and ignored. For this, append to your nextflow command `-c ignore.config -resume` where `ignore.config` contains:
```
process {
    withName:DADA2_FILTNTRIM {
        errorStrategy = 'ignore'
    }
}
```

**One more thought:** Which pipeline version do you use? If you do use an older version the Fail-Safes might be not yet implemented the problem could be at any process before filterAndTrim/DADA2_FILTNTRIM.

**Comment by d4straub** [comment]
I am closing this due to long time no reply but please feel free to open another issue when coming across a problem.
