### ISSUE TITLE
How can I find the loaction of the image about docker?

### ISSUE THREAD

**Issue by luozhy88** [nf-core/ampliseq#497]
### Description of the bug

nextflow run nf-core/ampliseq -profile test 
I run nfcore/ampliseq,but I can not find the loaction of docker. how can I get the location?
I loaded the local docker image and couldn't find it.

**Comment by maxulysse** [comment]
Hi, there should be several Docker containers actually.
Can you try with that instead:
```
nextflow run nf-core/ampliseq -profile docker,test
```

**Comment by luozhy88** [comment]
yes,I run "nextflow run nf-core/ampliseq -profile docker,test  ".But I can not find the location of image.

**Comment by d4straub** [comment]
nf-core/ampliseq (as most up to date nf-core pipelines) uses one docker/singularity image or conda environment per process (i.e. many). Docker images can be viewed (at least on my linux system, I use singularity on our hpc) with `docker images`. Does that help?

**Comment by luozhy88** [comment]
Thanks. I get it.

**Comment by d4straub** [comment]
Glad to hear, can this issue than be closed?

**Comment by luozhy88** [comment]
yes
