### ISSUE TITLE
Enhancement: add quality control options

### ISSUE THREAD

**Issue by yanxianl** [nf-core/ampliseq#50]
Hi there,

Here's another new feature request: adding quality control options. 

As part of the quality control, negative (blank extraction/library) and positive (mock) controls are often processed together with the samples. Therefore, allowing input of the mock composition will help to evaluate the reliability of the whole pipeline (wet and dry lab), which can be implemented by the [q2-quality-control](https://docs.qiime2.org/2018.11/plugins/available/quality-control/) plugin. For the use of negative controls, the feature table with taxonomy can be generated and exported. Users will then need to supply a tsv file containing the featureIDs of contaminant sequences for the filtering in the next flow pipeline. Alternatively, users can provide a "Sample_DNA_concentraion.tsv" file, which can be used to identify the contaminant sequences by tools like the [decontam](https://github.com/benjjneb/decontam) package. The sample DNA is ideally measured via qPCR using universal primers targetting 16s rRNA gene, which provides accurate quantification of bacterial DNA from host-associated samples.

Cheers,
Yanxian

**Comment by d4straub** [comment]
Hi,

I agree that would be a desirable addition.
Guidelines for q2-quality-control describe a workflow for positive controls [here](https://docs.qiime2.org/2018.11/tutorials/quality-control).
Negative controls might be even more important and covered by decontam.

I have to admit that's not my highest priority, if you would like to have it done soonish, you might want to contribute.

Best wishes

**Comment by d4straub** [comment]
I won't have time for this in the foreseeable future, but it remains interesting. If anyone wants to do a pull request for that I would be happy to test it.

Closed for now.
