### ISSUE TITLE
Cannot specify version of GTDB in ampliseq v2.3.1

### ISSUE THREAD

**Issue by AnotherSimon** [nf-core/ampliseq#515]
When issuing commands like <code>nextflow run nf-core/ampliseq -r 306ad5df8f -profile docker--dada_ref_taxonomy "gtdb=06-RS202" </code> I get the following output:
```
 N E X T F L O W  ~  version 21.10.6
Launching `nf-core/ampliseq` [lethal_wescoff] - revision: 306ad5df8f [2.3.1]

ERROR: Validation of pipeline parameters failed!


* --dada_ref_taxonomy: 'gtdb=06-RS202' is not a valid choice (Available choices (5 of 19): gtdb=05-RS95, gtdb, pr2=4.14.0, pr2=4.13.0, pr2, ... )
```

This is despite the fact that this should be a legal option for ref DB as indicated by the pipeline if you specify an invalid alternative like <code>nextflow run nf-core/ampliseq -r 306ad5df8f -profile docker--dada_ref_taxonomy "Nonsense" </code> which produces an output like:
<pre><code>
N E X T F L O W  ~  version 21.10.6
Launching `nf-core/ampliseq` [modest_khorana] - revision: 306ad5df8f [2.3.1]
=============================================================================
  DADA2 reference database 'Nonsense' not found in any config files provided to the pipeline.
  Currently, the available reference taxonomy keys for `--dada_ref_taxonomy` are:
  gtdb=05-RS95, <b>gtdb=06-RS202</b>, gtdb, pr2, pr2=4.14.0, pr2=4.13.0, rdp=18, rdp, sbdi-gtdb, sbdi-gtdb=R06-RS202-3, sbdi-gtdb=R06-RS202-1, silva, silva=138, silva=132, unite-fungi, unite-fungi=8.3, unite-fungi=8.2, unite-alleuk, unite-alleuk=8.3, unite-alleuk=8.2
===================================================================================
</pre></code>

Please note that the option "gtdb=R06-RS202" (as listed on the [nf-core site](https://nf-co.re/ampliseq/2.4.1/parameters#taxonomic-database)) also does not work.
The pipeline will run successfully when I do not specify a version for GTDB (apparently defaulting to [release 202](https://data.ace.uq.edu.au/public/gtdb/data/releases/release202/202.0/genomic_files_reps/bac120_ssu_reps_r202.tar.gz) anyway).

**Comment by erikrikarddaniel** [comment]
Can you try with Ampliseq 2.4.1, the latest release?
