### ISSUE TITLE
Bug with v2.4.1: categorical data required in metadata

### ISSUE THREAD

**Issue by chuan-wang** [nf-core/ampliseq#522]
### Description of the bug

According to the pipeline instruction, metadata files are not required to have additional columns than the ID column, and it is optional to have `--metadata_category`. But when I ran with a metadata file with only the ID column, `qiime` threw the following error messages:

```
Plugin error from diversity:

    Metadata does not contain any columns that satisfy this visualizer's requirements. There must be at least one metadata column that contains categorical data, isn't empty, doesn't consist of unique values, and doesn't consist of exactly one value.
```

I tried adding a "fake" category column with two values ("A" and "B") in the metadata file, running the same command with the option `--metadata_category fake`, the pipeline could be completed.

**Comment by d4straub** [comment]
Thanks for the report! 
I think some processes cannot be run without additional columns, such as diversity & differential abundance analysis. Those would need to be manually skipped with the skipping parameters, see https://nf-co.re/ampliseq/2.4.1/parameters#skipping-specific-steps. I will see if I can make those processes be skipped automatically when the metadata file contains only one column or I just update the documentation and reference the relevant skipping params.

**Comment by d4straub** [comment]
I updated the documentation, currently in the dev branch, but will be part of the next release. Thanks again for reporting!
