### ISSUE TITLE
Nicer plots?

### ISSUE THREAD

**Issue by apeltzer** [nf-core/ampliseq#54]
Should have a look at this one here:

https://github.com/bbarad/matplotlibrc

Super easy to adapt that for the pipeline - simply take the matplotlibrc there, adapt it to our needs and supplement it with ampliseq ;-)

**Comment by d4straub** [comment]
Not sure where to apply that right now, maybe later ;)

**Comment by d4straub** [comment]
Currently no further plots planned, closed for now.
