### ISSUE TITLE
ASV filtering with barrnap could be improved

### ISSUE THREAD

**Issue by d4straub** [nf-core/ampliseq#547]
### Description of feature

Filtering ASVs with barrnap is currently using each barrnap gff individually. This leads to having a positive list of ASVs matching the chosen kingdom with --filter_ssu for ASVs that might have a lower evalue for another kindgom. It might be better to use barrnap/summary.tsv, determine the kingdom with lowest evalue, and choose only from the list of lowest evalue the matching kingdoms to --filter_ssu.

**Comment by erikrikarddaniel** [comment]
I agree!

**Comment by d4straub** [comment]
In dev
