### ISSUE TITLE
how did the pipeline filter the "filtered-table.qza" 

### ISSUE THREAD

**Issue by bark9299** [nf-core/ampliseq#555]
Sorry if this is a silly question but I wanted to know what parameters the pipeline chose to filter the "filtered-table.qza". When I look at the output files on the nexflow ampliseq github page under /qiime2/abundance_tables, you see the filtered-table.qza with a short description of "QIIME2 fragment".  When I look at this filtered-table file as a qzv on qiime2 view, the only difference I can see is that the number of features and total frequency decreased from the original "table.qza" file. However, it does not get rid of any samples.

**Comment by d4straub** [comment]
Hi there, all question welcome!

> When I look at the output files on the nexflow ampliseq github page under /qiime2/abundance_tables, you see the filtered-table.qza with a short description of "QIIME2 fragment". When I look at this filtered-table file as a qzv on qiime2 view, the only difference I can see is that the number of features and total frequency decreased from the original "table.qza" file.

I assume you are speaking about the filtered-table.qza file in the AWS results tab on the nf-core website [here](https://nf-co.re/ampliseq/results#ampliseq/results-78b7514ceeba80efb66b0e973e5321878cb9b0ba/qiime2/abundance_tables/abundance_tables)? Furthermore, I assume the table.qza file is from [here](https://nf-co.re/ampliseq/results#ampliseq/results-78b7514ceeba80efb66b0e973e5321878cb9b0ba/qiime2/input/)?
The difference is essentially the filters explained directly below https://nf-co.re/ampliseq/2.5.0/output#qiime2, i.e. [--exclude_taxa](https://nf-co.re/ampliseq/2.5.0/parameters#exclude_taxa) (default is removing mitochondria & chloroplast), [--min_frequency](https://nf-co.re/ampliseq/2.5.0/parameters#min_frequency) , and [--min_samples](https://nf-co.re/ampliseq/2.5.0/parameters#min_samples) (default is off).

> However, it does not get rid of any samples.

Correct, the filters are removing ASVs, not samples. The only way to remove samples currently was introduced in version 2.5.0 with https://github.com/nf-core/ampliseq/pull/538, i.e. [--diversity_rarefaction_depth](https://nf-co.re/ampliseq/2.5.0/parameters#diversity_rarefaction_depth) and [ancom_sample_min_count](https://nf-co.re/ampliseq/2.5.0/parameters#ancom_sample_min_count).

Is there a specific reason you want to get rid of samples? And based on what specifics (e.g. total sample counts, sample name, ...)? A sample filtering step at other points of the pipeline based e.g. on total sample counts would be relatively easy to add, but I am not sure why it would be needed.

**Comment by d4straub** [comment]
Close this because it seems clarified and no further response. Please open another issue and/or join the nf-core slack channel #ampliseq.
