### ISSUE TITLE
Add more details on --exclude_taxa value taxonomy format

### ISSUE THREAD

**Issue by Ste40** [nf-core/ampliseq#559]
I would add more information about the format of taxonomy names required by the `--exclude_taxa` parameter.

**Comment by d4straub** [comment]
Hi there, are you speaking about [--exclude_taxa](https://nf-co.re/ampliseq/2.5.0/parameters#exclude_taxa) ? When you click on "help" there is a bunch of information. What is missing there in your opinion?

**Comment by d4straub** [comment]
Thanks for adding the missing explanation yourself!
