### ISSUE TITLE
Sample Name issues for parsing reads in qiimi

### ISSUE THREAD

**Issue by likelet** [nf-core/ampliseq#56]
seems a reads name parsing problem in my situation 
![image](https://user-images.githubusercontent.com/3021506/50272699-80ca4300-0473-11e9-8a92-f227b5439d31.png)
My command is 
```shell
nextflow run ampliseq \
 --reads "/data3/zqf/16S_Anaysis/rawdata/28892494"  \
 --FW_primer GTGYCAGCMGCCGCGGTAA --RV_primer GGACTACNVGGGTWTCTAAT \
 --metadata "/data3/zqf/16S_Anaysis/rawdata/Metadata.tsv"\
 --outdir /data3/zqf/16S_Anaysis/results/28892494/ \
 -profile docker --genomes greengenes -resume
```

my reads file is like `2095566_L001_R1_001.fastq.gz `  , 
dose sample name need a `_` inside ?

**Comment by d4straub** [comment]
Yes it does need an additional `_`, as the error indicates it needs to follow the regex '.+_.+_L[0-9][0-9][0-9]_R[12]_001.fastq.gz'. Unfortunately I didn't specify this in the documentation, I'll correct that.

**Comment by likelet** [comment]
well, is there a strategy to fix this ?  as most of the sample names  in my center has no "_"  inside.  I think this may also be  an issue for others.

**Comment by d4straub** [comment]
I opened a separate issue for this, I close it for now.
