### ISSUE TITLE
Add classifier name and database name to output file names

### ISSUE THREAD

**Issue by erikrikarddaniel** [nf-core/ampliseq#560]
### Description of feature

E.g. `dada2/ASV.tax.tsv` would be `dada2/ASV.dada2tax.sbdi-gtdb_r07rs207.tsv` and `dada2/ASV.tax_species.tsv` would become `dada2/ASV.dada2species.sbdi-gtdb_r07rs207.tsv`.

**Comment by d4straub** [comment]
I have added the ref tax abbreviation but not the taxonomic algorithm name to the file names.
