### ISSUE TITLE
Parser error for single-end data

### ISSUE THREAD

**Issue by lch14forever** [nf-core/ampliseq#572]
### Description of the bug

Thank you for developing this nice workflow!

I am getting an error during parsing:

```
No such file: home

 -- Check script '/home/chenhao/.nextflow/assets/nf-core/ampliseq/./workflows/../subworkflows/local/parse_input.nf' at line: 143 or see '.nextflow.log' file for more details
```

I found that my parsed input list in `ch_reads` looks like this:

```
[[id:S1, single_end:true, run:1], /home/chenhao/test/S1_R1_001.fastq.gz]
[[id:S2, single_end:true, run:1], /home/chenhao/test/S2_R1_001.fastq.gz]
```

I think L146-L147 of `parse_input.nf` could be changed to 

```nextflow
        ch_reads
            .branch {
                failed: it[0].single_end ? it[1].size() < 1.KB : it[1][0].size() < 1.KB || it[1][1].size() < 1.KB
                passed: it[0].single_end ? it[1].size() >= 1.KB : it[1][0].size() >= 1.KB && it[1][1].size() >= 1.KB
            }
```

**Comment by d4straub** [comment]
Hi there,
thanks for the report!
I was able to reproduce the error.
That change from `it[0].single_end ? it[1][0].size()` to `it[0].single_end ? it[1].size()` indeed works. Weirdly, a second such test in `cutadapt_workflow.nf` does not contain that error but works fine.

**Comment by d4straub** [comment]
I found it only appears when a single end file is empty. I fixed it in the PR above, it will be in dev branch soon, it will be in the next release.
Unfortunately that means for now you have to take care to not supply empty (<1KB) single end read files to avoid the error.
