### ISSUE TITLE
Add UNITE 9.0 databases

### ISSUE THREAD

**Issue by prototaxites** [nf-core/ampliseq#574]
### Description of feature

The most recent UNITE version available in ampliseq is 8.3, which was released in May '21 - version 9.0 is available (https://unite.ut.ee/repository.php#panel5a, last release Nov '22). 

Would be good to keep up-to-date with the latest taxonomy!

**Comment by erikrikarddaniel** [comment]
> ### Description of feature
> 
> The most recent UNITE version available in ampliseq is 8.3, which was released in May '21 - version 9.0 is available (https://unite.ut.ee/repository.php#panel5a, last release Nov '22).
> 
> Would be good to keep up-to-date with the latest taxonomy!

Indeed. Do you fancy contributing this? Happy to help, please use the nf-core Slack channel #ampliseq channel for help.

**Comment by prototaxites** [comment]
Happy to add this (should be pretty straightforward) - will shoot a message in Slack about how to process the files as it looks like the pipeline doesn't download the release directly from UNITE.

**Comment by jtangrot** [comment]
I have now finished updating the SH files, needed for the addsh option, to UNITE 9.0, and I am preparing a PR with the new databases. I don't know if you did any work on the other "tracks", like the standard analysis with assignTaxonomy, or qiime @prototaxites?
My initial tests have some problems with qiime classification and the unite-fungi version 9.0 (unite-alleuk works fine), qiime claims "this classifier does not support confidence values". Googling indicates this could be a formatting issue, but I find this unlikely as the unite-fungi file is just a subset of unite-alleuk, which works. Does anyone know what the issue could be?

**Comment by jtangrot** [comment]
UNITE 9.0 is now in dev, except for the QIIME version of unite-fungi.

**Comment by d4straub** [comment]
Seems solved?!
