### ISSUE TITLE
Error locating home in single-end analysis

### ISSUE THREAD

**Issue by pehenrique** [nf-core/ampliseq#579]
### Description of the bug

Hello everybody,

I would like some help with an error I am having while conducting single-end analyzes with my data. I started using nf-core/ampliseq recently and have successfully used it for pair-end data. I want to analyze only my forward reads and the pipeline is giving me the error below and I am not able to solve the problem. Forgive me if this is a silly question, but I already looked in the documentation and in the troubleshooting of nf-core and I didn't find anything related to my case. The command line I used with single-end was basically the same as I used for pair-end, I just added the "--single_end" and "--extension" parameters and directed the input path to a folder with just my forward sequence.

Best,

### Command used and terminal output

```console
~$ nextflow run nf-core/ampliseq -profile singularity --input "/home/pdantas/testes/seqs-teste/teste-se/" --single_end --extension "/*_R1_001.fastq.gz" --max_memory '32.GB' --skip_cutadapt --outdir "/home/pdantas/testes/teste-ampliseq-se"

ERROR ~ No such file or directory: home

 -- Check script '.nextflow/assets/nf-core/ampliseq/./workflows/../subworkflows/local/parse_input.nf' at line: 146 or see '.nextflow.log' file for more details


~$ ls testes/seqs-teste/teste-se/
6_L001_R1_001.fastq.gz
```

### Relevant files

[nextflow.log](https://github.com/nf-core/ampliseq/files/11398677/nextflow.log)

### System information

Nextflow version 23.04.1
Ampliseq version v2.5.0-g78b7514
Container Singularity
OS Linux Ubuntu 20.04.4 LTS
Hardware HPC
Executor Local

**Comment by d4straub** [comment]
Hi there,
this appears to be the identical problem to https://github.com/nf-core/ampliseq/issues/572
Essentially, when you use Direct FASTQ input with single end data and one of the files is empty, the perser will fail with that cryptic error message. This problem is solved in dev branch and that fix will be in the next release. Until then, use [sample sheet input](https://nf-co.re/ampliseq/2.5.0/usage#samplesheet-input) or take care that none of your files is empty (<1KB in size).
Please let me know if that solves your problem.

**Comment by pehenrique** [comment]
Hi @d4straub, 
Thanks for your answer
I took a look at the log I sent and I really saw that it could be something related to the empty file, however I checked my file and it is not empty. I'll try your suggestion to use sample sheet input. If that doesn't work, I'll report it here.

**Comment by d4straub** [comment]
> however I checked my file and it is not empty

the threshold is 1KB in size, not that its empty. But ptobabaly you meant that.
I hope the second approach, i.e. samplesheet input, will help!

**Comment by pehenrique** [comment]
Hi @d4straub! 
Ampliseq worked using the samplesheet as you suggested. Thank you very much.

**Comment by d4straub** [comment]
Glad that worked, I'll close that issue then.
