### ISSUE TITLE
Error executing Ampliseq through pbs/Torque executor

### ISSUE THREAD

**Issue by pehenrique** [nf-core/ampliseq#581]
### Description of the bug

Hello everybody,

I'm adapting my analyzes to the best practices for executing work on the cluster I use. The cluster uses PBS and I tried to configure Ampliseq by including the parameter process.executor = 'pbs' in the nextflow.config file as suggested in the Nextflow manual, however I am having the following error below. Thank you in advance for your help.

### Command used and terminal output

```console
$ nextflow run nf-core/ampliseq -profile singularity --input /home/pdantas/testes/teste-perReadCutting-fastp/results1/ --trunc_qmin 20 --max_memory '32.GB' --skip_cutadapt --outdir /home/pdantas/testes/teste-perReadCutting-fastp/results1/ampliseq


Command error:
  env: 'singularity': No such file or directory

Work dir:
  /home/pdantas/work/6f/0049e3735817362c1eb8f51cd0a43c

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

 -- Check '.nextflow.log' file for details
ERROR ~ Cannot invoke method getAt() on null object
```

### Relevant files

[nextflow.config.txt](https://github.com/nf-core/ampliseq/files/11433016/nextflow.config.txt)
[nextflow.log.log](https://github.com/nf-core/ampliseq/files/11433017/nextflow.log.log)

### System information

Nextflow version: 23.04.1.5866
Hardware: HPC
Executor: pbs
Container engine: Singularity
OS: linux ubuntu
Version of nf-core/ampliseq: v2.5.0-g78b7514

**Comment by d4straub** [comment]
Hi there!

Please never ever modify pipeline files but rather use additional configs to modify pipeline behavior. If pipeline files are modified, I wont be able to help and not the original pipeline is used.
So the best practice to start nf-core pipelines is following [nf-core documentation](https://nf-co.re/docs/usage/tutorials/nf_core_usage_tutorial#running-nf-core-pipelines). And [here](https://nf-co.re/docs/usage/tutorials/nf_core_usage_tutorial#config-profiles) is info about configs.
For your application, the optimal solution would be either an [existing nf-core config for your cluster](https://github.com/nf-core/configs) or using `-c custom.config` with your required settings. The file `custom.config` may contain:
```
singularity {
  enabled = true
}
process {
  executor = 'pbs'
}
```
I used this config as an example, but you could use any to get ideas.

**Comment by pehenrique** [comment]
Hi @d4straub ,

Thanks for the alert. I undo the changes in the ampliseq config file and create a new custom config file as you suggested, however the problem persists. Another thing I noticed but I don't know if it can help is that even defining the singularity in the custom file, ampliseq runs as "standard".

```
$ cat pipelines/custom.config
singularity {
  enabled = true
}
process {
  executor = 'pbs'
}

```
`bin/nextflow run nf-core/ampliseq -c pipelines/custom.config --input "/home/pdantas/pipelines/sample-sheet-seR1.tsv" --trunc_qmin 20 --single_end --extension '/*_R-trimmed-1.fastq.gz' --skip_cutadapt --outdir "/home/pdantas/testes/ampliseq-se-R1"`

```
Command error:
  env: 'singularity': No such file or directory

Work dir:
  /home/pdantas/work/f2/5aae7314f8e30cf168bdf20b1de37e

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

 -- Check '.nextflow.log' file for details
```


[nextflow.log](https://github.com/nf-core/ampliseq/files/11466342/nextflow.log)

**Comment by d4straub** [comment]
Singularity isnt executable. Some reasons come to mind, such as not instelled, module not loaded, etc
Have a look at https://github.com/nf-core/mag/issues/234 and the other issue linked, that should help.

**Comment by pehenrique** [comment]
Hey @d4straub ,

Thanks for the valuable help. As in the [nf-core/mag#234](https://github.com/nf-core/mag/issues/234) case, the cluster I work on also has no modules; I just needed to use conda to activate the singularity environment.

```
$ cat pipelines/custom.config
singularity {
  enabled = true
}
process {
  executor = 'pbs'
  beforeScript = 'source /sw/miniconda.export; conda activate singularity_04_2021'
}
```

**Comment by d4straub** [comment]
great, glad it works for now, and many thanks to posting the solution, that might help when another person has a similar problem!
