### ISSUE TITLE
Use new PR2 release for 18S (PR2 version 5.0.0)

### ISSUE THREAD

**Issue by andand** [nf-core/ampliseq#588]
### Description of feature

https://github.com/pr2database/pr2database/releases/tag/v5.0.0

Note that "We moved from 8 levels (kingdom to species) to 9 levels (domain to species) with a new level subdivision. The changes are explained [here](https://github.com/pr2database/pr2database/blob/v5.0.0)."

**Comment by d4straub** [comment]
Added to dev, will be in next release.
