### ISSUE TITLE
Sanity check for input values 

### ISSUE THREAD

**Issue by apeltzer** [nf-core/ampliseq#6]
expand sanity check for input values, also --metadata_category could be verified: subset of metadata_category_all

**Comment by apeltzer** [comment]
Is this really required @d4straub ?

**Comment by d4straub** [comment]
Strictly speaking not. But it would be a good addition, because the workflow would break quite late when --metadata_category is not pointing to valid metadata columns. We can postpone this issue.

**Comment by d4straub** [comment]
extended sanity check in commit a0d8f365aa9887cc0298c6e8ad156281b091591f

Verification of --metadata_category with metadata_category_all and/or metadata_category_pairwise remains desirable.

**Comment by d4straub** [comment]
Over the course of the last year I have encountered numerous problems with metadata that are absolutely impossible to test and verify all. 

I think I give up on that plan for now.
