### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by d4straub** [nf-core/ampliseq#61]
Update to reflect all changes.

**Comment by d4straub** [comment]
might still profit from proofreading

**Comment by d4straub** [comment]
done

**Comment by d4straub** [comment]
docs/installation.md needs update, especially dead link to reference databases

**Comment by apeltzer** [comment]
I'll also have a detailed look at the docs once we do the PR for release 1.1.0 to make sure things are there and properly updated :-)

**Comment by d4straub** [comment]
So far I am done, ready for 1.1.0
