### ISSUE TITLE
Error in command

### ISSUE THREAD

**Issue by dixi06** [nf-core/ampliseq#623]
Hi I am new to nextflow, I was trying to run the pipeline but it gives me errors.
Can you please let me know wheat is wrong with my command.

nextflow run nf-core/ampliseq \
   -profile singularity \
   --input "~/Biovigilance_2021/ITS/"
   --FW_primer  AHCGATGAAGAACRYAG \
   --RV_primer  CTTATTGATATGCTTAAGTTCAG \
   --outdir “~/ITS_2021/”

ERROR ~ ERROR: Validation of pipeline parameters failed!

 -- Check '.nextflow.log' file for details
ERROR ~ * Missing required parameter: --outdir

 -- Check '.nextflow.log' file for details

Exiting!
-bash: --FW_primer: command not found

Thanks.

**Comment by a4000** [comment]
It looks like your command is on multiple lines. You can put everything on one line or try adding '\' at the end of every line except for the last line. E.g., 

nextflow run nf-core/ampliseq \
-profile singularity \
--input "/Biovigilance_2021/ITS/" \
--FW_primer AHCGATGAAGAACRYAG \
--RV_primer CTTATTGATATGCTTAAGTTCAG \
--outdir “/ITS_2021/”

**Comment by d4straub** [comment]
Or you just write all in one line, e.g.
`nextflow run nf-core/ampliseq -profile singularity --input "/Biovigilance_2021/ITS/" --FW_primer AHCGATGAAGAACRYAG --RV_primer CTTATTGATATGCTTAAGTTCAG --outdir “/ITS_2021/”`
I close that here, but please feel free to open another issue. For beginner questions it might be also helpful to have a look at the [nf-core slack](https://nf-co.re/join) channel `#ampliseq`.
