### ISSUE TITLE
Read "Manifest" file format?

### ISSUE THREAD

**Issue by DiegoBrambilla** [nf-core/ampliseq#63]
Hi,
There is another way to import single- and paired-end demultiplexed sequences in QIIME2 aside from the Casava format that is not picky  with names. The **"Manifest" file format** (https://docs.qiime2.org/2018.11/tutorials/importing/?highlight=manifest#fastq-manifest-formats) is a text file that does not pose limitations to file naming. It is up to users to prepare it but I think that with some coding the preparation of manifest files can be automatized and thus can enhance the flexibility of the pipeline in accepting input files. Another way could also be that the pipeline would accept both casava file formats and manifest files manually created by users. This way, downstream analyses like taxonomy or alpha diversity would benefit from having clearer ID names.

**Comment by d4straub** [comment]
The more I think about it the more I like it, flexibility is just so good.
I have a working version which is creating a manifest automatically, just have to test it further and work on docs. I would like to have it in the version 1.1 which is due soonish.

**Comment by DiegoBrambilla** [comment]
That would be great, appreciate it! Glad I could be of inspiration.

**Comment by d4straub** [comment]
This is tested and available in dev branch now.
