### ISSUE TITLE
Adding gtdb release 214 & adding already downloaded database

### ISSUE THREAD

**Issue by x-rv** [nf-core/ampliseq#636]
### Description of feature

Hello! 

GTDB has recently published a new release: https://data.gtdb.ecogenomic.org/releases/release214/
Could this be added to the supported databases?

Also, is it possible to indicate the path to an already downloaded database in the dada_ref_taxonomy option?

Thanks!

**Comment by d4straub** [comment]
> GTDB has recently published a new release: https://data.gtdb.ecogenomic.org/releases/release214/
> Could this be added to the supported databases?

Yes thats sounds important, thanks for the reminder!

> Also, is it possible to indicate the path to an already downloaded database in the dada_ref_taxonomy option?

[--dada_ref_tax_custom](https://nf-co.re/ampliseq/2.6.1/parameters/#dada_ref_tax_custom) would allow that. But the databases are not so large and that shouldnt be a problem?! If you resume a run an already downloaded database will also be re-used and not downloaded again. Another option might be to use https://nf-co.re/docs/usage/offline (havent tried that myself).

**Comment by d4straub** [comment]
GTDB 214.1 is avaivale in the dev branch and will be in the next release!
