### ISSUE TITLE
I didn't receive an email notification

### ISSUE THREAD

**Issue by luozhy88** [nf-core/ampliseq#653]
### Description of the bug

"Thank you very much for nfcore and its excellent software. I successfully ran the AmpliSeq workflow, but I didn't receive an email notification (using --email [479321347@qq.com](mailto:479321347@qq.com)). How can I test if my email system is working correctly? I'm using Ubuntu 20.04."

**Comment by d4straub** [comment]
Hi there,

glad that you are enjoying nf-core pipelines and ampliseq!

In https://nf-co.re/docs/usage/introduction#tips-and-tricks is specified that a mail configutation is needed, see https://www.nextflow.io/docs/latest/mail.html#mail-configuration. So either configure in the system you are running the pipeline in a mail program or configure it via nextflow.
Does that answer your question?
