### ISSUE TITLE
Add custom qiime reference database support to Ampliseq.

### ISSUE THREAD

**Issue by MatthewJM96** [nf-core/ampliseq#665]
Implement an equivalent custom database flag as exists for Kraken and Dada (i.e. qiime_ref_tax_custom).

**Comment by d4straub** [comment]
A custom trained classifier can be already supplied with [`--classifier`](https://nf-co.re/ampliseq/2.7.0/parameters#classifier), but there is indeed no option equivalent to `--dada_ref_tax_custom`.

**Comment by d4straub** [comment]
Was solved in https://github.com/nf-core/ampliseq/pull/667 & https://github.com/nf-core/ampliseq/pull/673
