### ISSUE TITLE
Problem running offline

### ISSUE THREAD

**Issue by telatin** [nf-core/ampliseq#67]
I'm running the pipeline in an offline cluster. I downloaded the repository and the singularity image.
I initialize the script with: export NXF_OFFLINE='TRUE'

Running as 
nextflow run path/to/ampliseq -with-singularity "path/to/img"

I got this warning:
```
WARN: Unable to stage foreign file: https://www.arb-silva.de/fileadmin/silva_databases/qiime/Silva_132_release.zip (try 1) -- Cause: Connection timed out (Connection timed out)
```

Can i predownload the archive and place it somewhere?

**Comment by apeltzer** [comment]
You could try using this here:

```
--reference_database /path/to/zip/file
``` 

and download & store the file beforehand. Did that help?

**Comment by telatin** [comment]
Yes Thanks!
