### ISSUE TITLE
unzip:  cannot find zipfile directory in one of Silva_132_release.zip

### ISSUE THREAD

**Issue by solna** [nf-core/ampliseq#68]
Hi, I went into an issue as shown below. I am running the docker standard profile. Any suggestions on solving this issue? 

[2d/5ce92b] Submitted process > make_SILVA_132_16S_classifier (1)
[ac/9130c2] Submitted process > metadata_category_all (1)
ERROR ~ Error executing process > 'make_SILVA_132_16S_classifier (1)'

Caused by:
  Process `make_SILVA_132_16S_classifier (1)` terminated with an error exit status (9)

Command executed:

  unzip -qq Silva_132_release.zip
  
          fasta="SILVA_132_QIIME_release/rep_set/rep_set_16S_only/99/silva_132_99_16S.fna"
          taxonomy="SILVA_132_QIIME_release/taxonomy/16S_only/99/consensus_taxonomy_7_levels.txt"
  
          if [ "false" = "true" ]; then
  		    sed 's/#//g' $taxonomy >taxonomy-99_removeHash.txt
  		    taxonomy="taxonomy-99_removeHash.txt"
  		    echo "
  ######## WARNING! The taxonomy file was altered by removing all hash signs!"
          fi
  
  	    ### Import
  	    qiime tools import --type 'FeatureData[Sequence]' 		--input-path $fasta 		--output-path ref-seq-99.qza
  	    qiime tools import --type 'FeatureData[Taxonomy]' 		--source-format HeaderlessTSVTaxonomyFormat 		--input-path $taxonomy 		--output-path ref-taxonomy-99.qza
  
  	    #Extract sequences based on primers
  	    qiime feature-classifier extract-reads 		--i-sequences ref-seq-99.qza 		--p-f-primer ACTCCTACGGGAGGCAGCA 		--p-r-primer GGACTACHVGGGTWTCTAAT 		--o-reads ACTCCTACGGGAGGCAGCA-GGACTACHVGGGTWTCTAAT-99-ref-seq.qza         --quiet
  
  	    #Train classifier
  	    qiime feature-classifier fit-classifier-naive-bayes 		--i-reference-reads ACTCCTACGGGAGGCAGCA-GGACTACHVGGGTWTCTAAT-99-ref-seq.qza 		--i-reference-taxonomy ref-taxonomy-99.qza 		--o-classifier ACTCCTACGGGAGGCAGCA-GGACTACHVGGGTWTCTAAT-99-classifier.qza         --quiet

Command exit status:
  9

Command output:
  (empty)

Command error:
  [Silva_132_release.zip]
    End-of-central-directory signature not found.  Either this file is not
    a zipfile, or it constitutes one disk of a multi-part archive.  In the
    latter case the central directory and zipfile comment will be found on
    the last disk(s) of this archive.
  unzip:  cannot find zipfile directory in one of Silva_132_release.zip or
          Silva_132_release.zip.zip, and cannot find Silva_132_release.zip.ZIP, period.

**Comment by d4straub** [comment]
Hi there, I would guess the file download failed.

You could download the file from https://www.arb-silva.de/fileadmin/silva_databases/qiime/Silva_132_release.zip and use `--reference_database /path/to/zip/file` as in #67 

Let me know if that helps.

Good luck!

**Comment by d4straub** [comment]
I assume the problem was solves.
