### ISSUE TITLE
Allow stratified output from picrust2

### ISSUE THREAD

**Issue by hh1985** [nf-core/ampliseq#685]
### Description of feature

Please add option to enable stratified results output from picrust2:`--stratified` and related flags.

**Comment by hh1985** [comment]
BTW, to add more parameters, is there any way to update the parameter file somewhere directly instead of downloading the source code and manually changing the configuration of the pipeline?

**Comment by erikrikarddaniel** [comment]
> BTW, to add more parameters, is there any way to update the parameter file somewhere directly instead of downloading the source code and manually changing the configuration of the pipeline?

Yes, to add `--stratified` you can create a config file (typically `nextflow.config` in the directory in which you're running the pipeline) looking like this:
```
process {
  withName: PICRUST {
        ext.args = "-t epa-ng --remove_intermediate --stratified"
  }
}
```

**Comment by erikrikarddaniel** [comment]
This technique allows full freedom to end users to set parameters to programs exactly as they want them instead of waiting for a developer to add a flag to the pipeline. If you're satisfied with this, please close the issue.

**Comment by hh1985** [comment]
That's exactly what I want. Thanks!
