### ISSUE TITLE
"-profile standard" produces error

### ISSUE THREAD

**Issue by d4straub** [nf-core/ampliseq#69]
Running local using 

`nextflow run ampliseq -profile standard,singularity --reads [...skipped all that options here...] --max_cpus 4 --max_memory '15.GB'`

produces the error message:

> Unknown configuration profile: 'standard'

@apeltzer is that supposed to be gone? If yes, docs have to be updated ...

**Comment by apeltzer** [comment]
Yes, this is supposed to be gone :-)

**Comment by d4straub** [comment]
so standard is just not specified anymore and default?
