### ISSUE TITLE
Launch webpage not working

### ISSUE THREAD

**Issue by kjurdzinski** [nf-core/ampliseq#693]
### Description of the bug

Hey,

I've tried to access the launch webpage and got this error:

![image](https://github.com/nf-core/ampliseq/assets/74978240/5d654434-74a9-40a8-96f8-08263df44249)

I've used the link on the new nf-core website.

Kind regards,
Krzysztof Jurdzinski

**Comment by d4straub** [comment]
Thanks for the report. That seems to be the case also for other pipelines. I will inform the website team.

**Comment by mashehu** [comment]
Weird workaround for now. append the launch_id behind the following url: `https://oldsite.nf-co.re/launch?id=`

**Comment by ewels** [comment]
After adjusting some settings on the server, I think that this should now be solved. Thanks for reporting!
