### ISSUE TITLE
Getting ca 50% more ASVs than when using DADA2 on QIIME2

### ISSUE THREAD

**Issue by eperezv** [nf-core/ampliseq#703]
### Description of the bug

Hello,

I was unsure about opening an github issue but couldn't join the slack channel. 
I like the way ampliseq is built and tried to process my 16S V4 data. I am getting ca 97.000 ASVs, which is much higher than what I get running DADA2 on QIIME2 (ca. 60.000 ASVs). I have checked that the reads per sample are roughly similar (not differing in more than ca. 5%), depending on the sample.

I have used mostly default options, and I have played with trunc_qmin default (25) and 35 but I've seen no big changes.

Do you have any clue why I get such a difference? 
Thank you

### Command used and terminal output

```console
nextflow run nf-core/ampliseq -profile docker --skip_ancom --trunc_qmin 35 -params-file params.yaml

input: "samples.txt"
FW_primer: "GTGCCAGCMGCCGCGGTAA"
RV_primer: "GGACTACHVGGGTWTCTAAT"
metadata: "metadata.txt"
outdir: "./resultsq35_last"
filter_ssu: "bac,arc"
```

**Comment by d4straub** [comment]
Hi!
50% more is indeed a big difference. I havent run QIIME2 recently, so I am not up to date with their defaults. The 5% more reads coming through preprocessing can absolutely mean a difference, probably the outcomes differ in low abundant ASVs?
But 60.0000 and 97.000 ASV is also an extremely high number, potentially there is something wrong with the sequencing data (depending mostly on sample origin, sample number, and sequencing depth).
50% more ASV isnt necessarily a good thing, it might mean more spurious ASVs, but it also can mean more true ASVs detected.

**Comment by eperezv** [comment]
Thank you for your answer. I am doing tests to check about the difference.
You were right, it was not a bug but didn't know how to remove it.
