### ISSUE TITLE
Run without metadata?

### ISSUE THREAD

**Issue by alneberg** [nf-core/ampliseq#71]
Hello,
I get the error:
`ERROR: Missing required input --Q2imported OR --FW_primer / --RV_primer / --metadata`

when I run the pipeline without the `--metadata` parameter *but* with using all three of:
`--FW_primer`,  `--RV_primer` and `--untilQ2import`. I understood from the issue #15, that if `--untilQ2import` was specified, the metadata was not necessary? Is this a typo, where `--Q2imported` should be replaced with `--untilQ2import` in the check?

We would really like to be able to run the first steps without the --metadata, since at our sequencing platform (NGI Sweden), we don't have the users metadata available and we'd like to be able to run primary analysis without this information.

Thanks!

**Comment by d4straub** [comment]
Hi,

this error is produced by release 1.0.0 (which is admittedly too strict for inputs) and the issue #15 refers to the dev version. Would you be able to test the same analysis with the dev version?
1.1.0 is due soon-ish and contains #15 improvement.

Best wishes

**Comment by alneberg** [comment]
Ah, I see. I missed that the issue was closed that recently. Then everything should be alright. Thanks!

**Comment by alneberg** [comment]
Sorry to reopen this issue, but I was just wondering if #15 will make it possible to get taxonomic annotation for your sequences when running without metadata? Or if its only the preprocessing steps which are allowed to run without metadata? As stated above, at our sequencing platform, we don't have the metadata, but it would be nice to still be able to run as many steps as possible...

**Comment by d4straub** [comment]
Sure, but you will miss out on a lot of output.

The minimal test command for this would be:
`nextflow run nf-core/ampliseq -r dev -profile test,singularity --onlyDenoising --metadata false`
--> taxonomy classification is in `results/taxonomy/taxonomy.tsv`. However, only absolute abundance tables are calculated, relative abundance tables are missing.

Running this gives the maximum output without any metadata table:
`nextflow run nf-core/ampliseq -r dev -profile test,singularity --onlyDenoising --metadata false --skip_abundance_tables false --skip_taxonomy false -resume`
--> including relative abundance table

That should work with actual data also, I think.

**Comment by d4straub** [comment]
Just not specifying any metadata will now calculate all output that doesn't require it (which is primary analysis incl. taxonomic classification and some exported tables).
