### ISSUE TITLE
off line mode (singularity pull)

### ISSUE THREAD

**Issue by mafouille** [nf-core/ampliseq#72]
Hi 

The command indicated in the documentation to get the singularity image `singularity pull --name nf-core-ampliseq.simg shub://nf-core/ampliseq` doesn't work. 

```
$singularity -d pull shub://nf-core/ampliseq
DEBUG GET https://www.singularity-hub.org/api/container/nf-core/ampliseq:latest
DEBUG Http Error with code 404
ERROR Cannot find image. Is your capitalization correct?
```

It works with smrnaseq pipeline.

maf

**Comment by d4straub** [comment]
Hi there,
seems like you found a documentation error!

Following commands don't work for me as well:
singularity pull --name nf-core-ampliseq.simg shub://nf-core/ampliseq
singularity pull --name nfcore-ampliseq-1.0.img docker://nfcore/ampliseq:1.0

but this works:
singularity pull --name nfcore-ampliseq-1.0.0.img docker://nfcore/ampliseq:1.0.0

Have to correct that in the docs!
@apeltzer what command for shub should work?

**Comment by apeltzer** [comment]
None! We dropped direct support for Singularity hub and will only have singularity pulls from DockerHub. That should be synchronized across all pipelines I guess whenever we release the next nf-core/tools release, synchronizing the template documentation to `ampliseq` as well...

**Comment by d4straub** [comment]
> That should be synchronized across all pipelines I guess whenever we release the next nf-core/tools release, synchronizing the template documentation to `ampliseq` as well...

Was that done or does it need manual intervention?

**Comment by apeltzer** [comment]
This was done - in the. `dev` branch its already updated, the 1.1.0 release will also contain the correct changes / changed URLs.
