### ISSUE TITLE
ANCOM-BC for differentially abundant taxa

### ISSUE THREAD

**Issue by enriiquee** [nf-core/ampliseq#731]
### Description of feature

ANCOM-BC has a more robust method for bias correction and controlling FDR by estimating the unknown sampling fractions and correcting the bias induced by their differences among samples. Maybe include it would be nice. 

I'd recommend checking out the ANCOM-BC paper to read more on the methods used:
https://www.nature.com/articles/s41467-020-17041-7

**Comment by d4straub** [comment]
This is in dev and will be in the next release, 2.10.0!
