### ISSUE TITLE
ERROR: R_HOME ('/usr/local/lib/R') not found

### ISSUE THREAD

**Issue by WangLab-SCSIO** [nf-core/ampliseq#732]
### Description of the bug

I installed nextflow using conda.  
R is installed in conda.
(env_nf) [train@localhost ampliseq]$ which R
~/mambaforge/envs/env_nf/bin/R

I used this command: 
nextflow run nf-core/ampliseq -profile test,docker --outdir test -resume -with-conda

I got this error. How can I fix it?

Execution cancelled -- Finishing pending tasks before exit
-[nf-core/ampliseq] Pipeline completed with errors-
ERROR ~ Error executing process > 'NFCORE_AMPLISEQ:AMPLISEQ:METADATA_ALL (Metadata.tsv)'

Caused by:
  Process `NFCORE_AMPLISEQ:AMPLISEQ:METADATA_ALL (Metadata.tsv)` terminated with an error exit status (1)

Command executed:

  metadata_all.r Metadata.tsv

  cat <<-END_VERSIONS > versions.yml
  "NFCORE_AMPLISEQ:AMPLISEQ:METADATA_ALL":
      R: $(R --version 2>&1 | sed -n 1p | sed 's/R version //' | sed 's/ (.*//')
  END_VERSIONS

Command exit status:
  1

Command output:
  (empty)

Command error:
  ERROR: R_HOME ('/usr/local/lib/R') not found

Work dir:
  /home/train/80-1372045246/ampliseq/work/41/fe8be8d5b86f25bb8d93905895f87c

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line

 -- Check '.nextflow.log' file for details

**Comment by erikrikarddaniel** [comment]
Try without the ` -with-conda`. Next time, for quicker responses, post at the nf-core Slack #ampliseq channel. Join here: https://nf-co.re/join/slack (there might be some problems with joining now, try later if there is).

**Comment by erikrikarddaniel** [comment]
Try installing Nextflow natively instead of in a Conda environment, i.e. deactivate the Conda environment and follow the instructions here: https://www.nextflow.io/ (under "Getting started").

**Comment by d4straub** [comment]
I close that issue now because of missing response. Feel free to open it again in case you continue to have the issue.
