### ISSUE TITLE
Running test error

### ISSUE THREAD

**Issue by aslangabriel99** [nf-core/ampliseq#737]
### Description of the bug

Hi ,  I just ran the pipeline 2.9.0 and 2.8.0 to test if it worked. The error message was as follows"ERROR ~ Error executing process > 'NFCORE_AMPLISEQ:AMPLISEQ:CUTADAPT_WORKFLOW:CUTADAPT_BASIC (sampleID_2a)'

Caused by:
  Process `NFCORE_AMPLISEQ:AMPLISEQ:CUTADAPT_WORKFLOW:CUTADAPT_BASIC (sampleID_2a)` terminated with an error exit status (127)

Command executed:

  cutadapt \
      -Z \
      --cores 2 \
      --minimum-length 1 -O 3 -e 0.1 -g GTGYCAGCMGCCGCGGTAA -G GGACTACNVGGGTWTCTAAT --discard-untrimmed \
      -o sampleID_2a.trimmed_1.trim.fastq.gz -p sampleID_2a.trimmed_2.trim.fastq.gz \
      sampleID_2a_1.fastq.gz sampleID_2a_2.fastq.gz \
      > sampleID_2a.trimmed.cutadapt.log
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_AMPLISEQ:AMPLISEQ:CUTADAPT_WORKFLOW:CUTADAPT_BASIC":
      cutadapt: $(cutadapt --version)
  END_VERSIONS

Command exit status:
  127

Command output:
  (empty)

Command error:
  .command.sh: line 3: cutadapt: command not found

Work dir:
  /home/aslangabriel/work/2f/014d8d0460a511d16f91d2e59bef30

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

 -- Check '.nextflow.log' file for details
ERROR ~ Cannot invoke method getAt() on null object

 -- Check script '/root/.nextflow/assets/nf-core/ampliseq/./workflows/../subworkflows/local/dada2_preprocessing.nf' at line: 61 or see '.nextflow.log' file for more details
ERROR ~ Unexpected error [NullPointerException]

 -- Check script '/root/.nextflow/assets/nf-core/ampliseq/./workflows/../subworkflows/local/../../subworkflows/local/utils_nfcore_ampliseq_pipeline/../../nf-core/utils_nfcore_pipeline/main.nf' at line: 100 or see '.nextflow.log' file for more details"

### Command used and terminal output

```console
nextflow run nf-core/ampliseq -r 2.9.0 -profile test --outdir test
```

### System information

 N E X T F L O W
      version 23.10.1 build 5891
      created 12-01-2024 22:01 UTC (13-01-2024 06:01 CDT)
      cite doi:10.1038/nbt.3820
      http://nextflow.io

**Comment by d4straub** [comment]
Using that command, it is expected that all software is installed locally. This isnt the way the pipeline is used best. The proper usage is to add a software managing software, such as conda, docker or singularity/apptainer (that needs to be installed on your system!). I recommend singularity/apptainer, if you do so, use 
`nextflow run nf-core/ampliseq -r 2.9.0 -profile test,singularity --outdir test`
Further info on software can be found in https://nf-co.re/docs/usage/installation#pipeline-software
If you run into any other problem, please feel free to open another issue. You can also join slack for a more chat-like environment, see https://nf-co.re/join
