### ISSUE TITLE
Cutadapt with "-u" instead of "fw/rv_primer seq"

### ISSUE THREAD

**Issue by ilwookkim** [nf-core/ampliseq#744]
### Description of the bug

Hi all,

I'm new in the 16s rRNA seq field. 
Our lab used Zymo 16s primer V3-V4 but they refused to provide primer sequence. 
They only provide length of primer. FW: 16, RV: 24
Therefore I would like to try to trim this seq by using "-u 16 -U 24" as in https://github.com/nf-core/ampliseq/issues/743

I created cutadpater.config as below:
process {
    withName: CUTADAPT_BASIC {
        ext.args = { [
            "--minimum-length 1 -u 16 -U 24",
            "-O ${params.cutadapt_min_overlap}",
            "-e ${params.cutadapt_max_error_rate}",
            params.pacbio ? "--rc -g ${meta.fw_primer}...${meta.rv_primer_revcomp}" :
                params.iontorrent ? "--rc -g ${meta.fw_primer}...${meta.rv_primer_revcomp}" :
                params.single_end ? "-g ${meta.fw_primer}" :
                "-g ${meta.fw_primer} -G ${meta.rv_primer}",
            params.retain_untrimmed ? '' : "--discard-untrimmed"
        ].join(' ').trim() }
	}
}

But it returns following message.
```
Incompatible parameters: `--FW_primer` and `--RV_primer` are required for primer trimming. If primer trimming is not needed, use `--skip_cutadapt`.
```

Could you help me to solve the problem?
Thanks a lot.
Best,

### Command used and terminal output

```console
nextflow run nf-core/ampliseq -r 2.9.0 -profile singularity -resume -params-file ./nf-params.json -c ./cutadapt.config
```

### System information

N E X T F L O W  ~  version 23.10.0
Hardware : Virtual Linux server
Container engine: Singularity
OS: RHEL8
Version of nf-core/ampliseq: 2.9.0

**Comment by d4straub** [comment]
Hi there,

this is no bug because you are modifying the pipeline behavior in a way that doesnt work. Thats my mistake.
I close here in favor of #743 and write there possible solutions.
