### ISSUE TITLE
Two minor things running on Google batch

### ISSUE THREAD

**Issue by lch14forever** [nf-core/ampliseq#774]
### Description of the bug

I am running ampliseq pipeline on Google cloud using batch executor. I faced two minor issues that I would like to report here in case people encountered them, too. Feel free to close it as I found workarounds.

### permission denied for FORMAT_TAXONOMY

This step failed with the error:

```
cp: failed to access '/mnt/disks/xxxxxx/.command.log': Permission denied
```

I guess the issue is with the container it uses `docker.io/biocontainers/biocontainers:v1.2.0_cv1`. Similar issue was reported [here](https://github.com/nextflow-io/nextflow/issues/4880). Using the following config fixed the issue:

```
process {
    containerOptions = "--user root"
}
```

### empty fastq files for RENAME_RAW_DATA_FILES

The default behavior of this step is to create symbolic links to the raw fastq files. But these symbolic links are not followed by the executor (not sure it is because of the fused drive or google batch itself). I ended up with two empty renamed fastq files in the work directory. I found a similar issue [here](https://github.com/nextflow-io/nextflow/issues/4845), but setting `stageInMode = 'copy'` did not work for me... I guess it is because the symbolic link was not made by nextflow.

I fixed this by modifying the `rename_raw_data_files.nf` module - changing `ln -s` to `cp`. But I think a proper way to fix it might be adding the config:

```
process {
    withName: RENAME_RAW_DATA_FILES {
        ext.args = 'cp'
    }
}
```

### System information

Nextflow version: version 24.04.4
Hardware: Google cloud
Executor: Batch
Container engine: Docker
OS: Linux
Version of nf-core/ampliseq v2.11.0-g0473e15

**Comment by d4straub** [comment]
Thanks you for the report!

`biocontainers/biocontainers:v1.2.0_cv1` is indeed a problem, but I havent found any other container that contains all software that we need. See also in https://github.com/nf-core/ampliseq/issues/502#issuecomment-1337181943
That problem might be relatively easily solved with a mulled container when nf-core moves towards sequenra containers: https://nf-co.re/blog/2024/seqera-containers-part-1

Indeed, the config with "cp" would be the "proper" way.

I will close that issue, but I do hope that the container issue can be addressed soon.
