### ISSUE TITLE
variation in Dad2 and QIIME2 output

### ISSUE THREAD

**Issue by sajjadasaf** [nf-core/ampliseq#777]
I successfully ran the pipeline and found 7,390 ASVs in the DADA2 output. However, when I checked the QIIME2 output directory, the abs-abund-table-6.tsv file showed only 884 ASVs. I'm not sure why there's such a large discrepancy between the two files. Should I proceed with the DADA2 file for downstream analysis, or should I use the QIIME2 file? Thank you for your help. I've attached the files for reference.
[abs-abund-table-6.csv](https://github.com/user-attachments/files/17072801/abs-abund-table-6.csv)
[ASV_table.csv](https://github.com/user-attachments/files/17072809/ASV_table.csv)

**Comment by d4straub** [comment]
Depends on your pipeline settings and aims. By default the pipeline removes everything that is taxonomic ally annotated as mitochondria or chloroplasts, see https://nf-co.re/ampliseq/2.11.0/parameters/#exclude_taxa. Maybe thats the reason? Checkout https://nf-co.re/ampliseq/2.11.0/docs/output/#pipeline-summary-report to see where ASVs were lost.

**Comment by sajjadasaf** [comment]
It mean that pipeline will remove everything after dada2 step. How to retain these results as we have in dada2 step.
Thank you

**Comment by d4straub** [comment]
If you would follow the link I gave you, you would find that the solution is to use `--exclude_taxa "none"` .
