### ISSUE TITLE
Add (absolute) abundance tables at different taxonomic levels

### ISSUE THREAD

**Issue by andand** [nf-core/ampliseq#81]
Would be useful to also have (absolute) abundance tables at different taxonomic levels, not just  relative abundance tables.

**Comment by d4straub** [comment]
These tables are already available in `results/barplot/level-<number>.csv`.
However, they contain metadata and might need to be transposed.

**Comment by d4straub** [comment]
Additionally you can access these files through the interactive barplot in `results/barplot/index.html`, go to the barplot opened in your browser and click on `CSV` in the Download bar. 

Original count tables can be found as .biom and .tsv in `results/abundance_table/filtered` or `results/abundance_table/unfiltered` which can be imported to a program of your liking and transformed to any special analysis you might want.

I close that issue.
