### ISSUE TITLE
container creation failed?!

### ISSUE THREAD

**Issue by marwa38** [nf-core/ampliseq#810]
### Description of the bug

I am not sure why the container can't load?
I am using singularity v4.1.0 and nextflow v24.04.3 and ampliseq v2.12.0

```
nf-core/ampliseq execution completed unsuccessfully!
The exit status of the task that caused the workflow execution to fail was: 255.

The full error message was:

Error executing process > 'NFCORE_AMPLISEQ:AMPLISEQ:RENAME_RAW_DATA_FILES (pyloric_MMV_T5_Rep1)'

Caused by:
  Process `NFCORE_AMPLISEQ:AMPLISEQ:RENAME_RAW_DATA_FILES (pyloric_MMV_T5_Rep1)` terminated with an error exit status (255)


Command executed:

  [ -f "pyloric_MMV_T5_Rep1_1.fastq.gz" ] || ln -s "pyloric_MMV_T5_Rep1_R1.fq.gz" "pyloric_MMV_T5_Rep1_1.fastq.gz"
  [ -f "pyloric_MMV_T5_Rep1_2.fastq.gz" ] || ln -s "pyloric_MMV_T5_Rep1_R2.fq.gz" "pyloric_MMV_T5_Rep1_2.fastq.gz"
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_AMPLISEQ:AMPLISEQ:RENAME_RAW_DATA_FILES":
      sed: $(sed --version 2>&1 | sed -n 1p | sed 's/sed (GNU sed) //')
  END_VERSIONS

Command exit status:
  255

Command output:
  (empty)

Command error:
  free(): invalid pointer
  FATAL:   container creation failed: mount tmpfs->/opt/software/uoa/spack/linux-rhel8-x86_64/gcc-12.3.0/singularityce-4.1.0-kwaxhpaawfspgtwj7zaieuvdthbpvo7b/var/singularity/mnt/session error: while mounting tmpfs: can't mount tmpfs filesystem to /opt/software/uoa/spack/linux-rhel8-x86_64/gcc-12.3.0/singularityce-4.1.0-kwaxhpaawfspgtwj7zaieuvdthbpvo7b/var/singularity/mnt/session: write unix @->@: write: broken pipe

Work dir:
  /uoa/scratch/users/r02km21/intesParts/work/da/e4f9848a25f7173779402054710ca6

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`
```

### Command used and terminal output

```console
module load nextflow/24.04.3
module load singularity/4.1.0
nextflow run nf-core/ampliseq -r 2.12.0 -name test2 -profile singularity -resume -params-file nf-params.json

{
    "input": ".\/samplesheet.txt",
    "input_folder": ".\/samples\/",
    "FW_primer": "CCTACGGGNGGGCWGCAG",
    "RV_primer": "GACTACHVGGGTATCTAATCC",
    "metadata": ".\/metadata.tsv",
    "outdir": ".\/results",
    "save_intermediates": true,
    "extension": ".\/samples\/*_R{1,2}.fq.gz",
    "double_primer": true,
    "qiime_ref_taxonomy": "greengenes2",
    "metadata_category": "Region,Regime",
    "metadata_category_barplot": "Region,Regime",
    "qiime_adonis_formula": "\"Region*Regime\"",
    "picrust": true,
    "tax_agglom_max": 7,
    "ancom": true,
    "ancombc": true,
    "ancombc_formula": "\"Region*Regime\"",
    "ancombc_formula_reflvl": "\"Region=pyloric\""
}

nf-core/ampliseq execution completed unsuccessfully!
The exit status of the task that caused the workflow execution to fail was: 255.

The full error message was:

Error executing process > 'NFCORE_AMPLISEQ:AMPLISEQ:RENAME_RAW_DATA_FILES (pyloric_MMV_T5_Rep1)'

Caused by:
  Process `NFCORE_AMPLISEQ:AMPLISEQ:RENAME_RAW_DATA_FILES (pyloric_MMV_T5_Rep1)` terminated with an error exit status (255)


Command executed:

  [ -f "pyloric_MMV_T5_Rep1_1.fastq.gz" ] || ln -s "pyloric_MMV_T5_Rep1_R1.fq.gz" "pyloric_MMV_T5_Rep1_1.fastq.gz"
  [ -f "pyloric_MMV_T5_Rep1_2.fastq.gz" ] || ln -s "pyloric_MMV_T5_Rep1_R2.fq.gz" "pyloric_MMV_T5_Rep1_2.fastq.gz"
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_AMPLISEQ:AMPLISEQ:RENAME_RAW_DATA_FILES":
      sed: $(sed --version 2>&1 | sed -n 1p | sed 's/sed (GNU sed) //')
  END_VERSIONS

Command exit status:
  255

Command output:
  (empty)

Command error:
  free(): invalid pointer
  FATAL:   container creation failed: mount tmpfs->/opt/software/uoa/spack/linux-rhel8-x86_64/gcc-12.3.0/singularityce-4.1.0-kwaxhpaawfspgtwj7zaieuvdthbpvo7b/var/singularity/mnt/session error: while mounting tmpfs: can't mount tmpfs filesystem to /opt/software/uoa/spack/linux-rhel8-x86_64/gcc-12.3.0/singularityce-4.1.0-kwaxhpaawfspgtwj7zaieuvdthbpvo7b/var/singularity/mnt/session: write unix @->@: write: broken pipe

Work dir:
  /uoa/scratch/users/r02km21/intesParts/work/da/e4f9848a25f7173779402054710ca6

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`
```

### Relevant files

output[log.txt](https://github.com/user-attachments/files/18011439/log.txt)

### System information

Nextflow version 24.04.3
Hardware HPC
Executor slurm
Container engine: Singularity
OS Linux (Linux maxlogin2.int.maxwell.abdn.ac.uk 4.18.0-372.13.1.el8_6.x86_64 #1 SMP Mon Jun 6 15:05:22 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux)
Version of nf-core/ampliseq 2.12.0

**Comment by d4straub** [comment]
This usually happens when the remote is down/unavailable.
- do you have access to the internet on that machine?
- it might have been a temporary problem, did you try again?

**Comment by marwa38** [comment]
- I used this cluster before but earlier version of ampliseq 2.7 and worked fine
- I use the offline mode always and not sure if there is internet on the machine (Launching with no internet and without nf-core/tools)
- I tried that two times.

**Comment by d4straub** [comment]
If you used the offline mode, then it seems to me that not all containers were available. Can you make sure all containers are available before starting the pipeline in offline mode?

**Comment by marwa38** [comment]
here are the available ones
what do you think?
![Image](https://github.com/user-attachments/assets/dd8c9bd4-a205-4eef-a4d5-58b512ed1308)

**Comment by marwa38** [comment]
could you please let me know what is the exact version you used for developing nf-core/ampliseq 2.12.0?
@d4straub

**Comment by d4straub** [comment]
> here are the available ones
> what do you think?

5 container seems too less? not sure actually

> could you please let me know what is the exact version you used for developing nf-core/ampliseq 2.12.0?

Version of what? I develop with apptainer version 1.3.4, but until recently I had an ancient version of singularity. I also use Docker version 27.3.1 occasionally. The CI tests use docker as well, no idea what version.

**Comment by marwa38** [comment]
@Version of what? I develop with apptainer version 1.3.4, but until recently I had an ancient version of singularity. I also use Docker version 27.3.1 occasionally. The CI tests use docker as well, no idea what version.
I mean would the version of nextflow or singularity make a difference?

@5 container seems too less? not sure actually
I have never needed to check the number of the containers and I checked the config file to check for the container names and could find any, where to find that?

I could use the older version of nfcore ampliseq (2.7) if it is working or you advice against that?

**Comment by d4straub** [comment]
> I mean would the version of nextflow or singularity make a difference?

no

> I have never needed to check the number of the containers and I checked the config file to check for the container names and could find any, where to find that?

in each module file, i.e. modules/local/*.nf or modules/nf-core/*/main.nf, within the first few lines.

> I could use the older version of nfcore ampliseq (2.7) if it is working or you advice against that?

newer version should have less bugs and more functionality. But yes, the older versions should also be fine.

**Comment by marwa38** [comment]
solved by running another version of singularity version 3.8.5
