### ISSUE TITLE
trimming for the second time vs --double_primer?

### ISSUE THREAD

**Issue by marwa38** [nf-core/ampliseq#816]
In a previous run/test of ampliseq, I tried to run cutadapt (i.e., --double_primer FALSE) for one time to get rid of specific primers but I got the following error:
I used trimGalore before on my sequences but I am not sure why I am getting this error if we consider that this ampliseq cutadapt run would be a second primer removal so doing same as the option of double_primer, as I understand.

` trim_galore -q 30 --phred33 --paired --gzip --fastqc --fastqc_args "--nogroup" -o "./trimGalored" --length 20 --stringency 1 -e 0 --clip_R1 17 --clip_R2 21 "${sample}_R1.fq.gz" "${sample}_R2.fq.gz"`

```
{
    "input": ".\/samplesheet.txt",
    "input_folder": ".\/samples\/",
    "FW_primer": "CCTACGGGNGGGCWGCAG",
    "RV_primer": "GACTACHVGGGTATCTAATCC",
    "metadata": ".\/metadata.tsv",
    "outdir": ".\/results",
    "save_intermediates": true,
    "email": "marwa.tawfik@inrae.fr",
    "extension": ".\/samples\/*_R{1,2}.fq.gz",
    "qiime_ref_taxonomy": "greengenes2",
    "metadata_category": "Region,Regime",
    "metadata_category_barplot": "Region,Regime",
    "qiime_adonis_formula": "Region*Regime",
    "picrust": true,
    "tax_agglom_max": 7,
    "ancom": true,
    "ancombc": true,
    "ancombc_formula": "Region*Regime",
    "ancombc_formula_reflvl": "Region::pyloric"
}
```

Why I would get this weird error?
```
nf-core/ampliseq execution completed unsuccessfully!
The exit status of the task that caused the workflow execution to fail was: null.

The full error message was:

The following samples had too few reads (<1) after trimming with cutadapt:
pyloric_MMV_T1_Rep4
pyloric_MMV_T1_Rep2
pyloric_MMV_T5_Rep1
pyloric_MMV_T1_Rep3
pyloric_MMV_T9_Rep3
pyloric_VMV_T3_Rep3
pyloric_VMV_T12_Rep3
pyloric_MMV_T9_Rep1
pyloric_VMV_T3_Rep4
middle_MMV_T1_Rep6
middle_VMV_T3_Rep3
middle_VMV_T12_Rep2
distal_MMV_T1_Rep6
distal_VMV_T8_Rep4
distal_VMV_T12_Rep4
distal_VMV_T12_Rep6
Please check whether the correct primer sequences for trimming were supplied. Ignore that samples using `--ignore_failed_trimming` or adjust the threshold with `--min_read_counts`.




```

**Comment by d4straub** [comment]
`The following samples had too few reads (<1) after trimming with cutadapt:`
says it all, no reads passed for the listed samples.
Check out the documentation, i.e. https://nf-co.re/ampliseq/2.12.0/parameters/#retain_untrimmed and its help text.

Essentially, you removed primer sequences. Then you put the sequences into the pipeline. The pipeline discards via cutadapt all reads that do not have the primers, you removed them before, so all sequences are discarded. You could remedy that by setting `retain_untrimmed`. Or just dont remove primer sequences before.
