### ISSUE TITLE
Unclear if taxonomic relative abundance tables are filtered or unfiltered

### ISSUE THREAD

**Issue by andand** [nf-core/ampliseq#82]
This is not clear in the Documentation or file structure. Ideally the taxonomic abundance tables would be generated both for filtered and unfiltered data, and with both absolute and relative counts (i.e. 4 version).

**Comment by d4straub** [comment]
As said before in #81, absolute and relative counts are already available for all taxonomic levels and ASVs. These are based on filtered absolute abundance tables. Might need to highlight that somewhere, do you have a suggestion?

I do think that having tables in `results/abundance-table/filtered` and `results/abundance-table/unfiltered` is somewhat clear if you are looking at filtered or unfiltered tables. Let me know how I can improve that.

But it is true that unfiltered relative abundance tables are not calculated. Might be interesting to have, I myself was never interested in these.

**Comment by d4straub** [comment]
No further feedback recieved, closed. Let me know if you have suggestions.
