### ISSUE TITLE
Warning after recent updates

### ISSUE THREAD

**Issue by d4straub** [nf-core/ampliseq#83]
WARN: Access to undefined parameter `fasta` -- Initialise it to a default value 
eg. `params.fasta = some_value`

Before commit ba75258f1ca083cc3418b75c648d0adceccb43b5 this warning did not appear, but don't know when this appeared first because I didn't analyze in between.

**Comment by apeltzer** [comment]
Yeah that was introduced via the newest template merge - should probably kick it out again or set `params.fasta = false` in the `nextflow.config`.

**Comment by apeltzer** [comment]
Ah maybe thats in the `summary[...]` part - should probably kick it out from there

**Comment by d4straub** [comment]
Done
