### ISSUE TITLE
Add nf-core logo to README.md

### ISSUE THREAD

**Issue by drpatelh** [nf-core/ampliseq#84]
Just noticed this when trying to get the logo for `ampliseq` for a presentation

**Comment by d4straub** [comment]
Thanks for reporting, could you do that @apeltzer?

**Comment by drpatelh** [comment]
Its ok. I can do that because I have already created the logo. 👍

**Comment by drpatelh** [comment]
Fixed in https://github.com/nf-core/ampliseq/pull/87
