### ISSUE TITLE
`get_software_versions` terminated with an error exit status (127)

### ISSUE THREAD

**Issue by cailiangliang765** [nf-core/ampliseq#85]
```
./nextflow run nf-core/ampliseq -profile standard,docker -c test.config
Pipeline Name  : nf-core/ampliseq
Pipeline Version: 1.0.0
Run Name       : lethal_easley
Reads          : data/*_L001_R{1,2}_001.fastq.gz
Max Memory     : 6 GB
Max CPUs       : 2
Max Time       : 2d
Output dir     : ./results
Working dir    : /home/dind/work
Container Engine: docker
Container      : nfcore/ampliseq:1.0.0
Current home   : /home/dind
Current user   : dind
Current path   : /home/dind
Script dir     : /home/dind/.nextflow/assets/nf-core/ampliseq
Config Profile : standard,docker
=========================================
[warm up] executor > local
executor >  local (2)
[98/0a230b] process > get_software_versions [100%] 1 of 1, failed: 1 ✘
[7b/9a14e9] process > output_documentation  [100%] 1 of 1, failed: 1 ✘
Execution cancelled -- Finishing pending tasks before exit
[nf-core/ampliseq] Pipeline Complete
WARN: To render the execution DAG in the required format it is required to install Graphviz -- See http://www.graphviz.org for more info.
ERROR ~ Error executing process > 'get_software_versions'

Caused by:
  Process `get_software_versions` terminated with an error exit status (127)

Command executed:

  echo 1.0.0 > v_pipeline.txt
  echo 19.04.1 > v_nextflow.txt
  fastqc --version > v_fastqc.txt
  multiqc --version > v_multiqc.txt
  scrape_software_versions.py > software_versions_mqc.yaml

Command exit status:
  127

Command output:
  (empty)

Command error:
  /bin/bash: .command.run: No such file or directory

Work dir:
  /home/dind/work/98/0a230b19437d51ad128fa2c2b83ede

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

 -- Check '.nextflow.log' file for details
```

**Comment by cailiangliang765** [comment]
@apeltzer @ewels @matq007 I run nextflow in the dockerindocker docker container based on Alpine linux OS. I met this error.  I use this method because it is more efficient and convenient.

**Comment by apeltzer** [comment]
Why? I don't really see a reason to run a Nextflow pipeline inside another Docker layer if I understood correctly what you're doing here. The tests for the pipeline are just fine, tested the release you were using myself and wasn't experiencing that error on both a Docker workstation and a Singularity host...

**Comment by cailiangliang765** [comment]
> Why? I don't really see a reason to run a Nextflow pipeline inside another Docker layer if I understood correctly what you're doing here. The tests for the pipeline are just fine, tested the release you were using myself and wasn't experiencing that error on both a Docker workstation and a Singularity host...

I don't know if it's just a personal request. I usually do molecular biology experiments. However, after a period of time, such as half a year, I run the current pipline, due to upgrading and other reasons, I cannot perform the same analysis. I tried conda, it seems that it still has some dependency problems, the biggest trouble is that it can't save in the hard disk. But docker can solve this problem. It is true that you have built corresponding docker containers, such as nfcore/ampliseq:1.0.0. Some problems may still occur in nextflow installed into host system after a period of time, such as the update of nextflow version. But it does take me quite a while to sort it out. What's more, I can share this usable container with lab members.

**Comment by apeltzer** [comment]
> I don't know if it's just a personal request. I usually do molecular biology experiments. However, after a period of time, such as half a year, I run the current pipline, due to upgrading and other reasons, I cannot perform the same analysis. 

This is entirely solved when using Docker/Singularity + Nextflow with this pipeline as you can always go back and specify to run a specific release of this pipeline, e.g.

```
nextflow run nf-core/ampliseq -r 1.0.0 ....
```

> I tried conda, it seems that it still has some dependency problems, the biggest trouble is that it can't save in the hard disk. But docker can solve this problem. It is true that you have built corresponding docker containers, such as nfcore/ampliseq:1.0.0. Some problems may still occur in nextflow installed into host system after a period of time, such as the update of nextflow version.

You can also enforce using a specific nextflow version following this here: 

https://www.nextflow.io/docs/latest/config.html#environment-variables

If you then simply share your `nextflow run ....` call and tell people they need Docker/Singularity installed, this is enough to reproduce at any point all of your analysis.

I'll close this for now - if you have more questions, also feel free to join the Slack channel https://nf-core-invite.herokuapp.com/ (channel #ampliseq)
