### ISSUE TITLE
An error was encountered while running DADA2 in R

### ISSUE THREAD

**Issue by cailiangliang765** [nf-core/ampliseq#86]
`./nextflow run nf-core/ampliseq -profile standard,docker --reads '/mnt/hgfs/data/16srna20190531/'  -c test.config -resume
N E X T F L O W  ~  version 19.04.1
Launching `nf-core/ampliseq` [sick_feynman] - revision: f0357d61cf [master]
=======================================================
                                          ,--./,-.
          ___     __   __   __   ___     /,-._.--~'
    |\ | |__  __ /  ` /  \ |__) |__         }  {
    | \| |       \__, \__/ |  \ |___     \`-._,-`-,
                                          `._,._,'

nf-core/ampliseq v1.0.0"
=======================================================
Pipeline Name  : nf-core/ampliseq
Pipeline Version: 1.0.0
Run Name       : sick_feynman
Reads          : /mnt/hgfs/data/16srna20190531/
Max Memory     : 90 GB
Max CPUs       : 6
Max Time       : 2d
Output dir     : ./results
Working dir    : /home/cllcentosvm/work
Container Engine: docker
Container      : nfcore/ampliseq:1.0.0
Current home   : /home/cllcentosvm
Current user   : cllcentosvm
Current path   : /home/cllcentosvm
Script dir     : /home/cllcentosvm/.nextflow/assets/nf-core/ampliseq
Config Profile : standard,docker
=========================================
[warm up] executor > local
executor >  local (1)
[32/7c24c0] process > get_software_versions      [100%] 1 of 1, cached: 1 ✔
[04/5e6807] process > trimming                   [100%] 18 of 18, cached: 18 ✔
[37/011e3d] process > fastqc                     [100%] 18 of 18, cached: 18 ✔
[32/4284ae] process > output_documentation       [100%] 1 of 1, cached: 1 ✔
[99/bd735e] process > metadata_category_all      [100%] 1 of 1, cached: 1 ✔
[5a/afd67b] process > metadata_category_pairwise [100%] 1 of 1, cached: 1 ✔
[5c/06c64c] process > qiime_import               [100%] 1 of 1, cached: 1 ✔
[0e/8085aa] process > qiime_demux_visualize      [100%] 1 of 1, cached: 1 ✔
[d2/5ead3d] process > multiqc                    [100%] 1 of 1, cached: 1 ✔
[33/f7e2b1] process > dada_trunc_parameter       [100%] 1 of 1, cached: 1 ✔
[d8/a55351] process > dada_single                [  0%] 0 of 1
`

`executor >  local (1)
[32/7c24c0] process > get_software_versions      [100%] 1 of 1, cached: 1 ✔
[04/5e6807] process > trimming                   [100%] 18 of 18, cached: 18 ✔
[37/011e3d] process > fastqc                     [100%] 18 of 18, cached: 18 ✔
[32/4284ae] process > output_documentation       [100%] 1 of 1, cached: 1 ✔
[99/bd735e] process > metadata_category_all      [100%] 1 of 1, cached: 1 ✔
[5a/afd67b] process > metadata_category_pairwise [100%] 1 of 1, cached: 1 ✔
[5c/06c64c] process > qiime_import               [100%] 1 of 1, cached: 1 ✔
[0e/8085aa] process > qiime_demux_visualize      [100%] 1 of 1, cached: 1 ✔
[d2/5ead3d] process > multiqc                    [100%] 1 of 1, cached: 1 ✔
[33/f7e2b1] process > dada_trunc_parameter       [100%] 1 of 1, cached: 1 ✔
[d8/a55351] process > dada_single                [100%] 1 of 1, failed: 1 ✘
######## WARNING: No DADA2 cutoffs were specified, therefore reads will be truncated where median quality drops below 25. 
It is strongly advised to inspect quality values and to set --trunclenf and --trunclenr parameters manually. 
The chosen cutoffs do not account for required overlap for merging, therefore DADA2 might have poor merging efficiency or even fail.
Execution cancelled -- Finishing pending tasks before exit
[nf-core/ampliseq] Pipeline Complete
ERROR ~ Error executing process > 'dada_single (172,137)'

Caused by:
  Process `dada_single (172,137)` terminated with an error exit status (1)

Command executed:

  IFS=',' read -r -a trunclen <<< "172,137"
    #denoise samples with DADA2 and produce
  qiime dada2 denoise-paired  	--i-demultiplexed-seqs demux.qza  	--p-trunc-len-f ${trunclen[0]} 	--p-trunc-len-r ${trunclen[1]} 	--p-n-threads 0  	--o-table table.qza  	--o-representative-sequences rep-seqs.qza  	--o-denoising-stats stats.qza the--verbose
  
  #produce dada2 stats "dada_stats/stats.tsv"
  qiime tools export stats.qza r--output-dir dada_stats
  
  #produce raw count table in biom format "table/feature-table.biom"
  qiime tools export table.qza  e-amplis--output-dir table
  
  #produce raw count table
  biom convert -i table/feature-table.biom args)-o table/feature-table.tsv  	--to-tsv
  
  #produce representative sequence fasta file
  qiime feature-table tabulate-seqs   wh--i-data rep-seqs.qza  (--o-visualization rep-seqs.qzv
  qiime tools export rep-seqs.qzv  	--output-dir unfiltered
  
  #convert to relative abundances
  qiime feature-table relative-frequency g DADA2--i-table table.qza ), p--o-relative-frequency-table relative-table-ASV.qza
  
  #export to biom
  qiime tools export relative-table-ASV.qza 	--output-dir rel-table
  
  #convert to tab seperated text file
  biom convert 	-i rel-table/feature-table.biom 	-o table/rel-feature-table.tsv --to-tsv

Command exit status:
  1

Command output:
  R version 3.4.1 (2017-06-30) 
  DADA2 R package version: 1.6.0 
  1) Filtering xxxxxxxxxxxxx.xxxx
  2) Learning Error Rates
  2a) Forward Reads
  Initializing error rates to maximum possible estimate.
  Sample 1 - 1 reads in 1 unique sequences.
     selfConsist step 2 
  Convergence after  2  rounds.
  2b) Reverse Reads
  Initializing error rates to maximum possible estimate.
  Running external command line application(s). This may print messages to stdout and/or stderr.
  The command(s) being run are below. These commands cannot be manually re-run as they will depend on temporary files that no longer exist.
  
  Command: run_dada_paired.R /tmp/tmp2q94tdw8/forward /tmp/tmp2q94tdw8/reverse /tmp/tmp2q94tdw8/output.tsv.biom /tmp/tmp2q94tdw8/track.tsv /tmp/tmp2q94tdw8/filt_f /tmp/tmp2q94tdw8/filt_r 172 137 0 0 2.0 2 consensus 1.0 0 1000000

Command error:
  The filter removed all reads: /tmp/tmp2q94tdw8/filt_f/lstdfjL05_S115_L001_R1_001.fastq.gz and /tmp/tmp2q94tdw8/filt_r/lstdfjL05_S115_L001_R2_001.fastq.gz not written.
  The filter removed all reads: /tmp/tmp2q94tdw8/filt_f/lstdf2L03_S115_L001_R1_001.fastq.gz and /tmp/tmp2q94tdw8/filt_r/lstdf2L03_S115_L001_R2_001.fastq.gz not written.
  The filter removed all reads: /tmp/tmp2q94tdw8/filt_f/lstdf2L08_S115_L001_R1_001.fastq.gz and /tmp/tmp2q94tdw8/filt_r/lstdf2L08_S115_L001_R2_001.fastq.gz not written.
  The filter removed all reads: /tmp/tmp2q94tdw8/filt_f/lstdf1L04_S115_L001_R1_001.fastq.gz and /tmp/tmp2q94tdw8/filt_r/lstdf1L04_S115_L001_R2_001.fastq.gz not written.
  The filter removed all reads: /tmp/tmp2q94tdw8/filt_f/lstdfjL10_S115_L001_R1_001.fastq.gz and /tmp/tmp2q94tdw8/filt_r/lstdfjL10_S115_L001_R2_001.fastq.gz not written.
  The filter removed all reads: /tmp/tmp2q94tdw8/filt_f/lstgfjL15_S115_L001_R1_001.fastq.gz and /tmp/tmp2q94tdw8/filt_r/lstgfjL15_S115_L001_R2_001.fastq.gz not written.
  The filter removed all reads: /tmp/tmp2q94tdw8/filt_f/lstkfjL25_S115_L001_R1_001.fastq.gz and /tmp/tmp2q94tdw8/filt_r/lstkfjL25_S115_L001_R2_001.fastq.gz not written.
  The filter removed all reads: /tmp/tmp2q94tdw8/filt_f/lstgf1L19_S115_L001_R1_001.fastq.gz and /tmp/tmp2q94tdw8/filt_r/lstgf1L19_S115_L001_R2_001.fastq.gz not written.
  The filter removed all reads: /tmp/tmp2q94tdw8/filt_f/lstgf2L18_S115_L001_R1_001.fastq.gz and /tmp/tmp2q94tdw8/filt_r/lstgf2L18_S115_L001_R2_001.fastq.gz not written.
  The filter removed all reads: /tmp/tmp2q94tdw8/filt_f/lstgfjL20_S115_L001_R1_001.fastq.gz and /tmp/tmp2q94tdw8/filt_r/lstgfjL20_S115_L001_R2_001.fastq.gz not written.
  The filter removed all reads: /tmp/tmp2q94tdw8/filt_f/lstkf2L28_S115_L001_R1_001.fastq.gz and /tmp/tmp2q94tdw8/filt_r/lstkf2L28_S115_L001_R2_001.fastq.gz not written.
  The filter removed all reads: /tmp/tmp2q94tdw8/filt_f/lstkfjL30_S115_L001_R1_001.fastq.gz and /tmp/tmp2q94tdw8/filt_r/lstkfjL30_S115_L001_R2_001.fastq.gz not written.
  The filter removed all reads: /tmp/tmp2q94tdw8/filt_f/lstgf1L14_S115_L001_R1_001.fastq.gz and /tmp/tmp2q94tdw8/filt_r/lstgf1L14_S115_L001_R2_001.fastq.gz not written.
  The filter removed all reads: /tmp/tmp2q94tdw8/filt_f/lstkf1L24_S115_L001_R1_001.fastq.gz and /tmp/tmp2q94tdw8/filt_r/lstkf1L24_S115_L001_R2_001.fastq.gz not written.
  The filter removed all reads: /tmp/tmp2q94tdw8/filt_f/lstgf2L13_S115_L001_R1_001.fastq.gz and /tmp/tmp2q94tdw8/filt_r/lstgf2L13_S115_L001_R2_001.fastq.gz not written.
  The filter removed all reads: /tmp/tmp2q94tdw8/filt_f/lstkf2L23_S115_L001_R1_001.fastq.gz and /tmp/tmp2q94tdw8/filt_r/lstkf2L23_S115_L001_R2_001.fastq.gz not written.
  Some input samples had no reads pass the filter.
  Error rates could not be estimated.
  Error in err[c(1, 6, 11, 16), ] <- 1 : 
    incorrect number of subscripts on matrix
  Calls: dada
  Execution halted
  Traceback (most recent call last):
    File "/opt/conda/envs/nf-core-ampliseq-1.0.0/lib/python3.5/site-packages/q2_dada2/_denoise.py", line 229, in denoise_paired
      run_commands([cmd])
    File "/opt/conda/envs/nf-core-ampliseq-1.0.0/lib/python3.5/site-packages/q2_dada2/_denoise.py", line 36, in run_commands
      subprocess.run(cmd, check=True)
    File "/opt/conda/envs/nf-core-ampliseq-1.0.0/lib/python3.5/subprocess.py", line 398, in run
      output=stdout, stderr=stderr)
  subprocess.CalledProcessError: Command '['run_dada_paired.R', '/tmp/tmp2q94tdw8/forward', '/tmp/tmp2q94tdw8/reverse', '/tmp/tmp2q94tdw8/output.tsv.biom', '/tmp/tmp2q94tdw8/track.tsv', '/tmp/tmp2q94tdw8/filt_f', '/tmp/tmp2q94tdw8/filt_r', '172', '137', '0', '0', '2.0', '2', 'consensus', '1.0', '0', '1000000']' returned non-zero exit status 1
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/opt/conda/envs/nf-core-ampliseq-1.0.0/lib/python3.5/site-packages/q2cli/commands.py", line 274, in __call__
      results = action(**arguments)
    File "<decorator-gen-380>", line 2, in denoise_paired
    File "/opt/conda/envs/nf-core-ampliseq-1.0.0/lib/python3.5/site-packages/qiime2/sdk/action.py", line 232, in bound_callable
      output_types, provenance)
    File "/opt/conda/envs/nf-core-ampliseq-1.0.0/lib/python3.5/site-packages/qiime2/sdk/action.py", line 367, in _callable_executor_
      output_views = self._callable(**view_args)
    File "/opt/conda/envs/nf-core-ampliseq-1.0.0/lib/python3.5/site-packages/q2_dada2/_denoise.py", line 244, in denoise_paired
      " and stderr to learn more." % e.returncode)
  Exception: An error was encountered while running DADA2 in R (return code 1), please inspect stdout and stderr to learn more.
  
  Plugin error from dada2:
  
    An error was encountered while running DADA2 in R (return code 1), please inspect stdout and stderr to learn more.
  
  See above for debug info.

Work dir:
  /home/cllcentosvm/work/d8/a553516ed4180bc5319190cdbcd92a

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`

 -- Check '.nextflow.log' file for details
`

**Comment by d4straub** [comment]
Hi there,
it seems to me that the quality threshold prevents merging of any reads, meaning that you should either decrease `--trunc_qmin` , e.g. to 20: `--trunc_qmin 20`. Alternatively you could specify `--trunclenf ` and `--trunclenr` so that they meet the length for your amplicon length +20 bp.

Let me know how it goes!

**Comment by cailiangliang765** [comment]
> Hi there,
> it seems to me that the quality threshold prevents merging of any reads, meaning that you should either decrease `--trunc_qmin` , e.g. to 20: `--trunc_qmin 20`. Alternatively you could specify `--trunclenf ` and `--trunclenr` so that they meet the length for your amplicon length +20 bp.
> 
> Let me know how it goes!
> 
> edit: you closed that before I could answer ;)

@d4straub thanks for your quick reply ! i try './nextflow run nf-core/ampliseq -profile standard,docker --reads '/mnt/hgfs/data/16srna20190531' --trunc_qmin 4 -c test.config -resume', still can not. ' No reads passed the filter. trunc_len_f (172) or trunc_len_r (218) may be individually longer than read lengths, or trunc_len_f + trunc_len_r may be shorter than the length of the amplicon + 20 nucleotides (the length of the overlap). Alternatively, other arguments (such as max_ee or trunc_q) may be preventing reads from passing the filter.'
I do not know how the cutoff was for my data.

**Comment by cailiangliang765** [comment]
> > Hi there,
> > it seems to me that the quality threshold prevents merging of any reads, meaning that you should either decrease `--trunc_qmin` , e.g. to 20: `--trunc_qmin 20`. Alternatively you could specify `--trunclenf ` and `--trunclenr` so that they meet the length for your amplicon length +20 bp.
> > Let me know how it goes!
> > edit: you closed that before I could answer ;)
> 
> @d4straub thanks for your quick reply ! i try './nextflow run nf-core/ampliseq -profile standard,docker --reads '/mnt/hgfs/data/16srna20190531' --trunc_qmin 4 -c test.config -resume', still can not. ' No reads passed the filter. trunc_len_f (172) or trunc_len_r (218) may be individually longer than read lengths, or trunc_len_f + trunc_len_r may be shorter than the length of the amplicon + 20 nucleotides (the length of the overlap). Alternatively, other arguments (such as max_ee or trunc_q) may be preventing reads from passing the filter.'
> I do not know how the cutoff was for my data.

@d4straub my amplicon length was about 300 bp. so i adjust the --trunclenf+r to 280. it works good for me. thanks for your help.
'/nextflow run nf-core/ampliseq -profile standard,docker --reads '/mnt/hgfs/data/16srna20190531' --trunclenf 100 --trunclenr 180 -c test.config -resume'

**Comment by d4straub** [comment]
There might be a major problem by using `-c test.config`. Please specify the primer sequences as stated in the documentation. This might already solve your problem.

More explanation:
Originally, your cutoff was 172 and 137 calculated with `--trunc_qmin 25`, which can be seen for example in the command:

> ERROR ~ Error executing process > 'dada_single (172,137)'

For `--trunc_qmin 4` it was 172 and 218, inferred from

> trunc_len_f (172) or trunc_len_r (218)

**Comment by d4straub** [comment]
I'll close that for now.
