### ISSUE TITLE
Requested level of 7 is larger than the maximum level available in taxonomy data (6).

### ISSUE THREAD

**Issue by cailiangliang765** [nf-core/ampliseq#88]
`nextflow run nf-core/ampliseq -profile standard,docker --reads '/mnt/hgfs/data/16srna20190531/' \
--FW_primer GTGCCAGCMGCCGCGGTAA --RV_primer GGACTACHVGGGTWTCTAAT \
--metadata "/mnt/hgfs/data/16srna20190531/Metadata.tsv" \
--classifier "/mnt/hgfs/data/16srna20190531/classifier.qza" \
--metadata_category "treatment1" \
--trunclenf 100 --trunclenr 180 \
--max_cpus 6 \
--max_memory '90.GB' \
-resume`

[93/c77056] process > report_filter_stats          [100%] 1 of 1, cached: 1 ✔
[eb/1338ae] process > metadata_category_pairwise   [100%] 1 of 1 ✔
[88/8fe50b] process > prepare_ancom                [100%] 1 of 1 ✔
[f8/8b38f1] process > barplot                      [100%] 1 of 1 ✔
[3a/c66c60] process > RelativeAbundanceReducedTaxa [100%] 1 of 1, failed: 1 ✘
[26/fbb19a] process > RelativeAbundanceASV         [100%] 1 of 1 ✔
[26/8cf20e] process > multiqc                      [100%] 1 of 1 ✔
[8f/c564d1] process > combinetable                 [100%] 1 of 1 ✔
[f5/f91277] process > tree                         [100%] 1 of 1 ✔
Execution cancelled -- Finishing pending tasks before exit
ERROR ~ Error executing process > 'RelativeAbundanceReducedTaxa (1)'

Caused by:
  Process `RelativeAbundanceReducedTaxa (1)` terminated with an error exit status (1)

Command executed:

  ##on several taxa level
  
  array=( 2 3 4 5 6 7 )
  for i in ${array[@]}
  do
   #collapse taxa
   qiime taxa collapse equency]     --i-table filtered-table.qza 		    --i-taxonomy taxonomy.qza 		    --p-level $i 		    --o-collapsed-table table-$i.qza
   #convert to relative abundances
   qiime feature-table relative-frequency 6.qza 	    --i-table table-$i.qza 		    --o-relative-frequency-table relative-table-$i.qza
   #export to biom
   qiime tools export relative-table-$i.qza 		    --output-dir relative-table-$i
   #convert to tab seperated text file
   biom convert rom taxa:           -i relative-table-$i/feature-table.biom 		    -o rel-table-$i.tsv --to-tsv
  done

Command exit status:
  1

Command output:
  Saved FeatureTable[Frequency] to: table-2.qza
  Saved FeatureTable[RelativeFrequency] to: relative-table-2.qza
  Saved FeatureTable[Frequency] to: table-3.qza
  Saved FeatureTable[RelativeFrequency] to: relative-table-3.qza
  Saved FeatureTable[Frequency] to: table-4.qza
  Saved FeatureTable[RelativeFrequency] to: relative-table-4.qza
  Saved FeatureTable[Frequency] to: table-5.qza
  Saved FeatureTable[RelativeFrequency] to: relative-table-5.qza
  Saved FeatureTable[Frequency] to: table-6.qza
  Saved FeatureTable[RelativeFrequency] to: relative-table-6.qza

Command error:
  Plugin error from taxa:
  
    Requested level of 7 is larger than the maximum level available in taxonomy data (6).
  
  Debug info has been saved to /tmp/qiime2-q2cli-err-k8465gx2.log

Work dir:
  /home/cllcentosvm/work/3a/c66c6097bedc4db9a5997489f4322f

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

 -- Check '.nextflow.log' file for details

**Comment by cailiangliang765** [comment]
`qiime tools import \
--type 'FeatureData[Sequence]' \
--input-path ./SILVA_132_QIIME_release/rep_set/rep_set_16S_only/99/silva_132_99_16S.fna \
--output-path silva_132_99_16S.qza


qiime tools import \
--type 'FeatureData[Taxonomy]' \
--source-format HeaderlessTSVTaxonomyFormat \
--input-path ./SILVA_132_QIIME_release/taxonomy/16S_only/99/taxonomy_7_levels.txt  \
--output-path ref-taxonomy.qza


qiime feature-classifier extract-reads 	\
--i-sequences silva_132_99_16S.qza \
--p-f-primer GTGCCAGCMGCCGCGGTAA --p-r-primer GGACTACHVGGGTWTCTAAT \
--p-trunc-len 120 \
--o-reads ref-seqs.qza


qiime feature-classifier fit-classifier-naive-bayes \
--i-reference-reads ref-seqs.qza \
--i-reference-taxonomy ref-taxonomy.qza \
--o-classifier classifier.qza`

**Comment by d4straub** [comment]
I assume the second message contains the commands you used for training the classifier for the first ampliseq run? A line of explanation might make it easier to troubleshoot...

Your classifier is not what ampliseq expects. Somehow it contains one taxonomy level less than SILVA usually has. Since you did not train the classifier by ampliseq but on your own, I cant say what might fix it. 

Probably use the full length pre-trained classifier: https://data.qiime2.org/2018.6/common/silva-132-99-nb-classifier.qza if that raises an error too than I have to make a fix.

**Comment by cailiangliang765** [comment]
> I assume the second message contains the commands you used for training the classifier for the first ampliseq run? A line of explanation might make it easier to troubleshoot...
> 
> Your classifier is not what ampliseq expects. Somehow it contains one taxonomy level less than SILVA usually has. Since you did not train the classifier by ampliseq but on your own, I cant say what might fix it.
> 
> Probably use the full length pre-trained classifier: https://data.qiime2.org/2018.6/common/silva-132-99-nb-classifier.qza if that raises an error too than I have to make a fix.
That still doesn't solve the problem.
`nextflow run nf-core/ampliseq -profile standard,docker --reads '/mnt/hgfs/data/16srna20190531/' \
> --FW_primer GTGCCAGCMGCCGCGGTAA --RV_primer GGACTACHVGGGTWTCTAAT \
> --metadata "/mnt/hgfs/data/16srna20190531/Metadata.tsv" \
> --classifier "/mnt/hgfs/data/16srna20190531/silva-132-99-nb-classifier.qza" \
> --metadata_category "treatment1" \
> --trunclenf 100 --trunclenr 180 \
> --max_cpus 6 \
> --max_memory '90.GB'`
[3e/70761b] process > fastqc                       [100%] 18 of 18 ✔
[32/79599c] process > get_software_versions        [100%] 1 of 1 ✔
[a5/69de26] process > trimming                     [100%] 18 of 18 ✔
[c4/eb2225] process > metadata_category_pairwise   [100%] 1 of 1 ✔
[9a/b41d43] process > metadata_category_all        [100%] 1 of 1 ✔
[7e/cf0dc4] process > output_documentation         [100%] 1 of 1 ✔
[a9/fb1620] process > qiime_import                 [100%] 1 of 1 ✔
[e7/6a3747] process > multiqc                      [100%] 1 of 1 ✔
[fd/2d45f0] process > qiime_demux_visualize        [100%] 1 of 1 ✔
[6a/fa0279] process > dada_trunc_parameter         [100%] 1 of 1 ✔
[f5/094daa] process > dada_single                  [100%] 1 of 1 ✔
[f4/714305] process > classifier                   [100%] 1 of 1 ✔
[ac/e0d190] process > filter_taxa                  [100%] 1 of 1 ✔
[01/6f4288] process > RelativeAbundanceReducedTaxa [100%] 1 of 1, failed: 1 ✘
[32/9c5055] process > barplot                      [100%] 1 of 1 ✔
[57/752ec4] process > prepare_ancom                [100%] 1 of 1 ✔[54/d2158f] process > RelativeAbundanceASV         [100%] 1 of 1 ✔
[90/5ced26] process > export_filtered_dada_output  [100%] 1 of 1 ✔
[d2/f7085a] process > tree                         [100%] 1 of 1 ✔
Execution cancelled -- Finishing pending tasks before exit
ERROR ~ Error executing process > 'RelativeAbundanceReducedTaxa (1)'

Caused by:
  Process `RelativeAbundanceReducedTaxa (1)` terminated with an error exit status (1)

Command executed:

  ##on several taxa level
  
  array=( 2 3 4 5 6 7 )
  for i in ${array[@]}
  do
   #collapse taxa
   qiime taxa collapse 		    --i-table filtered-table.qza 		    --i-taxonomy taxonomy.qza 		    --p-level $i 		    --o-collapsed-table table-$i.qza
   #convert to relative abundances
   qiime feature-table relative-frequency 		    --i-table table-$i.qza 	        --o-relative-frequency-table relative-table-$i.qza
   #export to biom
   qiime tools export relative-table-$i.qza 		    --output-dir relative-table-$i
   #convert to tab seperated text file
   biom convert 		    -i relative-table-$i/feature-table.biom 		    -o rel-table-$i.tsv --to-tsv
  done

Command exit status:
  1

Command output:
  Saved FeatureTable[Frequency] to: table-2.qza
  Saved FeatureTable[RelativeFrequency] to: relative-table-2.qza
  Saved FeatureTable[Frequency] to: table-3.qza
  Saved FeatureTable[RelativeFrequency] to: relative-table-3.qza
  Saved FeatureTable[Frequency] to: table-4.qza
  Saved FeatureTable[RelativeFrequency] to: relative-table-4.qza
  Saved FeatureTable[Frequency] to: table-5.qza
  Saved FeatureTable[RelativeFrequency] to: relative-table-5.qza
  Saved FeatureTable[Frequency] to: table-6.qza
  Saved FeatureTable[RelativeFrequency] to: relative-table-6.qza

Command error:
  Plugin error from taxa:
  
    Requested level of 7 is larger than the maximum level available in taxonomy data (6).
  
  Debug info has been saved to /tmp/qiime2-q2cli-err-4byy3g13.log

Work dir:
  /home/cllcentosvm/work/01/6f4288b18ec2d6acfc08620fb19274

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

 -- Check '.nextflow.log' file for details

**Comment by cailiangliang765** [comment]
@d4straub I need to produce my primers-based classifier strictly in accordance with the main.nf file.  Now the problem is solved. thank you
