### ISSUE TITLE
Best practice for containers

### ISSUE THREAD

**Issue by DiegoBrambilla** [nf-core/ampliseq#94]
Hi,
I am planning on developing a branch of the ampliseq workflow that relies on [R-DADA2](http://benjjneb.github.io/dada2/) instead of the [DADA2 plugin of QIIME2](https://docs.qiime2.org/2019.4/plugins/available/dada2/).

For this end, I would like to include into a container a bundle of R executable files coming from [this repository](https://github.com/erikrikarddaniel/eemisdada2).

Do you suggest creating a new Dockerfile to use for docker/singularity/uppmax profiles, editing the [existing dockerfile](https://hub.docker.com/r/nfcore/ampliseq/dockerfile) or creating a Singularityfile to use for singularity-based profiles?
Thanks in advance

**Comment by d4straub** [comment]
I suggest using the [bioconductor package of DADA2](https://bioconda.github.io/recipes/bioconductor-dada2/README.html) in the environmental.yml file. For this, adding the line `  - bioconductor-dada2=1.10.0` under `dependencies:` should suffice.

I recently build a docker container and also needed to add `RUN apt-get install -y libgfortran3 && apt-get clean` into the `Dockerfile`. 

Best of luck!

**Comment by d4straub** [comment]
I actually found [these documents](https://github.com/benjjneb/LRASManuscript) quite helpful when analyzing PacBio with DADA2.

**Comment by DiegoBrambilla** [comment]
Thank you for the helpful information.
My colleagues working with PacBio read files will appreciate the suggestion.
I will upload the R scripts from [this repository](https://github.com/erikrikarddaniel/eemisdada2) to Anaconda so that it will be possible to add them to `environment.yml`.
Of course, since they rely on dada2, I will include the relative package and the necessary prerequisites under `dependencies` in `environment.yml` .

**Comment by DiegoBrambilla** [comment]
Hello,
I've looked into [Conda documentation](https://docs.anaconda.com/anaconda-cloud/user-guide/tasks/work-with-packages/#using-package-managers) a bit. It seems one needs a channel to put programs in Anaconda.
I guess this channel could be hosted by the Anaconda cloud and perhaps one can host one's own channel.
For development prupose, I suppose it would be best to have something local, i.e. non-official. Did you share any original scripts through Conda?
Did you happen to [deploy any packages from Travis CI](https://gist.github.com/zshaheen/fe76d1507839ed6fbfbccef6b9c13ed9)?
Did you create any channels?

**Comment by d4straub** [comment]
Nope, I have no experience with this.

@apeltzer might have experience with this.

**Comment by drpatelh** [comment]
@DiegoBrambilla We normally encourage missing pipeline dependencies to be added to `bioconda`. 
https://bioconda.github.io/contributor/index.html

It seems that the additional scripts arent under version control i.e. `0 releases` which makes things slightly trickier...you could create a `bioconda` recipe anyway (if its permitted without a release) and then the pipeline will work with `Conda`, `Docker` and `Singularity` or you could add `- bioconductor-dada2=1.10.0` to `environment.yml` and add the commands below to the `Dockerfile` but the pipeline wont work with `-profile conda`...
https://github.com/erikrikarddaniel/eemisdada2#installation

**Comment by d4straub** [comment]
Crazy idea, but why don't you add the R scripts from erikrikarddaniel/eemisdada2 into the `bin` folder and execute them in `main.nf`? I think that would solve these problems. You could acknowledge the scripts in the documentation.

**Comment by drpatelh** [comment]
That would work too 👍 Seeing as they arent under version control anyway dont think it will matter. Will just have to be updated manually when/if they are changed.

**Comment by DiegoBrambilla** [comment]
Thank you.
The approach suggested by @d4straub works for testing the R scripts locally, and I am using it to develop the dada2-based nf script.
We are aiming for what @drpatelh  suggested (adding pipeline dependencies on bioconda or Anaconda somehow). That would imply more administrative effort, like keeping track of bug fixes, but this is what it means to work reproducibly.
I would consider releasing external scripts in `ampliseq/bin` only as a last resort.
Let's keep up the good work!

**Comment by d4straub** [comment]
So that's resolved? I close it.
