### ISSUE TITLE
Qiime fails on headless host

### ISSUE THREAD

**Issue by marchoeppner** [nf-core/ampliseq#95]
Hi, 
so I am running this on a headless node and am getting an error that corresponds to:

`https://forum.qiime2.org/t/error-in-qiime-feature-table-summarize/308`

This can be solved by running:

`echo "backend: Agg" > ~/.config/matplotlib/matplotlibrc`

Wondering if this is something the pipeline should do so users don't stumble over this? Although I am unclear on whether this might interfere with other things outside of this pipeline.

**Comment by d4straub** [comment]
How did you run this? To troubleshoot it would be nice to have the command you attempted to execute. 
This problem should not appear with `-profile docker` or `singularity`. Also with conda it shouldnt happen.
However, when you try to execute the container directly (e.g. `singularity exec <container> <command>`) than this might happen.

**Comment by d4straub** [comment]
Unfortunately no feedback for 2 weeks, maybe this was resolved somehow. Feel free to open another issue with more details, especially to the command to execute the pipeline.
