### ISSUE TITLE
Add Zenodo DOI for release to main README on master

### ISSUE THREAD

**Issue by drpatelh** [nf-core/ampliseq#99]
Would be good to add the Zenodo DOI for the release to the main README of the pipeline in order to make it citable. You will have to do this via a branch pushed to the repo in order to directly update `master`. See PR below for example and file changes:
https://github.com/nf-core/atacseq/pull/38

See https://zenodo.org/record/3336321#.XVZ0bOhKhPY

Web-hooks are already set-up for this repo to have a unique Zenodo DOI generated everytime a new version of the pipeline is released. Would be good to add this in after every release :+1:

**Comment by d4straub** [comment]
Totally agree.
